import type { Move } from "../domain/move";

import { Class, StatusEffectType } from "../domain/move";
import { Stat } from "../domain/stat";
import { Type } from "../domain/type";

export const MOVES = {
	POUND: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	KARATE_CHOP: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	DOUBLE_SLAP: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 15,
		accuracy: 85,
		pp: 10,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	COMET_PUNCH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 18,
		accuracy: 85,
		pp: 15,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	MEGA_PUNCH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 80,
		accuracy: 85,
		pp: 20,
		effect: { kind: "none" },
	},
	PAY_DAY: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FIRE_PUNCH: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
	ICE_PUNCH: {
		type: Type.ICE,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Freeze, chance: 0.1 },
	},
	THUNDER_PUNCH: {
		type: Type.ELECTRIC,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.1 },
	},
	SCRATCH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	STOMP: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "flinch", chance: 0.3 },
	},
	DOUBLE_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 30,
		accuracy: 100,
		pp: 30,
		effect: { kind: "multi-hit", hits: 2 },
	},
	TACKLE: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	QUICK_ATTACK: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "priority", value: 1 },
	},
	BODY_SLAM: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 85,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.3 },
	},
	WRAP: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 15,
		accuracy: 90,
		pp: 20,
		effect: { kind: "partial-trap", turns: 4 },
	},
	TAKE_DOWN: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 90,
		accuracy: 85,
		pp: 20,
		effect: { kind: "recoil", ratio: 0.25 },
	},
	THRASH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DOUBLE_EDGE: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "recoil", ratio: 1 / 3 },
	},
	TAIL_WHIP: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "target" },
	},
	POISON_STING: {
		type: Type.POISON,
		class: Class.Physical,
		power: 15,
		accuracy: 100,
		pp: 35,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 0.3 },
	},
	TWINEEDLE: {
		type: Type.BUG,
		class: Class.Physical,
		power: 25,
		accuracy: 100,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "multi-hit", hits: 2 },
				{ kind: "apply-status", status: StatusEffectType.Poison, chance: 0.2 },
			],
		},
	},
	PIN_MISSILE: {
		type: Type.BUG,
		class: Class.Physical,
		power: 25,
		accuracy: 95,
		pp: 20,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	LEER: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "target" },
	},
	BITE: {
		type: Type.DARK,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 25,
		effect: { kind: "flinch", chance: 0.3 },
	},
	GROWL: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: -1, target: "target" },
	},
	VINE_WHIP: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 45,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	RAZOR_LEAF: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 55,
		accuracy: 95,
		pp: 25,
		effect: { kind: "none" },
	},
	GROWTH: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "self" },
	},
	MEAN_LOOK: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "trap" },
	},
	CONFUSE_RAY: {
		type: Type.GHOST,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "confuse", turns: 2 },
	},
	PROTECT: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "protect" },
	},
	REFLECT: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "reflect", turns: 5, target: "self" },
	},
	LIGHT_SCREEN: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "side-effect", effect: "light-screen", turns: 5, target: "self" },
	},
	TAILWIND: {
		type: Type.FLYING,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "side-effect", effect: "tailwind", turns: 4, target: "self" },
	},
	TRICK_ROOM: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "trick-room", turns: 5 },
	},
	LEECH_SEED: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 90,
		pp: 10,
		effect: { kind: "leech-seed" },
	},
	SOLAR_BEAM: {
		type: Type.GRASS,
		class: Class.Special,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "charge", invulnerable: false },
	},
	SLEEP_POWDER: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 75,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Sleep, chance: 1 },
	},
	PETAL_DANCE: {
		type: Type.GRASS,
		class: Class.Special,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STRING_SHOT: {
		type: Type.BUG,
		class: Class.Status,
		power: 0,
		accuracy: 95,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "target" },
	},
	DRAGON_RAGE: {
		type: Type.DRAGON,
		class: Class.Special,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "fixed-damage", value: 40 },
	},
	FIRE_SPIN: {
		type: Type.FIRE,
		class: Class.Special,
		power: 15,
		accuracy: 70,
		pp: 15,
		effect: { kind: "partial-trap", turns: 4 },
	},
	THUNDER_SHOCK: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.1 },
	},
	SLAM: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 80,
		accuracy: 75,
		pp: 20,
		effect: { kind: "none" },
	},
	MEGA_KICK: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 120,
		accuracy: 75,
		pp: 5,
		effect: { kind: "none" },
	},
	JUMP_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 100,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	ROLLING_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 60,
		accuracy: 85,
		pp: 15,
		effect: { kind: "flinch", chance: 0.3 },
	},
	SAND_ATTACK: {
		type: Type.GROUND,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	HEADBUTT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 70,
		accuracy: 100,
		pp: 15,
		effect: { kind: "flinch", chance: 0.3 },
	},
	HORN_ATTACK: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 65,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	FURY_ATTACK: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 15,
		accuracy: 85,
		pp: 20,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	HORN_DRILL: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "ohko" },
	},
	POISON_POWDER: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 75,
		pp: 35,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 1 },
	},
	CUT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 50,
		accuracy: 95,
		pp: 30,
		effect: { kind: "none" },
	},
	FLY: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 90,
		accuracy: 95,
		pp: 15,
		effect: { kind: "charge", invulnerable: true },
	},
	SURF: {
		type: Type.WATER,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	STRENGTH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	FLASH: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	EMBER: {
		type: Type.FIRE,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 25,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
	SMOKE_SCREEN: {
		type: Type.FIRE,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	FIRE_FANG: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 65,
		accuracy: 95,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
				{ kind: "flinch", chance: 0.1 },
			],
		},
	},
	FLAMETHROWER: {
		type: Type.FIRE,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
} satisfies Record<string, Move>;
