/**
 * Canonical move content for the game's content layer.
 *
 * This module defines the move catalog consumed by the battle and rules systems,
 * pairing each move identifier with its authored data such as typing, damage
 * class, power, accuracy, PP, and authored effect metadata.
 *
 * As a content-layer file, it acts as the source of truth for move behavior data
 * without embedding engine logic here. The engine reads these records to resolve
 * move execution consistently while keeping mechanics and authored content
 * separated.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */
import type { Move } from "~/game/data/move";

import { DamageClass, StatusEffectType } from "~/game/data/move";
import { Stat } from "~/game/data/stat";
import { Type } from "~/game/data/type";

export const MOVES = {
	POUND: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	KARATE_CHOP: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 25,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	DOUBLE_SLAP: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 15,
		accuracy: 85,
		pp: 10,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	COMET_PUNCH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 18,
		accuracy: 85,
		pp: 15,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	MEGA_PUNCH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 85,
		pp: 20,
		effect: { kind: "none" },
	},
	PAY_DAY: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FIRE_PUNCH: {
		type: Type.FIRE,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
	ICE_PUNCH: {
		type: Type.ICE,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Freeze, chance: 0.1 },
	},
	THUNDER_PUNCH: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.1 },
	},
	SCRATCH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	STOMP: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "flinch", chance: 0.3 },
	},
	DOUBLE_KICK: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 30,
		accuracy: 100,
		pp: 30,
		effect: { kind: "multi-hit", hits: 2 },
	},
	TACKLE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	QUICK_ATTACK: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "priority", value: 1 },
	},
	BODY_SLAM: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 85,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.3 },
	},
	WRAP: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 15,
		accuracy: 90,
		pp: 20,
		effect: { kind: "partial-trap", turns: 4 },
	},
	TAKE_DOWN: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 90,
		accuracy: 85,
		pp: 20,
		effect: { kind: "recoil", ratio: 0.25 },
	},
	HYPER_BEAM: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 150,
		accuracy: 90,
		pp: 5,
		effect: { kind: "recharge" },
	},
	THRASH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "rampage", turns: 2 },
	},
	DOUBLE_EDGE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "recoil", ratio: 1 / 3 },
	},
	TAIL_WHIP: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "target" },
	},
	POISON_STING: {
		type: Type.POISON,
		damageClass: DamageClass.Physical,
		power: 15,
		accuracy: 100,
		pp: 35,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 0.3 },
	},
	TWINEEDLE: {
		type: Type.BUG,
		damageClass: DamageClass.Physical,
		power: 25,
		accuracy: 100,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "multi-hit", hits: 2 },
				{ kind: "apply-status", status: StatusEffectType.Poison, chance: 0.2 },
			],
		},
	},
	PIN_MISSILE: {
		type: Type.BUG,
		damageClass: DamageClass.Physical,
		power: 25,
		accuracy: 95,
		pp: 20,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	LEER: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "target" },
	},
	BITE: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 25,
		effect: { kind: "flinch", chance: 0.3 },
	},
	GROWL: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: -1, target: "target" },
	},
	VINE_WHIP: {
		type: Type.GRASS,
		damageClass: DamageClass.Physical,
		power: 45,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	RAZOR_LEAF: {
		type: Type.GRASS,
		damageClass: DamageClass.Physical,
		power: 55,
		accuracy: 95,
		pp: 25,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	GROWTH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "self" },
	},
	MEAN_LOOK: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "trap" },
	},
	CONFUSE_RAY: {
		type: Type.GHOST,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "confuse", turns: 2 },
	},
	PROTECT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "protect" },
	},
	REFLECT: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "reflect", turns: 5, target: "self" },
	},
	LIGHT_SCREEN: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "side-effect", effect: "light-screen", turns: 5, target: "self" },
	},
	TAILWIND: {
		type: Type.FLYING,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "side-effect", effect: "tailwind", turns: 4, target: "self" },
	},
	SAFEGUARD: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 25,
		effect: { kind: "side-effect", effect: "safeguard", turns: 5, target: "self" },
	},
	MIST: {
		type: Type.ICE,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "side-effect", effect: "mist", turns: 5, target: "self" },
	},
	SPIKES: {
		type: Type.GROUND,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "spikes", layers: 1, target: "target" },
	},
	TOXIC_SPIKES: {
		type: Type.POISON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "toxic-spikes", layers: 1, target: "target" },
	},
	STEALTH_ROCK: {
		type: Type.ROCK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "stealth-rock", target: "target" },
	},
	STICKY_WEB: {
		type: Type.BUG,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "sticky-web", target: "target" },
	},
	TRICK_ROOM: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "trick-room", turns: 5 },
	},
	SUNNY_DAY: {
		type: Type.FIRE,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "sun", turns: 5 },
	},
	RAIN_DANCE: {
		type: Type.WATER,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "rain", turns: 5 },
	},
	SANDSTORM: {
		type: Type.ROCK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "sand", turns: 5 },
	},
	HAIL: {
		type: Type.ICE,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "hail", turns: 5 },
	},
	SNOWSCAPE: {
		type: Type.ICE,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "snow", turns: 5 },
	},
	ELECTRIC_TERRAIN: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "electric-terrain", turns: 5 },
	},
	GRASSY_TERRAIN: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "grassy-terrain", turns: 5 },
	},
	MISTY_TERRAIN: {
		type: Type.FAIRY,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "misty-terrain", turns: 5 },
	},
	PSYCHIC_TERRAIN: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "psychic-terrain", turns: 5 },
	},
	GRAVITY: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "gravity", turns: 5 },
	},
	TAUNT: {
		type: Type.DARK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "taunt", turns: 3 },
	},
	ENCORE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "encore", turns: 3 },
	},
	IDENTIFY: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "identify" },
	},
	DISABLE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "disable", turns: 4, slot: 0 },
	},
	ATTRACT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "attract" },
	},
	WONDER_ROOM: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "wonder-room", turns: 5 },
	},
	MAGIC_ROOM: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "magic-room", turns: 5 },
	},
	LEECH_SEED: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 90,
		pp: 10,
		effect: { kind: "leech-seed" },
	},
	SOLAR_BEAM: {
		type: Type.GRASS,
		damageClass: DamageClass.Special,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "charge", invulnerable: false },
	},
	SLEEP_POWDER: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 75,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Sleep, chance: 1 },
	},
	PETAL_DANCE: {
		type: Type.GRASS,
		damageClass: DamageClass.Special,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "rampage", turns: 2 },
	},
	STRING_SHOT: {
		type: Type.BUG,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 95,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "target" },
	},
	DRAGON_RAGE: {
		type: Type.DRAGON,
		damageClass: DamageClass.Special,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "fixed-damage", value: 40 },
	},
	FIRE_SPIN: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 15,
		accuracy: 70,
		pp: 15,
		effect: { kind: "partial-trap", turns: 4 },
	},
	THUNDER_SHOCK: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.1 },
	},
	SLAM: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 75,
		pp: 20,
		effect: { kind: "none" },
	},
	MEGA_KICK: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 75,
		pp: 5,
		effect: { kind: "none" },
	},
	JUMP_KICK: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 95,
		pp: 10,
		effect: { kind: "crash-on-miss", ratio: 1 / 2 },
	},
	ROLLING_KICK: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 85,
		pp: 15,
		effect: { kind: "flinch", chance: 0.3 },
	},
	SAND_ATTACK: {
		type: Type.GROUND,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	HEADBUTT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 70,
		accuracy: 100,
		pp: 15,
		effect: { kind: "flinch", chance: 0.3 },
	},
	HORN_ATTACK: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 65,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	FURY_ATTACK: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 15,
		accuracy: 85,
		pp: 20,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	HORN_DRILL: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "ohko" },
	},
	POISON_POWDER: {
		type: Type.POISON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 75,
		pp: 35,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 1 },
	},
	CUT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 95,
		pp: 30,
		effect: { kind: "none" },
	},
	FLY: {
		type: Type.FLYING,
		damageClass: DamageClass.Physical,
		power: 90,
		accuracy: 95,
		pp: 15,
		effect: { kind: "charge", invulnerable: true },
	},
	SURF: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	STRENGTH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	FLASH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	EMBER: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 25,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
	SMOKE_SCREEN: {
		type: Type.FIRE,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	FIRE_FANG: {
		type: Type.FIRE,
		damageClass: DamageClass.Physical,
		power: 65,
		accuracy: 95,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
				{ kind: "flinch", chance: 0.1 },
			],
		},
	},
	FLAMETHROWER: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
	ABSORB: {
		type: Type.GRASS,
		damageClass: DamageClass.Special,
		power: 20,
		accuracy: 100,
		pp: 25,
		effect: { kind: "drain", ratio: 0.5 },
	},
	ACID: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	ACID_ARMOR: {
		type: Type.POISON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: 2, target: "self" },
	},
	ACID_SPRAY: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: -2, target: "target" }],
		},
	},
	ACUPRESSURE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	AERIAL_ACE: {
		type: Type.FLYING,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	AFTER_YOU: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	AGILITY: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: 2, target: "self" },
	},
	AIR_CUTTER: {
		type: Type.FLYING,
		damageClass: DamageClass.Special,
		power: 60,
		accuracy: 95,
		pp: 25,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	AIR_SLASH: {
		type: Type.FLYING,
		damageClass: DamageClass.Special,
		power: 75,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	ALLY_SWITCH: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	AMNESIA: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.SpecialDefense, stages: 2, target: "self" },
	},
	ANCIENT_POWER: {
		type: Type.ROCK,
		damageClass: DamageClass.Special,
		power: 60,
		accuracy: 100,
		pp: 5,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.Defense, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.Speed, stages: 1, target: "self" },
			],
		},
	},
	AQUA_JET: {
		type: Type.WATER,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: { kind: "priority", value: 1 },
	},
	AQUA_RING: {
		type: Type.WATER,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "aqua-ring" },
	},
	AQUA_TAIL: {
		type: Type.WATER,
		damageClass: DamageClass.Physical,
		power: 90,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	ASSURANCE: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 10,
		effect: { kind: "double-power-if-target-damaged-this-turn" },
	},
	ASTONISH: {
		type: Type.GHOST,
		damageClass: DamageClass.Physical,
		power: 30,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	AURA_SPHERE: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	AURORA_BEAM: {
		type: Type.ICE,
		damageClass: DamageClass.Special,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [{ kind: "modify-stat", stat: Stat.Attack, stages: -1, target: "target" }],
		},
	},
	AXE_KICK: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BABY_DOLL_EYES: {
		type: Type.FAIRY,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "priority", value: 1 },
				{ kind: "modify-stat", stat: Stat.Attack, stages: -1, target: "target" },
			],
		},
	},
	BATON_PASS: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "switch-self", preserveStatStages: true },
	},
	BEAT_UP: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	BELCH: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 120,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BELLY_DRUM: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "belly-drum" },
	},
	BIND: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 15,
		accuracy: 85,
		pp: 20,
		effect: { kind: "none" },
	},
	BLAZE_KICK: {
		type: Type.FIRE,
		damageClass: DamageClass.Physical,
		power: 85,
		accuracy: 90,
		pp: 10,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	BLIZZARD: {
		type: Type.ICE,
		damageClass: DamageClass.Special,
		power: 110,
		accuracy: 70,
		pp: 5,
		effect: { kind: "none" },
	},
	BLOCK: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "trap" },
	},
	BONE_RUSH: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 25,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BONEMERANG: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BRAVE_BIRD: {
		type: Type.FLYING,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	BRICK_BREAK: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: {
			kind: "clear-side-effects",
			target: "target",
			effects: ["reflect", "light-screen"],
		},
	},
	BRINE: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 65,
		accuracy: 100,
		pp: 10,
		effect: { kind: "double-power-on-damaged-target" },
	},
	BUBBLE_BEAM: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "target" },
	},
	BUG_BITE: {
		type: Type.BUG,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	BUG_BUZZ: {
		type: Type.BUG,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	BULK_UP: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.Defense, stages: 1, target: "self" },
			],
		},
	},
	BULLDOZE: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [{ kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "target" }],
		},
	},
	BULLET_PUNCH: {
		type: Type.STEEL,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "priority", value: 1 },
	},
	BULLET_SEED: {
		type: Type.GRASS,
		damageClass: DamageClass.Physical,
		power: 25,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	CALM_MIND: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: 1, target: "self" },
			],
		},
	},
	CHARGE: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: 1, target: "self" },
				{ kind: "charged-electric" },
			],
		},
	},
	CHARGE_BEAM: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 50,
		accuracy: 90,
		pp: 10,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "self" },
	},
	CHARM: {
		type: Type.FAIRY,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: -2, target: "target" },
	},
	CIRCLE_THROW: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 90,
		pp: 10,
		effect: { kind: "force-switch-target" },
	},
	CLEAR_SMOG: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 50,
		accuracy: 0,
		pp: 15,
		effect: { kind: "reset-stat-stages", target: "target" },
	},
	CLOSE_COMBAT: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 5,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: -1, target: "self" },
			],
		},
	},
	COIL: {
		type: Type.POISON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.Defense, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: "accuracy", stages: 1, target: "self" },
			],
		},
	},
	CONFUSION: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 50,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	CONVERSION: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	CONVERSION_2: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	COPYCAT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	COSMIC_POWER: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Defense, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: 1, target: "self" },
			],
		},
	},
	COUNTER: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "counter-last-physical-hit" },
	},
	COVET: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	CRABHAMMER: {
		type: Type.WATER,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 90,
		pp: 10,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	CROSS_CHOP: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 80,
		pp: 5,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	CROSS_POISON: {
		type: Type.POISON,
		damageClass: DamageClass.Physical,
		power: 70,
		accuracy: 100,
		pp: 20,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	CRUNCH: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	CRUSH_CLAW: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	CURSE: {
		type: Type.GHOST,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "curse" },
	},
	DARK_PULSE: {
		type: Type.DARK,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	DAZZLING_GLEAM: {
		type: Type.FAIRY,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DEFENSE_CURL: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: 1, target: "self" },
	},
	DEFOG: {
		type: Type.FLYING,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: {
			kind: "clear-side-effects",
			target: "both",
			effects: ["spikes", "toxic-spikes", "stealth-rock", "sticky-web"],
		},
	},
	DESTINY_BOND: {
		type: Type.GHOST,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "destiny-bond" },
	},
	DETECT: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "protect" },
	},
	DIG: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DISARMING_VOICE: {
		type: Type.FAIRY,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	DISCHARGE: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.3 },
	},
	DIVE: {
		type: Type.WATER,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DOUBLE_HIT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 35,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	DOUBLE_TEAM: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "modify-stat", stat: "evasion", stages: 1, target: "self" },
	},
	DRAGON_BREATH: {
		type: Type.DRAGON,
		damageClass: DamageClass.Special,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.3 },
	},
	DRAGON_CLAW: {
		type: Type.DRAGON,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	DRAGON_DANCE: {
		type: Type.DRAGON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.Speed, stages: 1, target: "self" },
			],
		},
	},
	DRAGON_PULSE: {
		type: Type.DRAGON,
		damageClass: DamageClass.Special,
		power: 85,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DRAGON_RUSH: {
		type: Type.DRAGON,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 75,
		pp: 10,
		effect: { kind: "none" },
	},
	DRAGON_TAIL: {
		type: Type.DRAGON,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 90,
		pp: 10,
		effect: { kind: "force-switch-target" },
	},
	DRAIN_PUNCH: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 100,
		pp: 10,
		effect: { kind: "drain", ratio: 0.5 },
	},
	DREAM_EATER: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 100,
		accuracy: 100,
		pp: 15,
		effect: { kind: "drain", ratio: 0.5, requiresSleepingTarget: true },
	},
	DRILL_PECK: {
		type: Type.FLYING,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	DRILL_RUN: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 95,
		pp: 10,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	DYNAMIC_PUNCH: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 50,
		pp: 5,
		effect: { kind: "none" },
	},
	EARTH_POWER: {
		type: Type.GROUND,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	EARTHQUAKE: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	ECHOED_VOICE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	EERIE_IMPULSE: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: -2, target: "target" },
	},
	ELECTRO_BALL: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "power-from-target-speed" },
	},
	ELECTROWEB: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 55,
		accuracy: 95,
		pp: 15,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "target" },
	},
	ENDEAVOR: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "fixed-damage-target-hp-gap" },
	},
	ENDURE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "endure" },
	},
	ENERGY_BALL: {
		type: Type.GRASS,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	ENTRAINMENT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	EXPLOSION: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 250,
		accuracy: 100,
		pp: 5,
		effect: { kind: "self-destruct" },
	},
	EXTRASENSORY: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	EXTREME_SPEED: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 5,
		effect: { kind: "priority", value: 2 },
	},
	FAKE_OUT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 10,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "priority", value: 3 },
				{ kind: "first-turn-only" },
				{ kind: "flinch", chance: 1 },
			],
		},
	},
	FAKE_TEARS: {
		type: Type.DARK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.SpecialDefense, stages: -2, target: "target" },
	},
	FALSE_SWIPE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 40,
		effect: { kind: "cannot-ko" },
	},
	FEATHER_DANCE: {
		type: Type.FLYING,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: -2, target: "target" },
	},
	FEINT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 30,
		accuracy: 100,
		pp: 10,
		effect: {
			kind: "compound",
			effects: [{ kind: "priority", value: 2 }, { kind: "break-protect" }],
		},
	},
	FELL_STINGER: {
		type: Type.BUG,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 25,
		effect: { kind: "boost-on-ko", stat: Stat.Attack, stages: 3 },
	},
	FINAL_GAMBIT: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Special,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: {
			kind: "compound",
			effects: [{ kind: "fixed-damage-user-hp" }, { kind: "self-destruct" }],
		},
	},
	FIRE_BLAST: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 110,
		accuracy: 85,
		pp: 5,
		effect: { kind: "none" },
	},
	FISSURE: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "ohko" },
	},
	FLAIL: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "power-from-user-hp" },
	},
	FLAME_CHARGE: {
		type: Type.FIRE,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FLAME_WHEEL: {
		type: Type.FIRE,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	FLARE_BLITZ: {
		type: Type.FIRE,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	FLASH_CANNON: {
		type: Type.STEEL,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	FLATTER: {
		type: Type.DARK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "target" },
				{ kind: "confuse", turns: 2 },
			],
		},
	},
	FLING: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	FOCUS_ENERGY: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "focus-energy" },
	},
	FOCUS_PUNCH: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 150,
		accuracy: 100,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [{ kind: "priority", value: -3 }, { kind: "fail-if-user-damaged-this-turn" }],
		},
	},
	FOLLOW_ME: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "compound", effects: [{ kind: "priority", value: 2 }, { kind: "follow-me" }] },
	},
	FREEZE_DRY: {
		type: Type.ICE,
		damageClass: DamageClass.Special,
		power: 70,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FURY_CUTTER: {
		type: Type.BUG,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 95,
		pp: 20,
		effect: { kind: "none" },
	},
	FURY_SWIPES: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 18,
		accuracy: 80,
		pp: 15,
		effect: { kind: "none" },
	},
	FUTURE_SIGHT: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "delayed-attack", turns: 2 },
	},
	GASTRO_ACID: {
		type: Type.POISON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	GIGA_DRAIN: {
		type: Type.GRASS,
		damageClass: DamageClass.Special,
		power: 75,
		accuracy: 100,
		pp: 10,
		effect: { kind: "drain", ratio: 0.5 },
	},
	GIGA_IMPACT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 150,
		accuracy: 90,
		pp: 5,
		effect: { kind: "none" },
	},
	GLARE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 1 },
	},
	GUARD_SPLIT: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	GUARD_SWAP: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	GUILLOTINE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "ohko" },
	},
	GUNK_SHOT: {
		type: Type.POISON,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 80,
		pp: 5,
		effect: { kind: "none" },
	},
	GUST: {
		type: Type.FLYING,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	GYRO_BALL: {
		type: Type.STEEL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "power-from-user-speed" },
	},
	HAMMER_ARM: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 90,
		pp: 10,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "self" },
	},
	HARDEN: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: 1, target: "self" },
	},
	HAZE: {
		type: Type.ICE,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "reset-stat-stages", target: "all-active" },
	},
	HEAD_SMASH: {
		type: Type.ROCK,
		damageClass: DamageClass.Physical,
		power: 150,
		accuracy: 80,
		pp: 5,
		effect: { kind: "none" },
	},
	HEAL_BELL: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	HEAL_PULSE: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	HEALING_WISH: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "compound", effects: [{ kind: "healing-wish" }, { kind: "self-destruct" }] },
	},
	HEAT_WAVE: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 95,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	HEAVY_SLAM: {
		type: Type.STEEL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "power-from-weight" },
	},
	HELPING_HAND: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	HEX: {
		type: Type.GHOST,
		damageClass: DamageClass.Special,
		power: 65,
		accuracy: 100,
		pp: 10,
		effect: { kind: "double-power-on-status-target" },
	},
	HIGH_HORSEPOWER: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 95,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	HIGH_JUMP_KICK: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 130,
		accuracy: 90,
		pp: 10,
		effect: { kind: "crash-on-miss", ratio: 1 / 2 },
	},
	HONE_CLAWS: {
		type: Type.DARK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: "accuracy", stages: 1, target: "self" },
			],
		},
	},
	HOWL: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: 1, target: "self" },
	},
	HURRICANE: {
		type: Type.FLYING,
		damageClass: DamageClass.Special,
		power: 110,
		accuracy: 70,
		pp: 10,
		effect: { kind: "none" },
	},
	HYDRO_PUMP: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 110,
		accuracy: 80,
		pp: 5,
		effect: { kind: "none" },
	},
	HYPER_VOICE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	HYPNOSIS: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 60,
		pp: 20,
		effect: { kind: "apply-status", status: StatusEffectType.Sleep, chance: 1 },
	},
	ICE_BEAM: {
		type: Type.ICE,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "apply-status", status: StatusEffectType.Freeze, chance: 0.1 },
	},
	ICE_FANG: {
		type: Type.ICE,
		damageClass: DamageClass.Physical,
		power: 65,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	ICE_SHARD: {
		type: Type.ICE,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "priority", value: 1 },
	},
	ICICLE_CRASH: {
		type: Type.ICE,
		damageClass: DamageClass.Physical,
		power: 85,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	ICICLE_SPEAR: {
		type: Type.ICE,
		damageClass: DamageClass.Physical,
		power: 25,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	ICY_WIND: {
		type: Type.ICE,
		damageClass: DamageClass.Special,
		power: 55,
		accuracy: 95,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [{ kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "target" }],
		},
	},
	IMPRISON: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	INCINERATE: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 60,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	INFERNO: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 100,
		accuracy: 50,
		pp: 5,
		effect: { kind: "none" },
	},
	INGRAIN: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	IRON_DEFENSE: {
		type: Type.STEEL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: 2, target: "self" },
	},
	IRON_HEAD: {
		type: Type.STEEL,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	IRON_TAIL: {
		type: Type.STEEL,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 75,
		pp: 15,
		effect: { kind: "none" },
	},
	KNOCK_OFF: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	LASER_FOCUS: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	LAST_RESORT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 140,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	LAVA_PLUME: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.3 },
	},
	LEAF_BLADE: {
		type: Type.GRASS,
		damageClass: DamageClass.Physical,
		power: 90,
		accuracy: 100,
		pp: 15,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	LEAF_STORM: {
		type: Type.GRASS,
		damageClass: DamageClass.Special,
		power: 130,
		accuracy: 90,
		pp: 5,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: -2, target: "self" },
	},
	LEECH_LIFE: {
		type: Type.BUG,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	LICK: {
		type: Type.GHOST,
		damageClass: DamageClass.Physical,
		power: 30,
		accuracy: 100,
		pp: 30,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.3 },
	},
	LIFE_DEW: {
		type: Type.WATER,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	LIQUIDATION: {
		type: Type.WATER,
		damageClass: DamageClass.Physical,
		power: 85,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	LOCK_ON: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	LOVELY_KISS: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 75,
		pp: 10,
		effect: { kind: "apply-status", status: StatusEffectType.Sleep, chance: 1 },
	},
	LOW_KICK: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "power-from-weight" },
	},
	LOW_SWEEP: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	MACH_PUNCH: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "priority", value: 1 },
	},
	MAGNET_RISE: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	MAGNETIC_FLUX: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	MEGA_DRAIN: {
		type: Type.GRASS,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 15,
		effect: { kind: "drain", ratio: 0.5 },
	},
	MEGAHORN: {
		type: Type.BUG,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 85,
		pp: 10,
		effect: { kind: "none" },
	},
	MEMENTO: {
		type: Type.DARK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	METAL_BURST: {
		type: Type.STEEL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	METAL_CLAW: {
		type: Type.STEEL,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 95,
		pp: 35,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: 1, target: "self" },
	},
	METAL_SOUND: {
		type: Type.STEEL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 85,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.SpecialDefense, stages: -2, target: "target" },
	},
	METEOR_MASH: {
		type: Type.STEEL,
		damageClass: DamageClass.Physical,
		power: 90,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	METRONOME: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	MIMIC: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	MINIMIZE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "modify-stat", stat: "evasion", stages: 2, target: "self" },
	},
	MIRROR_COAT: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	MOONBLAST: {
		type: Type.FAIRY,
		damageClass: DamageClass.Special,
		power: 95,
		accuracy: 100,
		pp: 15,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: -1, target: "target" },
	},
	MOONLIGHT: {
		type: Type.FAIRY,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	MORNING_SUN: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	MUD_SHOT: {
		type: Type.GROUND,
		damageClass: DamageClass.Special,
		power: 55,
		accuracy: 95,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [{ kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "target" }],
		},
	},
	MUD_SLAP: {
		type: Type.GROUND,
		damageClass: DamageClass.Special,
		power: 20,
		accuracy: 100,
		pp: 10,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	MUDDY_WATER: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 85,
		pp: 10,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	NASTY_PLOT: {
		type: Type.DARK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: 2, target: "self" },
	},
	NIGHT_SHADE: {
		type: Type.GHOST,
		damageClass: DamageClass.Special,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	NIGHT_SLASH: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 70,
		accuracy: 100,
		pp: 15,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	NUZZLE: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Physical,
		power: 20,
		accuracy: 100,
		pp: 20,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 1 },
	},
	OUTRAGE: {
		type: Type.DRAGON,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "rampage", turns: 2 },
	},
	OVERHEAT: {
		type: Type.FIRE,
		damageClass: DamageClass.Special,
		power: 130,
		accuracy: 90,
		pp: 5,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: -2, target: "self" },
	},
	PAIN_SPLIT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	PAYBACK: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	PECK: {
		type: Type.FLYING,
		damageClass: DamageClass.Physical,
		power: 35,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	PERISH_SONG: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	PETAL_BLIZZARD: {
		type: Type.GRASS,
		damageClass: DamageClass.Physical,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	PLAY_NICE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: -1, target: "target" },
	},
	PLAY_ROUGH: {
		type: Type.FAIRY,
		damageClass: DamageClass.Physical,
		power: 90,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	PLUCK: {
		type: Type.FLYING,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	POISON_FANG: {
		type: Type.POISON,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	POISON_GAS: {
		type: Type.POISON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 90,
		pp: 40,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 1 },
	},
	POISON_JAB: {
		type: Type.POISON,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 20,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 0.3 },
	},
	POISON_TAIL: {
		type: Type.POISON,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 25,
		criticalHitStages: 1,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 0.1 },
	},
	POWDER_SNOW: {
		type: Type.ICE,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 25,
		effect: { kind: "apply-status", status: StatusEffectType.Freeze, chance: 0.1 },
	},
	POWER_GEM: {
		type: Type.ROCK,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	POWER_SPLIT: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	POWER_SWAP: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	POWER_WHIP: {
		type: Type.GRASS,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 85,
		pp: 10,
		effect: { kind: "none" },
	},
	PRESENT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 90,
		pp: 15,
		effect: { kind: "none" },
	},
	PSYBEAM: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	PSYCH_UP: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	PSYCHIC: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	PSYCHO_CUT: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Physical,
		power: 70,
		accuracy: 100,
		pp: 20,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	PSYSHOCK: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	PSYSTRIKE: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 100,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	QUICK_GUARD: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	QUIVER_DANCE: {
		type: Type.BUG,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.Speed, stages: 1, target: "self" },
			],
		},
	},
	RAGE_FIST: {
		type: Type.GHOST,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	RAGE_POWDER: {
		type: Type.BUG,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	RAGING_BULL: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	RAGING_FURY: {
		type: Type.FIRE,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	RAPID_SPIN: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 40,
		effect: { kind: "none" },
	},
	RAZOR_SHELL: {
		type: Type.WATER,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	RECOVER: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	RECYCLE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	REFLECT_TYPE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	REST: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	RETALIATE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 70,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	REVENGE: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	REVERSAL: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "power-from-user-hp" },
	},
	ROAR: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [{ kind: "priority", value: -6 }, { kind: "force-switch-target" }],
		},
	},
	ROCK_BLAST: {
		type: Type.ROCK,
		damageClass: DamageClass.Physical,
		power: 25,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	ROCK_POLISH: {
		type: Type.ROCK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: 2, target: "self" },
	},
	ROCK_SLIDE: {
		type: Type.ROCK,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	ROCK_SMASH: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	ROCK_THROW: {
		type: Type.ROCK,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 90,
		pp: 15,
		effect: { kind: "none" },
	},
	ROLE_PLAY: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	ROLLOUT: {
		type: Type.ROCK,
		damageClass: DamageClass.Physical,
		power: 30,
		accuracy: 90,
		pp: 20,
		effect: { kind: "none" },
	},
	ROOST: {
		type: Type.FLYING,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	ROUND: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 60,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SAND_TOMB: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 35,
		accuracy: 85,
		pp: 15,
		effect: { kind: "none" },
	},
	SCARY_FACE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: -2, target: "target" },
	},
	SCREECH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 85,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: -2, target: "target" },
	},
	SEED_BOMB: {
		type: Type.GRASS,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SEISMIC_TOSS: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SELF_DESTRUCT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 200,
		accuracy: 100,
		pp: 5,
		effect: { kind: "self-destruct" },
	},
	SHADOW_BALL: {
		type: Type.GHOST,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SHADOW_PUNCH: {
		type: Type.GHOST,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	SHADOW_SNEAK: {
		type: Type.GHOST,
		damageClass: DamageClass.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	SHEER_COLD: {
		type: Type.ICE,
		damageClass: DamageClass.Special,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "ohko" },
	},
	SHELL_SMASH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: -1, target: "self" },
				{ kind: "modify-stat", stat: Stat.Attack, stages: 2, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialAttack, stages: 2, target: "self" },
				{ kind: "modify-stat", stat: Stat.Speed, stages: 2, target: "self" },
			],
		},
	},
	SHOCK_WAVE: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 60,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	SIMPLE_BEAM: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SING: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 55,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Sleep, chance: 1 },
	},
	SKULL_BASH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 130,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SKY_ATTACK: {
		type: Type.FLYING,
		damageClass: DamageClass.Physical,
		power: 140,
		accuracy: 90,
		pp: 5,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	SLACK_OFF: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	SLASH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 70,
		accuracy: 100,
		pp: 20,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	SLEEP_TALK: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	SLUDGE: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SLUDGE_BOMB: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SLUDGE_WAVE: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 95,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SMACK_DOWN: {
		type: Type.ROCK,
		damageClass: DamageClass.Physical,
		power: 50,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SMOG: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 30,
		accuracy: 70,
		pp: 20,
		effect: { kind: "none" },
	},
	SNORE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 50,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SOAK: {
		type: Type.WATER,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SOFT_BOILED: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	SPARK: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SPARKLING_ARIA: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SPIT_UP: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SPITE: {
		type: Type.GHOST,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SPLASH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "none" },
	},
	SPORE: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Sleep, chance: 1 },
	},
	STOCKPILE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Defense, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialDefense, stages: 1, target: "self" },
			],
		},
	},
	STOMPING_TANTRUM: {
		type: Type.GROUND,
		damageClass: DamageClass.Physical,
		power: 75,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STONE_EDGE: {
		type: Type.ROCK,
		damageClass: DamageClass.Physical,
		power: 100,
		accuracy: 80,
		pp: 5,
		criticalHitStages: 1,
		effect: { kind: "none" },
	},
	STORED_POWER: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Special,
		power: 20,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STORM_THROW: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STRENGTH_SAP: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STUN_SPORE: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 75,
		pp: 30,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 1 },
	},
	SUBMISSION: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 80,
		pp: 20,
		effect: { kind: "none" },
	},
	SUCKER_PUNCH: {
		type: Type.DARK,
		damageClass: DamageClass.Physical,
		power: 70,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	SUPER_FANG: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 0,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	SUPERPOWER: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 5,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: -1, target: "self" },
				{ kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "self" },
			],
		},
	},
	SUPERSONIC: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 55,
		pp: 20,
		effect: { kind: "confuse", turns: 2 },
	},
	SWAGGER: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 85,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: 2, target: "target" },
				{ kind: "confuse", turns: 2 },
			],
		},
	},
	SWALLOW: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	SWEET_KISS: {
		type: Type.FAIRY,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 75,
		pp: 10,
		effect: { kind: "confuse", turns: 2 },
	},
	SWEET_SCENT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: "evasion", stages: -2, target: "target" },
	},
	SWIFT: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 60,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	SWITCHEROO: {
		type: Type.DARK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SWORDS_DANCE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: 2, target: "self" },
	},
	SYNTHESIS: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	TEETER_DANCE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "confuse", turns: 2 },
	},
	TELEPORT: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	THUNDER: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 110,
		accuracy: 70,
		pp: 10,
		effect: { kind: "none" },
	},
	THUNDER_FANG: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Physical,
		power: 65,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	THUNDER_WAVE: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 90,
		pp: 20,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 1 },
	},
	THUNDERBOLT: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	TICKLE: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: -1, target: "target" },
				{ kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "target" },
			],
		},
	},
	TOXIC: {
		type: Type.POISON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 90,
		pp: 10,
		effect: {
			kind: "apply-status",
			status: StatusEffectType.Poison,
			chance: 1,
			poisonVariant: "escalating",
		},
	},
	TRANSFORM: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	TRI_ATTACK: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	TWISTER: {
		type: Type.DRAGON,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	UPROAR: {
		type: Type.NORMAL,
		damageClass: DamageClass.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	VACUUM_WAVE: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	VENOM_DRENCH: {
		type: Type.POISON,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	VENOSHOCK: {
		type: Type.POISON,
		damageClass: DamageClass.Special,
		power: 65,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	VICE_GRIP: {
		type: Type.NORMAL,
		damageClass: DamageClass.Physical,
		power: 55,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	VITAL_THROW: {
		type: Type.FIGHTING,
		damageClass: DamageClass.Physical,
		power: 70,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	WATER_GUN: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 40,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	WATER_PULSE: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	WATER_SPOUT: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 150,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	WATERFALL: {
		type: Type.WATER,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	WAVE_CRASH: {
		type: Type.WATER,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	WHIRLPOOL: {
		type: Type.WATER,
		damageClass: DamageClass.Special,
		power: 35,
		accuracy: 85,
		pp: 15,
		effect: { kind: "none" },
	},
	WHIRLWIND: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [{ kind: "priority", value: -6 }, { kind: "force-switch-target" }],
		},
	},
	WIDE_GUARD: {
		type: Type.ROCK,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	WILL_O_WISP: {
		type: Type.FIRE,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 85,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 1 },
	},
	WING_ATTACK: {
		type: Type.FLYING,
		damageClass: DamageClass.Physical,
		power: 60,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	WISH: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	WITHDRAW: {
		type: Type.WATER,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: 1, target: "self" },
	},
	WOOD_HAMMER: {
		type: Type.GRASS,
		damageClass: DamageClass.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	WORK_UP: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "modify-stat", stat: Stat.Attack, stages: 1, target: "self" },
				{ kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "self" },
			],
		},
	},
	WORRY_SEED: {
		type: Type.GRASS,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	X_SCISSOR: {
		type: Type.BUG,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	YAWN: {
		type: Type.NORMAL,
		damageClass: DamageClass.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	ZAP_CANNON: {
		type: Type.ELECTRIC,
		damageClass: DamageClass.Special,
		power: 120,
		accuracy: 50,
		pp: 5,
		effect: { kind: "none" },
	},
	ZEN_HEADBUTT: {
		type: Type.PSYCHIC,
		damageClass: DamageClass.Physical,
		power: 80,
		accuracy: 90,
		pp: 15,
		effect: { kind: "none" },
	},
} satisfies Record<string, Move>;
