import type { Move } from "../domain/move";

import { Class, StatusEffectType } from "../domain/move";
import { Stat } from "../domain/stat";
import { Type } from "../domain/type";

export const MOVES = {
	POUND: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	KARATE_CHOP: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	DOUBLE_SLAP: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 15,
		accuracy: 85,
		pp: 10,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	COMET_PUNCH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 18,
		accuracy: 85,
		pp: 15,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	MEGA_PUNCH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 80,
		accuracy: 85,
		pp: 20,
		effect: { kind: "none" },
	},
	PAY_DAY: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FIRE_PUNCH: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
	ICE_PUNCH: {
		type: Type.ICE,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Freeze, chance: 0.1 },
	},
	THUNDER_PUNCH: {
		type: Type.ELECTRIC,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.1 },
	},
	SCRATCH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	STOMP: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "flinch", chance: 0.3 },
	},
	DOUBLE_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 30,
		accuracy: 100,
		pp: 30,
		effect: { kind: "multi-hit", hits: 2 },
	},
	TACKLE: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	QUICK_ATTACK: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "priority", value: 1 },
	},
	BODY_SLAM: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 85,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.3 },
	},
	WRAP: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 15,
		accuracy: 90,
		pp: 20,
		effect: { kind: "partial-trap", turns: 4 },
	},
	TAKE_DOWN: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 90,
		accuracy: 85,
		pp: 20,
		effect: { kind: "recoil", ratio: 0.25 },
	},
	HYPER_BEAM: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 150,
		accuracy: 90,
		pp: 5,
		effect: { kind: "recharge" },
	},
	THRASH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DOUBLE_EDGE: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "recoil", ratio: 1 / 3 },
	},
	TAIL_WHIP: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "target" },
	},
	POISON_STING: {
		type: Type.POISON,
		class: Class.Physical,
		power: 15,
		accuracy: 100,
		pp: 35,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 0.3 },
	},
	TWINEEDLE: {
		type: Type.BUG,
		class: Class.Physical,
		power: 25,
		accuracy: 100,
		pp: 20,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "multi-hit", hits: 2 },
				{ kind: "apply-status", status: StatusEffectType.Poison, chance: 0.2 },
			],
		},
	},
	PIN_MISSILE: {
		type: Type.BUG,
		class: Class.Physical,
		power: 25,
		accuracy: 95,
		pp: 20,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	LEER: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "modify-stat", stat: Stat.Defense, stages: -1, target: "target" },
	},
	BITE: {
		type: Type.DARK,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 25,
		effect: { kind: "flinch", chance: 0.3 },
	},
	GROWL: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Attack, stages: -1, target: "target" },
	},
	VINE_WHIP: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 45,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	RAZOR_LEAF: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 55,
		accuracy: 95,
		pp: 25,
		effect: { kind: "none" },
	},
	GROWTH: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "modify-stat", stat: Stat.SpecialAttack, stages: 1, target: "self" },
	},
	MEAN_LOOK: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "trap" },
	},
	CONFUSE_RAY: {
		type: Type.GHOST,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "confuse", turns: 2 },
	},
	PROTECT: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "protect" },
	},
	REFLECT: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "reflect", turns: 5, target: "self" },
	},
	LIGHT_SCREEN: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "side-effect", effect: "light-screen", turns: 5, target: "self" },
	},
	TAILWIND: {
		type: Type.FLYING,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "side-effect", effect: "tailwind", turns: 4, target: "self" },
	},
	SAFEGUARD: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 25,
		effect: { kind: "side-effect", effect: "safeguard", turns: 5, target: "self" },
	},
	MIST: {
		type: Type.ICE,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "side-effect", effect: "mist", turns: 5, target: "self" },
	},
	SPIKES: {
		type: Type.GROUND,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "spikes", layers: 1, target: "target" },
	},
	TOXIC_SPIKES: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "toxic-spikes", layers: 1, target: "target" },
	},
	STEALTH_ROCK: {
		type: Type.ROCK,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "stealth-rock", target: "target" },
	},
	STICKY_WEB: {
		type: Type.BUG,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "side-effect", effect: "sticky-web", target: "target" },
	},
	TRICK_ROOM: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "trick-room", turns: 5 },
	},
	SUNNY_DAY: {
		type: Type.FIRE,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "sun", turns: 5 },
	},
	RAIN_DANCE: {
		type: Type.WATER,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "rain", turns: 5 },
	},
	SANDSTORM: {
		type: Type.ROCK,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "sand", turns: 5 },
	},
	HAIL: {
		type: Type.ICE,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "hail", turns: 5 },
	},
	SNOWSCAPE: {
		type: Type.ICE,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "snow", turns: 5 },
	},
	ELECTRIC_TERRAIN: {
		type: Type.ELECTRIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "electric-terrain", turns: 5 },
	},
	GRASSY_TERRAIN: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "grassy-terrain", turns: 5 },
	},
	MISTY_TERRAIN: {
		type: Type.FAIRY,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "misty-terrain", turns: 5 },
	},
	PSYCHIC_TERRAIN: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "psychic-terrain", turns: 5 },
	},
	GRAVITY: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "field-effect", effect: "gravity", turns: 5 },
	},
	TAUNT: {
		type: Type.DARK,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "taunt", turns: 3 },
	},
	ENCORE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "encore", turns: 3 },
	},
	IDENTIFY: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "identify" },
	},
	DISABLE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "disable", turns: 4, slot: 0 },
	},
	ATTRACT: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "attract" },
	},
	WONDER_ROOM: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "wonder-room", turns: 5 },
	},
	MAGIC_ROOM: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "field-effect", effect: "magic-room", turns: 5 },
	},
	LEECH_SEED: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 90,
		pp: 10,
		effect: { kind: "leech-seed" },
	},
	SOLAR_BEAM: {
		type: Type.GRASS,
		class: Class.Special,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "charge", invulnerable: false },
	},
	SLEEP_POWDER: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 75,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Sleep, chance: 1 },
	},
	PETAL_DANCE: {
		type: Type.GRASS,
		class: Class.Special,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STRING_SHOT: {
		type: Type.BUG,
		class: Class.Status,
		power: 0,
		accuracy: 95,
		pp: 40,
		effect: { kind: "modify-stat", stat: Stat.Speed, stages: -1, target: "target" },
	},
	DRAGON_RAGE: {
		type: Type.DRAGON,
		class: Class.Special,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "fixed-damage", value: 40 },
	},
	FIRE_SPIN: {
		type: Type.FIRE,
		class: Class.Special,
		power: 15,
		accuracy: 70,
		pp: 15,
		effect: { kind: "partial-trap", turns: 4 },
	},
	THUNDER_SHOCK: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "apply-status", status: StatusEffectType.Paralysis, chance: 0.1 },
	},
	SLAM: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 80,
		accuracy: 75,
		pp: 20,
		effect: { kind: "none" },
	},
	MEGA_KICK: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 120,
		accuracy: 75,
		pp: 5,
		effect: { kind: "none" },
	},
	JUMP_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 100,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	ROLLING_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 60,
		accuracy: 85,
		pp: 15,
		effect: { kind: "flinch", chance: 0.3 },
	},
	SAND_ATTACK: {
		type: Type.GROUND,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	HEADBUTT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 70,
		accuracy: 100,
		pp: 15,
		effect: { kind: "flinch", chance: 0.3 },
	},
	HORN_ATTACK: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 65,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	FURY_ATTACK: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 15,
		accuracy: 85,
		pp: 20,
		effect: { kind: "multi-hit", hits: [2, 5] },
	},
	HORN_DRILL: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "ohko" },
	},
	POISON_POWDER: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 75,
		pp: 35,
		effect: { kind: "apply-status", status: StatusEffectType.Poison, chance: 1 },
	},
	CUT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 50,
		accuracy: 95,
		pp: 30,
		effect: { kind: "none" },
	},
	FLY: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 90,
		accuracy: 95,
		pp: 15,
		effect: { kind: "charge", invulnerable: true },
	},
	SURF: {
		type: Type.WATER,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	STRENGTH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	FLASH: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	EMBER: {
		type: Type.FIRE,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 25,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
	SMOKE_SCREEN: {
		type: Type.FIRE,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "modify-stat", stat: "accuracy", stages: -1, target: "target" },
	},
	FIRE_FANG: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 65,
		accuracy: 95,
		pp: 15,
		effect: {
			kind: "compound",
			effects: [
				{ kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
				{ kind: "flinch", chance: 0.1 },
			],
		},
	},
	FLAMETHROWER: {
		type: Type.FIRE,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "apply-status", status: StatusEffectType.Burn, chance: 0.1 },
	},
	ABSORB: {
		type: Type.GRASS,
		class: Class.Special,
		power: 20,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	ACID: {
		type: Type.POISON,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	ACID_ARMOR: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	ACID_SPRAY: {
		type: Type.POISON,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	ACUPRESSURE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	AERIAL_ACE: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 60,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	AFTER_YOU: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	AGILITY: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	AIR_CUTTER: {
		type: Type.FLYING,
		class: Class.Special,
		power: 60,
		accuracy: 95,
		pp: 25,
		effect: { kind: "none" },
	},
	AIR_SLASH: {
		type: Type.FLYING,
		class: Class.Special,
		power: 75,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	ALLY_SWITCH: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	AMNESIA: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	ANCIENT_POWER: {
		type: Type.ROCK,
		class: Class.Special,
		power: 60,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	AQUA_JET: {
		type: Type.WATER,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	AQUA_RING: {
		type: Type.WATER,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	AQUA_TAIL: {
		type: Type.WATER,
		class: Class.Physical,
		power: 90,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	ASSURANCE: {
		type: Type.DARK,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	ASTONISH: {
		type: Type.GHOST,
		class: Class.Physical,
		power: 30,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	AURA_SPHERE: {
		type: Type.FIGHTING,
		class: Class.Special,
		power: 80,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	AURORA_BEAM: {
		type: Type.ICE,
		class: Class.Special,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	AXE_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 120,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BABY_DOLL_EYES: {
		type: Type.FAIRY,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	BATON_PASS: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "none" },
	},
	BEAT_UP: {
		type: Type.DARK,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	BELCH: {
		type: Type.POISON,
		class: Class.Special,
		power: 120,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BELLY_DRUM: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	BIND: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 15,
		accuracy: 85,
		pp: 20,
		effect: { kind: "none" },
	},
	BLAZE_KICK: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 85,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BLIZZARD: {
		type: Type.ICE,
		class: Class.Special,
		power: 110,
		accuracy: 70,
		pp: 5,
		effect: { kind: "none" },
	},
	BLOCK: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	BONE_RUSH: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 25,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BONEMERANG: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 50,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	BRAVE_BIRD: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	BRICK_BREAK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	BRINE: {
		type: Type.WATER,
		class: Class.Special,
		power: 65,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	BUBBLE_BEAM: {
		type: Type.WATER,
		class: Class.Special,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	BUG_BITE: {
		type: Type.BUG,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	BUG_BUZZ: {
		type: Type.BUG,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	BULK_UP: {
		type: Type.FIGHTING,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	BULLDOZE: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	BULLET_PUNCH: {
		type: Type.STEEL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	BULLET_SEED: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 25,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	CALM_MIND: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	CHARGE: {
		type: Type.ELECTRIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	CHARGE_BEAM: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 50,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	CHARM: {
		type: Type.FAIRY,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	CIRCLE_THROW: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 60,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	CLEAR_SMOG: {
		type: Type.POISON,
		class: Class.Special,
		power: 50,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	CLOSE_COMBAT: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	COIL: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	CONFUSION: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 50,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	CONVERSION: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	CONVERSION_2: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	COPYCAT: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	COSMIC_POWER: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	COUNTER: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	COVET: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	CRABHAMMER: {
		type: Type.WATER,
		class: Class.Physical,
		power: 100,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	CROSS_CHOP: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 100,
		accuracy: 80,
		pp: 5,
		effect: { kind: "none" },
	},
	CROSS_POISON: {
		type: Type.POISON,
		class: Class.Physical,
		power: 70,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	CRUNCH: {
		type: Type.DARK,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	CRUSH_CLAW: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 75,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	CURSE: {
		type: Type.GHOST,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	DARK_PULSE: {
		type: Type.DARK,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	DAZZLING_GLEAM: {
		type: Type.FAIRY,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DEFENSE_CURL: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "none" },
	},
	DEFOG: {
		type: Type.FLYING,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	DESTINY_BOND: {
		type: Type.GHOST,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	DETECT: {
		type: Type.FIGHTING,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	DIG: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DISARMING_VOICE: {
		type: Type.FAIRY,
		class: Class.Special,
		power: 40,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	DISCHARGE: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	DIVE: {
		type: Type.WATER,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DOUBLE_HIT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 35,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	DOUBLE_TEAM: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	DRAGON_BREATH: {
		type: Type.DRAGON,
		class: Class.Special,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	DRAGON_CLAW: {
		type: Type.DRAGON,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	DRAGON_DANCE: {
		type: Type.DRAGON,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	DRAGON_PULSE: {
		type: Type.DRAGON,
		class: Class.Special,
		power: 85,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DRAGON_RUSH: {
		type: Type.DRAGON,
		class: Class.Physical,
		power: 100,
		accuracy: 75,
		pp: 10,
		effect: { kind: "none" },
	},
	DRAGON_TAIL: {
		type: Type.DRAGON,
		class: Class.Physical,
		power: 60,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	DRAIN_PUNCH: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	DREAM_EATER: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 100,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	DRILL_PECK: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	DRILL_RUN: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 80,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	DYNAMIC_PUNCH: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 100,
		accuracy: 50,
		pp: 5,
		effect: { kind: "none" },
	},
	EARTH_POWER: {
		type: Type.GROUND,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	EARTHQUAKE: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 100,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	ECHOED_VOICE: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	EERIE_IMPULSE: {
		type: Type.ELECTRIC,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	ELECTRO_BALL: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	ELECTROWEB: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 55,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	ENDEAVOR: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	ENDURE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	ENERGY_BALL: {
		type: Type.GRASS,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	ENTRAINMENT: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	EXPLOSION: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 250,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	EXTRASENSORY: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	EXTREME_SPEED: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	FAKE_OUT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	FAKE_TEARS: {
		type: Type.DARK,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FALSE_SWIPE: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 40,
		effect: { kind: "none" },
	},
	FEATHER_DANCE: {
		type: Type.FLYING,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	FEINT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 30,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	FELL_STINGER: {
		type: Type.BUG,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	FINAL_GAMBIT: {
		type: Type.FIGHTING,
		class: Class.Special,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	FIRE_BLAST: {
		type: Type.FIRE,
		class: Class.Special,
		power: 110,
		accuracy: 85,
		pp: 5,
		effect: { kind: "none" },
	},
	FISSURE: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "none" },
	},
	FLAIL: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	FLAME_CHARGE: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FLAME_WHEEL: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	FLARE_BLITZ: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	FLASH_CANNON: {
		type: Type.STEEL,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	FLATTER: {
		type: Type.DARK,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	FLING: {
		type: Type.DARK,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	FOCUS_ENERGY: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	FOCUS_PUNCH: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 150,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FOLLOW_ME: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	FREEZE_DRY: {
		type: Type.ICE,
		class: Class.Special,
		power: 70,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	FURY_CUTTER: {
		type: Type.BUG,
		class: Class.Physical,
		power: 40,
		accuracy: 95,
		pp: 20,
		effect: { kind: "none" },
	},
	FURY_SWIPES: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 18,
		accuracy: 80,
		pp: 15,
		effect: { kind: "none" },
	},
	FUTURE_SIGHT: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	GASTRO_ACID: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	GIGA_DRAIN: {
		type: Type.GRASS,
		class: Class.Special,
		power: 75,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	GIGA_IMPACT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 150,
		accuracy: 90,
		pp: 5,
		effect: { kind: "none" },
	},
	GLARE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	GUARD_SPLIT: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	GUARD_SWAP: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	GUILLOTINE: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "none" },
	},
	GUNK_SHOT: {
		type: Type.POISON,
		class: Class.Physical,
		power: 120,
		accuracy: 80,
		pp: 5,
		effect: { kind: "none" },
	},
	GUST: {
		type: Type.FLYING,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	GYRO_BALL: {
		type: Type.STEEL,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	HAMMER_ARM: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 100,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	HARDEN: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	HAZE: {
		type: Type.ICE,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	HEAD_SMASH: {
		type: Type.ROCK,
		class: Class.Physical,
		power: 150,
		accuracy: 80,
		pp: 5,
		effect: { kind: "none" },
	},
	HEAL_BELL: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	HEAL_PULSE: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	HEALING_WISH: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	HEAT_WAVE: {
		type: Type.FIRE,
		class: Class.Special,
		power: 95,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	HEAVY_SLAM: {
		type: Type.STEEL,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	HELPING_HAND: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	HEX: {
		type: Type.GHOST,
		class: Class.Special,
		power: 65,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	HIGH_HORSEPOWER: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 95,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	HIGH_JUMP_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 130,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	HONE_CLAWS: {
		type: Type.DARK,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	HOWL: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "none" },
	},
	HURRICANE: {
		type: Type.FLYING,
		class: Class.Special,
		power: 110,
		accuracy: 70,
		pp: 10,
		effect: { kind: "none" },
	},
	HYDRO_PUMP: {
		type: Type.WATER,
		class: Class.Special,
		power: 110,
		accuracy: 80,
		pp: 5,
		effect: { kind: "none" },
	},
	HYPER_VOICE: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	HYPNOSIS: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 60,
		pp: 20,
		effect: { kind: "none" },
	},
	ICE_BEAM: {
		type: Type.ICE,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	ICE_FANG: {
		type: Type.ICE,
		class: Class.Physical,
		power: 65,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	ICE_SHARD: {
		type: Type.ICE,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	ICICLE_CRASH: {
		type: Type.ICE,
		class: Class.Physical,
		power: 85,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	ICICLE_SPEAR: {
		type: Type.ICE,
		class: Class.Physical,
		power: 25,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	ICY_WIND: {
		type: Type.ICE,
		class: Class.Special,
		power: 55,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	IMPRISON: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	INCINERATE: {
		type: Type.FIRE,
		class: Class.Special,
		power: 60,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	INFERNO: {
		type: Type.FIRE,
		class: Class.Special,
		power: 100,
		accuracy: 50,
		pp: 5,
		effect: { kind: "none" },
	},
	INGRAIN: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	IRON_DEFENSE: {
		type: Type.STEEL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	IRON_HEAD: {
		type: Type.STEEL,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	IRON_TAIL: {
		type: Type.STEEL,
		class: Class.Physical,
		power: 100,
		accuracy: 75,
		pp: 15,
		effect: { kind: "none" },
	},
	KNOCK_OFF: {
		type: Type.DARK,
		class: Class.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	LASER_FOCUS: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	LAST_RESORT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 140,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	LAVA_PLUME: {
		type: Type.FIRE,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	LEAF_BLADE: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	LEAF_STORM: {
		type: Type.GRASS,
		class: Class.Special,
		power: 130,
		accuracy: 90,
		pp: 5,
		effect: { kind: "none" },
	},
	LEECH_LIFE: {
		type: Type.BUG,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	LICK: {
		type: Type.GHOST,
		class: Class.Physical,
		power: 30,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	LIFE_DEW: {
		type: Type.WATER,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	LIQUIDATION: {
		type: Type.WATER,
		class: Class.Physical,
		power: 85,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	LOCK_ON: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	LOVELY_KISS: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 75,
		pp: 10,
		effect: { kind: "none" },
	},
	LOW_KICK: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	LOW_SWEEP: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	MACH_PUNCH: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	MAGNET_RISE: {
		type: Type.ELECTRIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	MAGNETIC_FLUX: {
		type: Type.ELECTRIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	MEGA_DRAIN: {
		type: Type.GRASS,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	MEGAHORN: {
		type: Type.BUG,
		class: Class.Physical,
		power: 120,
		accuracy: 85,
		pp: 10,
		effect: { kind: "none" },
	},
	MEMENTO: {
		type: Type.DARK,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	METAL_BURST: {
		type: Type.STEEL,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	METAL_CLAW: {
		type: Type.STEEL,
		class: Class.Physical,
		power: 50,
		accuracy: 95,
		pp: 35,
		effect: { kind: "none" },
	},
	METAL_SOUND: {
		type: Type.STEEL,
		class: Class.Status,
		power: 0,
		accuracy: 85,
		pp: 40,
		effect: { kind: "none" },
	},
	METEOR_MASH: {
		type: Type.STEEL,
		class: Class.Physical,
		power: 90,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	METRONOME: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	MIMIC: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	MINIMIZE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	MIRROR_COAT: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	MOONBLAST: {
		type: Type.FAIRY,
		class: Class.Special,
		power: 95,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	MOONLIGHT: {
		type: Type.FAIRY,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	MORNING_SUN: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	MUD_SHOT: {
		type: Type.GROUND,
		class: Class.Special,
		power: 55,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	MUD_SLAP: {
		type: Type.GROUND,
		class: Class.Special,
		power: 20,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	MUDDY_WATER: {
		type: Type.WATER,
		class: Class.Special,
		power: 90,
		accuracy: 85,
		pp: 10,
		effect: { kind: "none" },
	},
	NASTY_PLOT: {
		type: Type.DARK,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	NIGHT_SHADE: {
		type: Type.GHOST,
		class: Class.Special,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	NIGHT_SLASH: {
		type: Type.DARK,
		class: Class.Physical,
		power: 70,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	NUZZLE: {
		type: Type.ELECTRIC,
		class: Class.Physical,
		power: 20,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	OUTRAGE: {
		type: Type.DRAGON,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	OVERHEAT: {
		type: Type.FIRE,
		class: Class.Special,
		power: 130,
		accuracy: 90,
		pp: 5,
		effect: { kind: "none" },
	},
	PAIN_SPLIT: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	PAYBACK: {
		type: Type.DARK,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	PECK: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 35,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	PERISH_SONG: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	PETAL_BLIZZARD: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	PLAY_NICE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	PLAY_ROUGH: {
		type: Type.FAIRY,
		class: Class.Physical,
		power: 90,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	PLUCK: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	POISON_FANG: {
		type: Type.POISON,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	POISON_GAS: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 90,
		pp: 40,
		effect: { kind: "none" },
	},
	POISON_JAB: {
		type: Type.POISON,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	POISON_TAIL: {
		type: Type.POISON,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	POWDER_SNOW: {
		type: Type.ICE,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	POWER_GEM: {
		type: Type.ROCK,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	POWER_SPLIT: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	POWER_SWAP: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	POWER_WHIP: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 120,
		accuracy: 85,
		pp: 10,
		effect: { kind: "none" },
	},
	PRESENT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 0,
		accuracy: 90,
		pp: 15,
		effect: { kind: "none" },
	},
	PSYBEAM: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	PSYCH_UP: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	PSYCHIC: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	PSYCHO_CUT: {
		type: Type.PSYCHIC,
		class: Class.Physical,
		power: 70,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	PSYSHOCK: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	PSYSTRIKE: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 100,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	QUICK_GUARD: {
		type: Type.FIGHTING,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	QUIVER_DANCE: {
		type: Type.BUG,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	RAGE_FIST: {
		type: Type.GHOST,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	RAGE_POWDER: {
		type: Type.BUG,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	RAGING_BULL: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	RAGING_FURY: {
		type: Type.FIRE,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	RAPID_SPIN: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 40,
		effect: { kind: "none" },
	},
	RAZOR_SHELL: {
		type: Type.WATER,
		class: Class.Physical,
		power: 75,
		accuracy: 95,
		pp: 10,
		effect: { kind: "none" },
	},
	RECOVER: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	RECYCLE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	REFLECT_TYPE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	REST: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	RETALIATE: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 70,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	REVENGE: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	REVERSAL: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	ROAR: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	ROCK_BLAST: {
		type: Type.ROCK,
		class: Class.Physical,
		power: 25,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	ROCK_POLISH: {
		type: Type.ROCK,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	ROCK_SLIDE: {
		type: Type.ROCK,
		class: Class.Physical,
		power: 75,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	ROCK_SMASH: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	ROCK_THROW: {
		type: Type.ROCK,
		class: Class.Physical,
		power: 50,
		accuracy: 90,
		pp: 15,
		effect: { kind: "none" },
	},
	ROLE_PLAY: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	ROLLOUT: {
		type: Type.ROCK,
		class: Class.Physical,
		power: 30,
		accuracy: 90,
		pp: 20,
		effect: { kind: "none" },
	},
	ROOST: {
		type: Type.FLYING,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	ROUND: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 60,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SAND_TOMB: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 35,
		accuracy: 85,
		pp: 15,
		effect: { kind: "none" },
	},
	SCARY_FACE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SCREECH: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 85,
		pp: 40,
		effect: { kind: "none" },
	},
	SEED_BOMB: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SEISMIC_TOSS: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SELF_DESTRUCT: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 200,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	SHADOW_BALL: {
		type: Type.GHOST,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SHADOW_PUNCH: {
		type: Type.GHOST,
		class: Class.Physical,
		power: 60,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	SHADOW_SNEAK: {
		type: Type.GHOST,
		class: Class.Physical,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	SHEER_COLD: {
		type: Type.ICE,
		class: Class.Special,
		power: 0,
		accuracy: 30,
		pp: 5,
		effect: { kind: "none" },
	},
	SHELL_SMASH: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 15,
		effect: { kind: "none" },
	},
	SHOCK_WAVE: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 60,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	SIMPLE_BEAM: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SING: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 55,
		pp: 15,
		effect: { kind: "none" },
	},
	SKULL_BASH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 130,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SKY_ATTACK: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 140,
		accuracy: 90,
		pp: 5,
		effect: { kind: "none" },
	},
	SLACK_OFF: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	SLASH: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 70,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SLEEP_TALK: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	SLUDGE: {
		type: Type.POISON,
		class: Class.Special,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SLUDGE_BOMB: {
		type: Type.POISON,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SLUDGE_WAVE: {
		type: Type.POISON,
		class: Class.Special,
		power: 95,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SMACK_DOWN: {
		type: Type.ROCK,
		class: Class.Physical,
		power: 50,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SMOG: {
		type: Type.POISON,
		class: Class.Special,
		power: 30,
		accuracy: 70,
		pp: 20,
		effect: { kind: "none" },
	},
	SNORE: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 50,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	SOAK: {
		type: Type.WATER,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SOFT_BOILED: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	SPARK: {
		type: Type.ELECTRIC,
		class: Class.Physical,
		power: 65,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SPARKLING_ARIA: {
		type: Type.WATER,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SPIT_UP: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SPITE: {
		type: Type.GHOST,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SPLASH: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "none" },
	},
	SPORE: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	STOCKPILE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	STOMPING_TANTRUM: {
		type: Type.GROUND,
		class: Class.Physical,
		power: 75,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STONE_EDGE: {
		type: Type.ROCK,
		class: Class.Physical,
		power: 100,
		accuracy: 80,
		pp: 5,
		effect: { kind: "none" },
	},
	STORED_POWER: {
		type: Type.PSYCHIC,
		class: Class.Special,
		power: 20,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STORM_THROW: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STRENGTH_SAP: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	STUN_SPORE: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 75,
		pp: 30,
		effect: { kind: "none" },
	},
	SUBMISSION: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 80,
		accuracy: 80,
		pp: 20,
		effect: { kind: "none" },
	},
	SUCKER_PUNCH: {
		type: Type.DARK,
		class: Class.Physical,
		power: 70,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	SUPER_FANG: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 0,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	SUPERPOWER: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	SUPERSONIC: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 55,
		pp: 20,
		effect: { kind: "none" },
	},
	SWAGGER: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 85,
		pp: 15,
		effect: { kind: "none" },
	},
	SWALLOW: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	SWEET_KISS: {
		type: Type.FAIRY,
		class: Class.Status,
		power: 0,
		accuracy: 75,
		pp: 10,
		effect: { kind: "none" },
	},
	SWEET_SCENT: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	SWIFT: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 60,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	SWITCHEROO: {
		type: Type.DARK,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	SWORDS_DANCE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	SYNTHESIS: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 5,
		effect: { kind: "none" },
	},
	TEETER_DANCE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	TELEPORT: {
		type: Type.PSYCHIC,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	THUNDER: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 110,
		accuracy: 70,
		pp: 10,
		effect: { kind: "none" },
	},
	THUNDER_FANG: {
		type: Type.ELECTRIC,
		class: Class.Physical,
		power: 65,
		accuracy: 95,
		pp: 15,
		effect: { kind: "none" },
	},
	THUNDER_WAVE: {
		type: Type.ELECTRIC,
		class: Class.Status,
		power: 0,
		accuracy: 90,
		pp: 20,
		effect: { kind: "none" },
	},
	THUNDERBOLT: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	TICKLE: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	TOXIC: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 90,
		pp: 10,
		effect: { kind: "none" },
	},
	TRANSFORM: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	TRI_ATTACK: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 80,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	TWISTER: {
		type: Type.DRAGON,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	UPROAR: {
		type: Type.NORMAL,
		class: Class.Special,
		power: 90,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	VACUUM_WAVE: {
		type: Type.FIGHTING,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	VENOM_DRENCH: {
		type: Type.POISON,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	VENOSHOCK: {
		type: Type.POISON,
		class: Class.Special,
		power: 65,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	VICE_GRIP: {
		type: Type.NORMAL,
		class: Class.Physical,
		power: 55,
		accuracy: 100,
		pp: 30,
		effect: { kind: "none" },
	},
	VITAL_THROW: {
		type: Type.FIGHTING,
		class: Class.Physical,
		power: 70,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	WATER_GUN: {
		type: Type.WATER,
		class: Class.Special,
		power: 40,
		accuracy: 100,
		pp: 25,
		effect: { kind: "none" },
	},
	WATER_PULSE: {
		type: Type.WATER,
		class: Class.Special,
		power: 60,
		accuracy: 100,
		pp: 20,
		effect: { kind: "none" },
	},
	WATER_SPOUT: {
		type: Type.WATER,
		class: Class.Special,
		power: 150,
		accuracy: 100,
		pp: 5,
		effect: { kind: "none" },
	},
	WATERFALL: {
		type: Type.WATER,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	WAVE_CRASH: {
		type: Type.WATER,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	WHIRLPOOL: {
		type: Type.WATER,
		class: Class.Special,
		power: 35,
		accuracy: 85,
		pp: 15,
		effect: { kind: "none" },
	},
	WHIRLWIND: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 20,
		effect: { kind: "none" },
	},
	WIDE_GUARD: {
		type: Type.ROCK,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	WILL_O_WISP: {
		type: Type.FIRE,
		class: Class.Status,
		power: 0,
		accuracy: 85,
		pp: 15,
		effect: { kind: "none" },
	},
	WING_ATTACK: {
		type: Type.FLYING,
		class: Class.Physical,
		power: 60,
		accuracy: 100,
		pp: 35,
		effect: { kind: "none" },
	},
	WISH: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	WITHDRAW: {
		type: Type.WATER,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 40,
		effect: { kind: "none" },
	},
	WOOD_HAMMER: {
		type: Type.GRASS,
		class: Class.Physical,
		power: 120,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	WORK_UP: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 30,
		effect: { kind: "none" },
	},
	WORRY_SEED: {
		type: Type.GRASS,
		class: Class.Status,
		power: 0,
		accuracy: 100,
		pp: 10,
		effect: { kind: "none" },
	},
	X_SCISSOR: {
		type: Type.BUG,
		class: Class.Physical,
		power: 80,
		accuracy: 100,
		pp: 15,
		effect: { kind: "none" },
	},
	YAWN: {
		type: Type.NORMAL,
		class: Class.Status,
		power: 0,
		accuracy: 0,
		pp: 10,
		effect: { kind: "none" },
	},
	ZAP_CANNON: {
		type: Type.ELECTRIC,
		class: Class.Special,
		power: 120,
		accuracy: 50,
		pp: 5,
		effect: { kind: "none" },
	},
	ZEN_HEADBUTT: {
		type: Type.PSYCHIC,
		class: Class.Physical,
		power: 80,
		accuracy: 90,
		pp: 15,
		effect: { kind: "none" },
	},
} satisfies Record<string, Move>;
