import type { Species, SpeciesId } from "../domain/species";

import { EvolutionMethod } from "../domain/evolution";
import { GrowthRate } from "../domain/growth-rate";
import { Genre } from "../domain/species";
import { Stat } from "../domain/stat";
import { Type } from "../domain/type";

export const SPECIES = {
	["BULBASAUR"]: {
		number: 1,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 64,
		catchRate: 45,
		growthRate: GrowthRate.MediumFast,
		stats: {
			[Stat.HP]: 45,
			[Stat.Attack]: 49,
			[Stat.Defense]: 49,
			[Stat.SpecialAttack]: 65,
			[Stat.SpecialDefense]: 65,
			[Stat.Speed]: 45,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 16,
				speciesId: "IVYSAUR",
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "TACKLE" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 7, moveId: "LEECH_SEED" },
			{ level: 13, moveId: "VINE_WHIP" },
			{ level: 22, moveId: "POISON_POWDER" },
			{ level: 30, moveId: "RAZOR_LEAF" },
			{ level: 38, moveId: "SLEEP_POWDER" },
			{ level: 46, moveId: "GROWTH" },
			{ level: 54, moveId: "SOLAR_BEAM" },
			// TM/HM Moves
			{ tmhm: 14 },
			{ tmhm: 92 },
			{ tmhm: 34 },
			{ tmhm: 36 },
			{ tmhm: 38 },
			{ tmhm: 99 },
			{ tmhm: 72 },
			{ tmhm: 76 },
			{ tmhm: 102 },
			{ tmhm: 104 },
			{ tmhm: 115 },
			{ tmhm: 117 },
			{ tmhm: 156 },
			{ tmhm: 164 },
			// Tutor Moves
			{ tutor: true, moveId: "SOLAR_BEAM" },
		],
	},
	["IVYSAUR"]: {
		number: 2,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 142,
		catchRate: 45,
		growthRate: GrowthRate.MediumSlow,
		stats: {
			[Stat.HP]: 60,
			[Stat.Attack]: 62,
			[Stat.Defense]: 63,
			[Stat.SpecialAttack]: 80,
			[Stat.SpecialDefense]: 80,
			[Stat.Speed]: 60,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 32,
				speciesId: "VENUSAUR",
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "TACKLE" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 7, moveId: "LEECH_SEED" },
			{ level: 13, moveId: "VINE_WHIP" },
			{ level: 22, moveId: "POISON_POWDER" },
			{ level: 30, moveId: "RAZOR_LEAF" },
			{ level: 38, moveId: "SLEEP_POWDER" },
			{ level: 46, moveId: "GROWTH" },
			{ level: 54, moveId: "SOLAR_BEAM" },
			// TM/HM Moves
			{ tmhm: 14 },
			{ tmhm: 92 },
			{ tmhm: 34 },
			{ tmhm: 36 },
			{ tmhm: 38 },
			{ tmhm: 99 },
			{ tmhm: 72 },
			{ tmhm: 76 },
			{ tmhm: 102 },
			{ tmhm: 104 },
			{ tmhm: 115 },
			{ tmhm: 117 },
			{ tmhm: 156 },
			{ tmhm: 164 },
			// Tutor Moves
			{ tutor: true, moveId: "SOLAR_BEAM" },
		],
	},
	["VENUSAUR"]: {
		number: 3,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 236,
		catchRate: 45,
		growthRate: GrowthRate.Slow,
		stats: {
			[Stat.HP]: 80,
			[Stat.Attack]: 82,
			[Stat.Defense]: 83,
			[Stat.SpecialAttack]: 100,
			[Stat.SpecialDefense]: 100,
			[Stat.Speed]: 80,
		},
		evolutions: [],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "TACKLE" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 7, moveId: "LEECH_SEED" },
			{ level: 13, moveId: "VINE_WHIP" },
			{ level: 22, moveId: "POISON_POWDER" },
			{ level: 30, moveId: "RAZOR_LEAF" },
			{ level: 38, moveId: "SLEEP_POWDER" },
			{ level: 46, moveId: "GROWTH" },
			{ level: 54, moveId: "SOLAR_BEAM" },
			// TM/HM Moves
			{ tmhm: 14 },
			{ tmhm: 92 },
			{ tmhm: 34 },
			{ tmhm: 36 },
			{ tmhm: 38 },
			{ tmhm: 99 },
			{ tmhm: 72 },
			{ tmhm: 76 },
			{ tmhm: 102 },
			{ tmhm: 104 },
			{ tmhm: 115 },
			{ tmhm: 117 },
			{ tmhm: 156 },
			{ tmhm: 164 },
			// Tutor Moves
			{ tutor: true, moveId: "SOLAR_BEAM" },
		],
	},
	["CHARMANDER"]: {
		number: 4,
		types: [Type.FIRE],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 62,
		catchRate: 45,
		growthRate: GrowthRate.Fast,
		stats: {
			[Stat.HP]: 39,
			[Stat.Attack]: 52,
			[Stat.Defense]: 43,
			[Stat.SpecialAttack]: 60,
			[Stat.SpecialDefense]: 50,
			[Stat.Speed]: 65,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 16,
				speciesId: "CHARMELEON",
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "SCRATCH" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 9, moveId: "EMBER" },
			{ level: 15, moveId: "SMOKE_SCREEN" },
			{ level: 24, moveId: "DRAGON_RAGE" },
			{ level: 33, moveId: "FIRE_FANG" },
			{ level: 42, moveId: "FLAMETHROWER" },
			{ level: 51, moveId: "FIRE_SPIN" },
			// TM/HM Moves
			{ tmhm: 52 },
			{ tmhm: 58 },
			{ tmhm: 59 },
			{ tmhm: 60 },
			{ tmhm: 61 },
			{ tmhm: 62 },
			{ tmhm: 63 },
			{ tmhm: 64 },
			{ tmhm: 104 },
			{ tmhm: 115 },
			{ tmhm: 126 },
			{ tmhm: 127 },
			{ tmhm: 128 },
			{ tmhm: 129 },
			{ tmhm: 130 },
			{ tmhm: 131 },
			// Tutor Moves
			{ tutor: true, moveId: "FLAMETHROWER" },
		],
	},
	["CHARMELEON"]: {
		number: 5,
		types: [Type.FIRE],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 142,
		catchRate: 45,
		growthRate: GrowthRate.Fluctuating,
		stats: {
			[Stat.HP]: 58,
			[Stat.Attack]: 64,
			[Stat.Defense]: 58,
			[Stat.SpecialAttack]: 80,
			[Stat.SpecialDefense]: 65,
			[Stat.Speed]: 80,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 36,
				speciesId: "CHARIZARD",
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "SCRATCH" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 9, moveId: "EMBER" },
			{ level: 15, moveId: "SMOKE_SCREEN" },
			{ level: 24, moveId: "DRAGON_RAGE" },
			{ level: 33, moveId: "FIRE_FANG" },
			{ level: 42, moveId: "FLAMETHROWER" },
			{ level: 51, moveId: "FIRE_SPIN" },
			// TM/HM Moves
			{ tmhm: 52 },
			{ tmhm: 58 },
			{ tmhm: 59 },
			{ tmhm: 60 },
			{ tmhm: 61 },
			{ tmhm: 62 },
			{ tmhm: 63 },
			{ tmhm: 64 },
			{ tmhm: 104 },
			{ tmhm: 115 },
			{ tmhm: 126 },
			{ tmhm: 127 },
			{ tmhm: 128 },
			{ tmhm: 129 },
			{ tmhm: 130 },
			{ tmhm: 131 },
			// Tutor Moves
			{ tutor: true, moveId: "FLAMETHROWER" },
		],
	},
	CHARIZARD: {
		number: 6,
		types: [Type.FIRE, Type.FLYING],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 240,
		catchRate: 45,
		growthRate: GrowthRate.Slow,
		stats: {
			[Stat.HP]: 78,
			[Stat.Attack]: 84,
			[Stat.Defense]: 78,
			[Stat.SpecialAttack]: 109,
			[Stat.SpecialDefense]: 85,
			[Stat.Speed]: 100,
		},
		evolutions: [],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "SCRATCH" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 9, moveId: "EMBER" },
			{ level: 15, moveId: "SMOKE_SCREEN" },
			{ level: 24, moveId: "DRAGON_RAGE" },
			{ level: 33, moveId: "FIRE_FANG" },
			{ level: 42, moveId: "FLAMETHROWER" },
			{ level: 51, moveId: "FIRE_SPIN" },
			// TM/HM Moves
			{ tmhm: 52 },
			{ tmhm: 58 },
			{ tmhm: 59 },
			{ tmhm: 60 },
			{ tmhm: 61 },
			{ tmhm: 62 },
			{ tmhm: 63 },
			{ tmhm: 64 },
			{ tmhm: 104 },
			{ tmhm: 115 },
			{ tmhm: 126 },
			{ tmhm: 127 },
			{ tmhm: 128 },
			{ tmhm: 129 },
			{ tmhm: 130 },
			{ tmhm: 131 },
			// Tutor Moves
			{ tutor: true, moveId: "FLAMETHROWER" },
		],
	},
} satisfies Record<SpeciesId, Species>;
