import type { Species } from "../domain/species";

import { EvolutionMethod } from "../domain/evolution";
import { GrowthRate } from "../domain/growth-rate";
import { Genre } from "../domain/species";
import { Stat } from "../domain/stat";
import { Type } from "../domain/type";

import { MOVES } from "./moves";

export const SPECIES = {
	["BULBASAUR" as Species.Symbol]: {
		number: 1,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 64,
		catchRate: 45,
		growthRate: GrowthRate.MediumFast,
		stats: {
			[Stat.HP]: 45,
			[Stat.Attack]: 49,
			[Stat.Defense]: 49,
			[Stat.SpecialAttack]: 65,
			[Stat.SpecialDefense]: 65,
			[Stat.Speed]: 45,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 16,
				species: "IVYSAUR" as Species.Symbol,
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, move: MOVES["TACKLE"] },
			{ level: 1, move: MOVES["GROWL"] },
			// Level Up Moves
			{ level: 7, move: MOVES["LEECH_SEED"] },
			{ level: 13, move: MOVES["VINE_WHIP"] },
			{ level: 22, move: MOVES["POISON_POWDER"] },
			{ level: 30, move: MOVES["RAZOR_LEAF"] },
			{ level: 38, move: MOVES["SLEEP_POWDER"] },
			{ level: 46, move: MOVES["GROWTH"] },
			{ level: 54, move: MOVES["SOLAR_BEAM"] },
			// TM/HM Moves
			{ tmhm: 14, move: MOVES["TACKLE"] },
			{ tmhm: 92, move: MOVES["GROWL"] },
			{ tmhm: 34, move: MOVES["LEECH_SEED"] },
			{ tmhm: 36, move: MOVES["VINE_WHIP"] },
			{ tmhm: 38, move: MOVES["POISON_POWDER"] },
			{ tmhm: 99, move: MOVES["RAZOR_LEAF"] },
			{ tmhm: 72, move: MOVES["SLEEP_POWDER"] },
			{ tmhm: 76, move: MOVES["GROWTH"] },
			{ tmhm: 102, move: MOVES["SOLAR_BEAM"] },
			{ tmhm: 104, move: MOVES["TACKLE"] },
			{ tmhm: 115, move: MOVES["GROWL"] },
			{ tmhm: 117, move: MOVES["LEECH_SEED"] },
			{ tmhm: 156, move: MOVES["VINE_WHIP"] },
			{ tmhm: 164, move: MOVES["POISON_POWDER"] },
			// Tutor Moves
			{ tutor: true, move: MOVES["SOLAR_BEAM"] },
		],
	},
	["IVYSAUR" as Species.Symbol]: {
		number: 2,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 142,
		catchRate: 45,
		growthRate: GrowthRate.MediumSlow,
		stats: {
			[Stat.HP]: 60,
			[Stat.Attack]: 62,
			[Stat.Defense]: 63,
			[Stat.SpecialAttack]: 80,
			[Stat.SpecialDefense]: 80,
			[Stat.Speed]: 60,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 32,
				species: "VENUSAUR" as Species.Symbol,
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, move: MOVES["TACKLE"] },
			{ level: 1, move: MOVES["GROWL"] },
			// Level Up Moves
			{ level: 7, move: MOVES["LEECH_SEED"] },
			{ level: 13, move: MOVES["VINE_WHIP"] },
			{ level: 22, move: MOVES["POISON_POWDER"] },
			{ level: 30, move: MOVES["RAZOR_LEAF"] },
			{ level: 38, move: MOVES["SLEEP_POWDER"] },
			{ level: 46, move: MOVES["GROWTH"] },
			{ level: 54, move: MOVES["SOLAR_BEAM"] },
			// TM/HM Moves
			{ tmhm: 14, move: MOVES["TACKLE"] },
			{ tmhm: 92, move: MOVES["GROWL"] },
			{ tmhm: 34, move: MOVES["LEECH_SEED"] },
			{ tmhm: 36, move: MOVES["VINE_WHIP"] },
			{ tmhm: 38, move: MOVES["POISON_POWDER"] },
			{ tmhm: 99, move: MOVES["RAZOR_LEAF"] },
			{ tmhm: 72, move: MOVES["SLEEP_POWDER"] },
			{ tmhm: 76, move: MOVES["GROWTH"] },
			{ tmhm: 102, move: MOVES["SOLAR_BEAM"] },
			{ tmhm: 104, move: MOVES["TACKLE"] },
			{ tmhm: 115, move: MOVES["GROWL"] },
			{ tmhm: 117, move: MOVES["LEECH_SEED"] },
			{ tmhm: 156, move: MOVES["VINE_WHIP"] },
			{ tmhm: 164, move: MOVES["POISON_POWDER"] },
			// Tutor Moves
			{ tutor: true, move: MOVES["SOLAR_BEAM"] },
		],
	},
	["VENUSAUR" as Species.Symbol]: {
		number: 3,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 236,
		catchRate: 45,
		growthRate: GrowthRate.Slow,
		stats: {
			[Stat.HP]: 80,
			[Stat.Attack]: 82,
			[Stat.Defense]: 83,
			[Stat.SpecialAttack]: 100,
			[Stat.SpecialDefense]: 100,
			[Stat.Speed]: 80,
		},
		evolutions: [],
		learnset: [
			// Level 1 Moves
			{ level: 1, move: MOVES["TACKLE"] },
			{ level: 1, move: MOVES["GROWL"] },
			// Level Up Moves
			{ level: 7, move: MOVES["LEECH_SEED"] },
			{ level: 13, move: MOVES["VINE_WHIP"] },
			{ level: 22, move: MOVES["POISON_POWDER"] },
			{ level: 30, move: MOVES["RAZOR_LEAF"] },
			{ level: 38, move: MOVES["SLEEP_POWDER"] },
			{ level: 46, move: MOVES["GROWTH"] },
			{ level: 54, move: MOVES["SOLAR_BEAM"] },
			// TM/HM Moves
			{ tmhm: 14, move: MOVES["TACKLE"] },
			{ tmhm: 92, move: MOVES["GROWL"] },
			{ tmhm: 34, move: MOVES["LEECH_SEED"] },
			{ tmhm: 36, move: MOVES["VINE_WHIP"] },
			{ tmhm: 38, move: MOVES["POISON_POWDER"] },
			{ tmhm: 99, move: MOVES["RAZOR_LEAF"] },
			{ tmhm: 72, move: MOVES["SLEEP_POWDER"] },
			{ tmhm: 76, move: MOVES["GROWTH"] },
			{ tmhm: 102, move: MOVES["SOLAR_BEAM"] },
			{ tmhm: 104, move: MOVES["TACKLE"] },
			{ tmhm: 115, move: MOVES["GROWL"] },
			{ tmhm: 117, move: MOVES["LEECH_SEED"] },
			{ tmhm: 156, move: MOVES["VINE_WHIP"] },
			{ tmhm: 164, move: MOVES["POISON_POWDER"] },
			// Tutor Moves
			{ tutor: true, move: MOVES["SOLAR_BEAM"] },
		],
	},
	["CHARMANDER" as Species.Symbol]: {
		number: 4,
		types: [Type.FIRE],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 62,
		catchRate: 45,
		growthRate: GrowthRate.Fast,
		stats: {
			[Stat.HP]: 39,
			[Stat.Attack]: 52,
			[Stat.Defense]: 43,
			[Stat.SpecialAttack]: 60,
			[Stat.SpecialDefense]: 50,
			[Stat.Speed]: 65,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 16,
				species: "CHARMELEON" as Species.Symbol,
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, move: MOVES["SCRATCH"] },
			{ level: 1, move: MOVES["GROWL"] },
			// Level Up Moves
			{ level: 9, move: MOVES["EMBER"] },
			{ level: 15, move: MOVES["SMOKE_SCREEN"] },
			{ level: 24, move: MOVES["DRAGON_RAGE"] },
			{ level: 33, move: MOVES["FIRE_FANG"] },
			{ level: 42, move: MOVES["FLAMETHROWER"] },
			{ level: 51, move: MOVES["FIRE_SPIN"] },
			// TM/HM Moves
			{ tmhm: 52, move: MOVES["SCRATCH"] },
			{ tmhm: 58, move: MOVES["GROWL"] },
			{ tmhm: 59, move: MOVES["EMBER"] },
			{ tmhm: 60, move: MOVES["SMOKE_SCREEN"] },
			{ tmhm: 61, move: MOVES["DRAGON_RAGE"] },
			{ tmhm: 62, move: MOVES["FIRE_FANG"] },
			{ tmhm: 63, move: MOVES["FLAMETHROWER"] },
			{ tmhm: 64, move: MOVES["FIRE_SPIN"] },
			{ tmhm: 104, move: MOVES["SCRATCH"] },
			{ tmhm: 115, move: MOVES["GROWL"] },
			{ tmhm: 126, move: MOVES["EMBER"] },
			{ tmhm: 127, move: MOVES["SMOKE_SCREEN"] },
			{ tmhm: 128, move: MOVES["DRAGON_RAGE"] },
			{ tmhm: 129, move: MOVES["FIRE_FANG"] },
			{ tmhm: 130, move: MOVES["FLAMETHROWER"] },
			{ tmhm: 131, move: MOVES["FIRE_SPIN"] },
			// Tutor Moves
			{ tutor: true, move: MOVES["FLAMETHROWER"] },
		],
	},
	["CHARMELEON" as Species.Symbol]: {
		number: 5,
		types: [Type.FIRE],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 142,
		catchRate: 45,
		growthRate: GrowthRate.Fluctuating,
		stats: {
			[Stat.HP]: 58,
			[Stat.Attack]: 64,
			[Stat.Defense]: 58,
			[Stat.SpecialAttack]: 80,
			[Stat.SpecialDefense]: 65,
			[Stat.Speed]: 80,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 36,
				species: "CHARIZARD" as Species.Symbol,
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, move: MOVES["SCRATCH"] },
			{ level: 1, move: MOVES["GROWL"] },
			// Level Up Moves
			{ level: 9, move: MOVES["EMBER"] },
			{ level: 15, move: MOVES["SMOKE_SCREEN"] },
			{ level: 24, move: MOVES["DRAGON_RAGE"] },
			{ level: 33, move: MOVES["FIRE_FANG"] },
			{ level: 42, move: MOVES["FLAMETHROWER"] },
			{ level: 51, move: MOVES["FIRE_SPIN"] },
			// TM/HM Moves
			{ tmhm: 52, move: MOVES["SCRATCH"] },
			{ tmhm: 58, move: MOVES["GROWL"] },
			{ tmhm: 59, move: MOVES["EMBER"] },
			{ tmhm: 60, move: MOVES["SMOKE_SCREEN"] },
			{ tmhm: 61, move: MOVES["DRAGON_RAGE"] },
			{ tmhm: 62, move: MOVES["FIRE_FANG"] },
			{ tmhm: 63, move: MOVES["FLAMETHROWER"] },
			{ tmhm: 64, move: MOVES["FIRE_SPIN"] },
			{ tmhm: 104, move: MOVES["SCRATCH"] },
			{ tmhm: 115, move: MOVES["GROWL"] },
			{ tmhm: 126, move: MOVES["EMBER"] },
			{ tmhm: 127, move: MOVES["SMOKE_SCREEN"] },
			{ tmhm: 128, move: MOVES["DRAGON_RAGE"] },
			{ tmhm: 129, move: MOVES["FIRE_FANG"] },
			{ tmhm: 130, move: MOVES["FLAMETHROWER"] },
			{ tmhm: 131, move: MOVES["FIRE_SPIN"] },
			// Tutor Moves
			{ tutor: true, move: MOVES["FLAMETHROWER"] },
		],
	},
	["CHARIZARD" as Species.Symbol]: {
		number: 6,
		types: [Type.FIRE, Type.FLYING],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 240,
		catchRate: 45,
		growthRate: GrowthRate.Slow,
		stats: {
			[Stat.HP]: 78,
			[Stat.Attack]: 84,
			[Stat.Defense]: 78,
			[Stat.SpecialAttack]: 109,
			[Stat.SpecialDefense]: 85,
			[Stat.Speed]: 100,
		},
		evolutions: [],
		learnset: [
			// Level 1 Moves
			{ level: 1, move: MOVES["SCRATCH"] },
			{ level: 1, move: MOVES["GROWL"] },
			// Level Up Moves
			{ level: 9, move: MOVES["EMBER"] },
			{ level: 15, move: MOVES["SMOKE_SCREEN"] },
			{ level: 24, move: MOVES["DRAGON_RAGE"] },
			{ level: 33, move: MOVES["FIRE_FANG"] },
			{ level: 42, move: MOVES["FLAMETHROWER"] },
			{ level: 51, move: MOVES["FIRE_SPIN"] },
			// TM/HM Moves
			{ tmhm: 52, move: MOVES["SCRATCH"] },
			{ tmhm: 58, move: MOVES["GROWL"] },
			{ tmhm: 59, move: MOVES["EMBER"] },
			{ tmhm: 60, move: MOVES["SMOKE_SCREEN"] },
			{ tmhm: 61, move: MOVES["DRAGON_RAGE"] },
			{ tmhm: 62, move: MOVES["FIRE_FANG"] },
			{ tmhm: 63, move: MOVES["FLAMETHROWER"] },
			{ tmhm: 64, move: MOVES["FIRE_SPIN"] },
			{ tmhm: 104, move: MOVES["SCRATCH"] },
			{ tmhm: 115, move: MOVES["GROWL"] },
			{ tmhm: 126, move: MOVES["EMBER"] },
			{ tmhm: 127, move: MOVES["SMOKE_SCREEN"] },
			{ tmhm: 128, move: MOVES["DRAGON_RAGE"] },
			{ tmhm: 129, move: MOVES["FIRE_FANG"] },
			{ tmhm: 130, move: MOVES["FLAMETHROWER"] },
			{ tmhm: 131, move: MOVES["FIRE_SPIN"] },
			// Tutor Moves
			{ tutor: true, move: MOVES["FLAMETHROWER"] },
		],
	},
} satisfies Record<Species.Symbol, Species>;
