import type { Species } from "../domain/species";

import { EvolutionMethod } from "../domain/evolution";
import { GrowthRate } from "../domain/growth-rate";
import { Genre } from "../domain/species";
import { Stat } from "../domain/stat";
import { Type } from "../domain/type";

export const SPECIES = {
	["BULBASAUR" as Species.Symbol]: {
		number: 1,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 64,
		catchRate: 45,
		growthRate: GrowthRate.MediumFast,
		stats: {
			[Stat.HP]: 45,
			[Stat.Attack]: 49,
			[Stat.Defense]: 49,
			[Stat.SpecialAttack]: 65,
			[Stat.SpecialDefense]: 65,
			[Stat.Speed]: 45,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 16,
				speciesId: "IVYSAUR" as Species.Symbol,
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "TACKLE" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 7, moveId: "LEECH_SEED" },
			{ level: 13, moveId: "VINE_WHIP" },
			{ level: 22, moveId: "POISON_POWDER" },
			{ level: 30, moveId: "RAZOR_LEAF" },
			{ level: 38, moveId: "SLEEP_POWDER" },
			{ level: 46, moveId: "GROWTH" },
			{ level: 54, moveId: "SOLAR_BEAM" },
			// TM/HM Moves
			{ tmhm: 14, moveId: "TACKLE" },
			{ tmhm: 92, moveId: "GROWL" },
			{ tmhm: 34, moveId: "LEECH_SEED" },
			{ tmhm: 36, moveId: "VINE_WHIP" },
			{ tmhm: 38, moveId: "POISON_POWDER" },
			{ tmhm: 99, moveId: "RAZOR_LEAF" },
			{ tmhm: 72, moveId: "SLEEP_POWDER" },
			{ tmhm: 76, moveId: "GROWTH" },
			{ tmhm: 102, moveId: "SOLAR_BEAM" },
			{ tmhm: 104, moveId: "TACKLE" },
			{ tmhm: 115, moveId: "GROWL" },
			{ tmhm: 117, moveId: "LEECH_SEED" },
			{ tmhm: 156, moveId: "VINE_WHIP" },
			{ tmhm: 164, moveId: "POISON_POWDER" },
			// Tutor Moves
			{ tutor: true, moveId: "SOLAR_BEAM" },
		],
	},
	["IVYSAUR" as Species.Symbol]: {
		number: 2,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 142,
		catchRate: 45,
		growthRate: GrowthRate.MediumSlow,
		stats: {
			[Stat.HP]: 60,
			[Stat.Attack]: 62,
			[Stat.Defense]: 63,
			[Stat.SpecialAttack]: 80,
			[Stat.SpecialDefense]: 80,
			[Stat.Speed]: 60,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 32,
				speciesId: "VENUSAUR" as Species.Symbol,
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "TACKLE" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 7, moveId: "LEECH_SEED" },
			{ level: 13, moveId: "VINE_WHIP" },
			{ level: 22, moveId: "POISON_POWDER" },
			{ level: 30, moveId: "RAZOR_LEAF" },
			{ level: 38, moveId: "SLEEP_POWDER" },
			{ level: 46, moveId: "GROWTH" },
			{ level: 54, moveId: "SOLAR_BEAM" },
			// TM/HM Moves
			{ tmhm: 14, moveId: "TACKLE" },
			{ tmhm: 92, moveId: "GROWL" },
			{ tmhm: 34, moveId: "LEECH_SEED" },
			{ tmhm: 36, moveId: "VINE_WHIP" },
			{ tmhm: 38, moveId: "POISON_POWDER" },
			{ tmhm: 99, moveId: "RAZOR_LEAF" },
			{ tmhm: 72, moveId: "SLEEP_POWDER" },
			{ tmhm: 76, moveId: "GROWTH" },
			{ tmhm: 102, moveId: "SOLAR_BEAM" },
			{ tmhm: 104, moveId: "TACKLE" },
			{ tmhm: 115, moveId: "GROWL" },
			{ tmhm: 117, moveId: "LEECH_SEED" },
			{ tmhm: 156, moveId: "VINE_WHIP" },
			{ tmhm: 164, moveId: "POISON_POWDER" },
			// Tutor Moves
			{ tutor: true, moveId: "SOLAR_BEAM" },
		],
	},
	["VENUSAUR" as Species.Symbol]: {
		number: 3,
		types: [Type.GRASS, Type.POISON],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 236,
		catchRate: 45,
		growthRate: GrowthRate.Slow,
		stats: {
			[Stat.HP]: 80,
			[Stat.Attack]: 82,
			[Stat.Defense]: 83,
			[Stat.SpecialAttack]: 100,
			[Stat.SpecialDefense]: 100,
			[Stat.Speed]: 80,
		},
		evolutions: [],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "TACKLE" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 7, moveId: "LEECH_SEED" },
			{ level: 13, moveId: "VINE_WHIP" },
			{ level: 22, moveId: "POISON_POWDER" },
			{ level: 30, moveId: "RAZOR_LEAF" },
			{ level: 38, moveId: "SLEEP_POWDER" },
			{ level: 46, moveId: "GROWTH" },
			{ level: 54, moveId: "SOLAR_BEAM" },
			// TM/HM Moves
			{ tmhm: 14, moveId: "TACKLE" },
			{ tmhm: 92, moveId: "GROWL" },
			{ tmhm: 34, moveId: "LEECH_SEED" },
			{ tmhm: 36, moveId: "VINE_WHIP" },
			{ tmhm: 38, moveId: "POISON_POWDER" },
			{ tmhm: 99, moveId: "RAZOR_LEAF" },
			{ tmhm: 72, moveId: "SLEEP_POWDER" },
			{ tmhm: 76, moveId: "GROWTH" },
			{ tmhm: 102, moveId: "SOLAR_BEAM" },
			{ tmhm: 104, moveId: "TACKLE" },
			{ tmhm: 115, moveId: "GROWL" },
			{ tmhm: 117, moveId: "LEECH_SEED" },
			{ tmhm: 156, moveId: "VINE_WHIP" },
			{ tmhm: 164, moveId: "POISON_POWDER" },
			// Tutor Moves
			{ tutor: true, moveId: "SOLAR_BEAM" },
		],
	},
	["CHARMANDER" as Species.Symbol]: {
		number: 4,
		types: [Type.FIRE],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 62,
		catchRate: 45,
		growthRate: GrowthRate.Fast,
		stats: {
			[Stat.HP]: 39,
			[Stat.Attack]: 52,
			[Stat.Defense]: 43,
			[Stat.SpecialAttack]: 60,
			[Stat.SpecialDefense]: 50,
			[Stat.Speed]: 65,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 16,
				speciesId: "CHARMELEON" as Species.Symbol,
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "SCRATCH" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 9, moveId: "EMBER" },
			{ level: 15, moveId: "SMOKE_SCREEN" },
			{ level: 24, moveId: "DRAGON_RAGE" },
			{ level: 33, moveId: "FIRE_FANG" },
			{ level: 42, moveId: "FLAMETHROWER" },
			{ level: 51, moveId: "FIRE_SPIN" },
			// TM/HM Moves
			{ tmhm: 52, moveId: "SCRATCH" },
			{ tmhm: 58, moveId: "GROWL" },
			{ tmhm: 59, moveId: "EMBER" },
			{ tmhm: 60, moveId: "SMOKE_SCREEN" },
			{ tmhm: 61, moveId: "DRAGON_RAGE" },
			{ tmhm: 62, moveId: "FIRE_FANG" },
			{ tmhm: 63, moveId: "FLAMETHROWER" },
			{ tmhm: 64, moveId: "FIRE_SPIN" },
			{ tmhm: 104, moveId: "SCRATCH" },
			{ tmhm: 115, moveId: "GROWL" },
			{ tmhm: 126, moveId: "EMBER" },
			{ tmhm: 127, moveId: "SMOKE_SCREEN" },
			{ tmhm: 128, moveId: "DRAGON_RAGE" },
			{ tmhm: 129, moveId: "FIRE_FANG" },
			{ tmhm: 130, moveId: "FLAMETHROWER" },
			{ tmhm: 131, moveId: "FIRE_SPIN" },
			// Tutor Moves
			{ tutor: true, moveId: "FLAMETHROWER" },
		],
	},
	["CHARMELEON" as Species.Symbol]: {
		number: 5,
		types: [Type.FIRE],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 142,
		catchRate: 45,
		growthRate: GrowthRate.Fluctuating,
		stats: {
			[Stat.HP]: 58,
			[Stat.Attack]: 64,
			[Stat.Defense]: 58,
			[Stat.SpecialAttack]: 80,
			[Stat.SpecialDefense]: 65,
			[Stat.Speed]: 80,
		},
		evolutions: [
			{
				method: EvolutionMethod.Level,
				level: 36,
				speciesId: "CHARIZARD" as Species.Symbol,
			},
		],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "SCRATCH" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 9, moveId: "EMBER" },
			{ level: 15, moveId: "SMOKE_SCREEN" },
			{ level: 24, moveId: "DRAGON_RAGE" },
			{ level: 33, moveId: "FIRE_FANG" },
			{ level: 42, moveId: "FLAMETHROWER" },
			{ level: 51, moveId: "FIRE_SPIN" },
			// TM/HM Moves
			{ tmhm: 52, moveId: "SCRATCH" },
			{ tmhm: 58, moveId: "GROWL" },
			{ tmhm: 59, moveId: "EMBER" },
			{ tmhm: 60, moveId: "SMOKE_SCREEN" },
			{ tmhm: 61, moveId: "DRAGON_RAGE" },
			{ tmhm: 62, moveId: "FIRE_FANG" },
			{ tmhm: 63, moveId: "FLAMETHROWER" },
			{ tmhm: 64, moveId: "FIRE_SPIN" },
			{ tmhm: 104, moveId: "SCRATCH" },
			{ tmhm: 115, moveId: "GROWL" },
			{ tmhm: 126, moveId: "EMBER" },
			{ tmhm: 127, moveId: "SMOKE_SCREEN" },
			{ tmhm: 128, moveId: "DRAGON_RAGE" },
			{ tmhm: 129, moveId: "FIRE_FANG" },
			{ tmhm: 130, moveId: "FLAMETHROWER" },
			{ tmhm: 131, moveId: "FIRE_SPIN" },
			// Tutor Moves
			{ tutor: true, moveId: "FLAMETHROWER" },
		],
	},
	["CHARIZARD" as Species.Symbol]: {
		number: 6,
		types: [Type.FIRE, Type.FLYING],
		gender: { [Genre.Male]: 87.5, [Genre.Female]: 12.5 },
		baseExperience: 240,
		catchRate: 45,
		growthRate: GrowthRate.Slow,
		stats: {
			[Stat.HP]: 78,
			[Stat.Attack]: 84,
			[Stat.Defense]: 78,
			[Stat.SpecialAttack]: 109,
			[Stat.SpecialDefense]: 85,
			[Stat.Speed]: 100,
		},
		evolutions: [],
		learnset: [
			// Level 1 Moves
			{ level: 1, moveId: "SCRATCH" },
			{ level: 1, moveId: "GROWL" },
			// Level Up Moves
			{ level: 9, moveId: "EMBER" },
			{ level: 15, moveId: "SMOKE_SCREEN" },
			{ level: 24, moveId: "DRAGON_RAGE" },
			{ level: 33, moveId: "FIRE_FANG" },
			{ level: 42, moveId: "FLAMETHROWER" },
			{ level: 51, moveId: "FIRE_SPIN" },
			// TM/HM Moves
			{ tmhm: 52, moveId: "SCRATCH" },
			{ tmhm: 58, moveId: "GROWL" },
			{ tmhm: 59, moveId: "EMBER" },
			{ tmhm: 60, moveId: "SMOKE_SCREEN" },
			{ tmhm: 61, moveId: "DRAGON_RAGE" },
			{ tmhm: 62, moveId: "FIRE_FANG" },
			{ tmhm: 63, moveId: "FLAMETHROWER" },
			{ tmhm: 64, moveId: "FIRE_SPIN" },
			{ tmhm: 104, moveId: "SCRATCH" },
			{ tmhm: 115, moveId: "GROWL" },
			{ tmhm: 126, moveId: "EMBER" },
			{ tmhm: 127, moveId: "SMOKE_SCREEN" },
			{ tmhm: 128, moveId: "DRAGON_RAGE" },
			{ tmhm: 129, moveId: "FIRE_FANG" },
			{ tmhm: 130, moveId: "FLAMETHROWER" },
			{ tmhm: 131, moveId: "FIRE_SPIN" },
			// Tutor Moves
			{ tutor: true, moveId: "FLAMETHROWER" },
		],
	},
} satisfies Record<Species.Symbol, Species>;
