/**
 * Custom environment bindings not auto-generated by wrangler. Regenerate the base
 * `Cloudflare.Env` with `bun run cf:typegen`.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */
declare namespace Cloudflare {
	interface Env {
		BLOG: DurableObjectNamespace;
		PLATFORM_DB: D1Database;
		SLUG_CACHE: KVNamespace;
		ANALYTICS: AnalyticsEngineDataset;
		ASSETS: Fetcher;

		PLATFORM_DOMAIN: string;
		OIDC_ISSUER: string;

		COOKIE_SESSION_SECRET: string;
		OIDC_CLIENT_ID: string;
		OIDC_CLIENT_SECRET: string;
		SSO_MANAGEMENT_CLIENT_ID: string;
		SSO_MANAGEMENT_CLIENT_SECRET: string;
		CF_API_TOKEN: string;
		CF_ZONE_ID: string;
		CF_ACCOUNT_ID: string;
		POLAR_ACCESS_TOKEN: string;
		POLAR_WEBHOOK_SECRET?: string;
		POLAR_PRODUCT_ID: string;
	}
}
