/**
 * Root Vite+ configuration: the single place formatting, linting and type checking are
 * configured for every workspace. Ported from `.oxlintrc.json` and `.oxfmtrc.json`, which
 * it replaces, so `vp check` runs all three as one pass instead of three separate tools
 * with no shared cache.
 *
 * Per-package settings belong in `lint.overrides` / `fmt.overrides` here rather than in a
 * config file next to the package, so there is one file to read to know how any file in
 * the repo is checked.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */
import { defineConfig } from "vite-plus";

import { cloudflareWorkersStub } from "./test/cloudflare-workers-plugin";

export default defineConfig({
	test: {
		projects: [
			{
				// Rooted at the app so its own tsconfig — and therefore the `~/*` aliases and
				// `jsxImportSource` — apply, which a root-rooted run cannot see.
				root: "apps/uptime",
				plugins: [cloudflareWorkersStub()],
				resolve: { tsconfigPaths: true },
				test: {
					name: "uptime",
					// ADR-035 phase 2 pilot: only the converted files run under Vitest so far.
					include: [
						"app/lib/uptime-report.test.ts",
						"app/lib/concurrency.test.ts",
						"app/http/controllers/healthcheck-analytics-engine.test.ts",
						"app/lib/container.test.ts",
						"app/lib/cost-rates.test.ts",
						"app/lib/cron-text.test.ts",
						"app/lib/dns-record-value.test.ts",
						"app/lib/monitor-scope.test.ts",
						"app/lib/notify-queue.test.ts",
						"app/lib/pricing.test.ts",
						"app/lib/retention.test.ts",
						"app/lib/timezones.test.ts",
						"app/lib/trial-history.test.ts",
						"app/lib/trial-identity.test.ts",
						"app/do/geo-fetch.test.ts",
						"resources/components/app-toaster.test.ts",
						"resources/components/run-monitor-button.test.ts",
						"resources/layouts/app-shell.test.tsx",
						"resources/layouts/document.test.tsx",
						"resources/views/dns-monitors/form.test.tsx",
						"resources/views/monitors/form.test.tsx",
						"app/http/middleware/attribution.test.ts",
						"app/http/middleware/auth.test.ts",
						"app/http/middleware/i18n.test.ts",
						"app/http/middleware/require-api-key.test.ts",
						"app/http/middleware/require-role.test.ts",
						"app/http/middleware/require-team.test.ts",
						"app/http/middleware/require-user.test.ts",
						"app/http/middleware/session.test.ts",
						"app/data/account-deletion.test.ts",
						"app/data/alert-event.test.ts",
						"app/data/alert.test.ts",
						"app/data/api-key.test.ts",
						"app/data/content-check.test.ts",
						"app/data/cron-job.test.ts",
						"app/data/customer.test.ts",
						"app/data/dns-monitor-record.test.ts",
						"app/data/dns-monitor.test.ts",
						"app/data/invite.test.ts",
						"app/data/maintenance-window.test.ts",
						"app/data/monitor-daily-stats.test.ts",
						"app/data/status-page.test.ts",
						"app/data/subscription.test.ts",
						"app/data/team-domain.test.ts",
						"app/data/team.test.ts",
						"app/data/trial-daily-stats.test.ts",
						"app/http/controllers/default-handler.test.ts",
						"app/http/controllers/docs-index.test.ts",
						"app/http/controllers/healthcheck-analytics-engine-degraded.test.ts",
						"app/http/controllers/healthcheck.test.ts",
						"app/http/controllers/home.test.ts",
						"app/http/controllers/invite.test.ts",
						"app/http/controllers/logout.test.ts",
						"app/http/controllers/marketing-audience.test.ts",
						"app/http/controllers/marketing-comparison.test.ts",
						"app/http/controllers/marketing-feature.test.ts",
						"app/http/controllers/marketing-use-case.test.ts",
						"app/http/controllers/privacy.test.ts",
						"app/http/controllers/status-page.test.ts",
						"app/http/controllers/terms.test.ts",
						"app/http/controllers/app/index.test.ts",
						"app/http/controllers/app/team/account.test.ts",
						"app/http/controllers/app/team/dashboard-card-count.test.ts",
						"app/http/controllers/app/team/dashboard-card-slowest-endpoint.test.ts",
						"app/http/controllers/app/team/dashboard-card-uptime.test.ts",
						"app/http/controllers/app/team/dashboard-card-usage.test.ts",
						"app/http/controllers/app/team/dashboard-panel.test.ts",
						"app/http/controllers/app/team/dashboard-quick-ping-frame.test.ts",
						"app/http/controllers/app/team/dashboard-quick-ping.test.ts",
						"app/http/controllers/app/team/dashboard.test.ts",
						"app/http/controllers/app/team/index.test.ts",
						"app/http/controllers/app/team/settings.test.ts",
						"app/http/controllers/app/team/alert-edit.test.ts",
						"app/http/controllers/app/team/alert-history.test.ts",
						"app/http/controllers/app/team/alert-new.test.ts",
						"app/http/controllers/app/team/alerts.test.ts",
						"app/http/controllers/app/team/api-key-new.test.ts",
						"app/http/controllers/app/team/api-keys.test.ts",
						"app/http/controllers/app/team/checkout.test.ts",
						"app/http/controllers/app/team/cron-job-edit.test.ts",
						"app/http/controllers/app/team/cron-job-new.test.ts",
						"app/http/controllers/app/team/cron-job-show.test.ts",
						"app/http/controllers/app/team/cron-jobs.test.ts",
						"app/http/controllers/actions/api-keys.test.ts",
						"app/http/controllers/actions/content-checks.test.ts",
						"app/http/controllers/actions/cron-jobs.test.ts",
						"app/http/controllers/actions/dashboard.test.ts",
						"app/http/controllers/actions/dns-monitors.test.ts",
						"app/http/controllers/actions/flow-monitors.test.ts",
						"app/http/controllers/actions/invites.test.ts",
						"app/http/controllers/actions/maintenance-windows.test.ts",
						"app/http/controllers/actions/monitors-import.test.ts",
						"app/http/controllers/actions/ping.test.ts",
						"app/http/controllers/actions/ssl.test.ts",
						"app/http/controllers/actions/status-pages.test.ts",
						"app/http/controllers/actions/tcp-monitors.test.ts",
						"app/http/controllers/actions/team-domains.test.ts",
						"app/http/controllers/actions/team.test.ts",
						"app/http/controllers/app/team/dns-monitor-card-check-history.test.ts",
						"app/http/controllers/app/team/dns-monitor-card-results.test.ts",
						"app/http/controllers/app/team/dns-monitor-card-uptime-history.test.ts",
						"app/http/controllers/app/team/dns-monitor-edit.test.ts",
						"app/http/controllers/app/team/dns-monitor-new.test.ts",
						"app/http/controllers/app/team/dns-monitor-review.test.ts",
						"app/http/controllers/app/team/dns-monitor-show-frames.test.ts",
						"app/http/controllers/app/team/dns-monitor-show.test.ts",
						"app/http/controllers/app/team/dns-monitors.test.ts",
						"app/http/controllers/app/team/flow-monitor-card-results.test.ts",
						"app/http/controllers/app/team/flow-monitor-show.test.ts",
						"app/http/controllers/app/team/flow-monitors.test.ts",
						"app/http/controllers/api/alert.test.ts",
						"app/http/controllers/api/alerts.test.ts",
						"app/http/controllers/api/api-key.test.ts",
						"app/http/controllers/api/api-keys.test.ts",
						"app/http/controllers/api/backfill-daily-stats.test.ts",
						"app/http/controllers/api/cron-job-ping.test.ts",
						"app/http/controllers/api/cron-job.test.ts",
						"app/http/controllers/api/cron-jobs.test.ts",
						"app/http/controllers/api/dns-monitor-records.test.ts",
						"app/http/controllers/api/dns-monitor.test.ts",
						"app/http/controllers/api/dns-monitors.test.ts",
						"app/http/controllers/api/invite.test.ts",
						"app/http/controllers/api/invites.test.ts",
						"app/http/controllers/api/maintenance-window.test.ts",
						"app/http/controllers/api/maintenance.test.ts",
						"app/http/controllers/api/memberships.test.ts",
						"app/http/controllers/api/monitor-content-checks.test.ts",
						"app/http/controllers/api/monitor.test.ts",
						"app/http/controllers/api/monitors.test.ts",
						"app/http/controllers/api/ping.test.ts",
						"app/http/controllers/api/status-page.test.ts",
						"app/http/controllers/api/status-pages.test.ts",
						"app/http/controllers/api/status.test.ts",
						"app/http/controllers/api/tcp-monitor.test.ts",
						"app/http/controllers/api/tcp-monitors.test.ts",
						"app/http/controllers/api/team-domains.test.ts",
						"app/http/controllers/api/team.test.ts",
						"app/jobs/aggregate-daily-stats.test.ts",
						"app/jobs/check-cron-jobs.test.ts",
						"app/jobs/check-dns.test.ts",
						"app/jobs/check-http.test.ts",
						"app/jobs/check-ssl.test.ts",
						"app/jobs/check-tcp.test.ts",
						"app/jobs/clean-cron-job-pings.test.ts",
						"app/jobs/dead-letter.test.ts",
						"app/jobs/delete-accounts.test.ts",
						"app/jobs/notify.test.ts",
						"app/jobs/reconcile-subscriptions.test.ts",
						"app/jobs/report-costs.test.ts",
						"app/jobs/send-team-digests.test.ts",
						"app/http/controllers/trial/index.test.tsx",
						"app/http/controllers/trial/report.test.ts",
						"app/http/controllers/trial/unsubscribe.test.tsx",
						"app/http/controllers/webhooks/polar.test.ts",
						"app/services/account-erasure.test.ts",
						"app/services/account-export.test.ts",
						"app/services/adhoc-ping.test.ts",
						"app/services/analytics.test.ts",
						"app/services/api-key.test.ts",
						"app/services/api-response.test.ts",
						"app/services/cost.test.ts",
						"app/services/dns-check.test.ts",
						"app/services/dns-discovery.test.ts",
						"app/services/flow-check.test.ts",
						"app/services/funnel-events.test.ts",
						"app/services/http-check.test.ts",
						"app/services/ping-meter.test.ts",
						"app/services/ssl-info.test.ts",
						"app/services/status-page.test.ts",
						"app/services/subjects.test.ts",
						"app/services/tcp-check.test.ts",
						"app/services/trial-guard.test.ts",
						"app/http/controllers/app/team/http-monitors.test.ts",
						"app/http/controllers/app/team/maintenance-window-edit.test.ts",
						"app/http/controllers/app/team/maintenance-window-new.test.ts",
						"app/http/controllers/app/team/maintenance-windows.test.ts",
						"app/http/controllers/app/team/monitor-card-p99-response-time.test.ts",
						"app/http/controllers/app/team/monitor-card-slowest-result.test.ts",
						"app/http/controllers/app/team/monitor-card-uptime-history.test.ts",
						"app/http/controllers/app/team/monitor-card-uptime.test.ts",
						"app/http/controllers/app/team/monitor-card-usage.test.ts",
						"app/http/controllers/app/team/monitor-edit.test.ts",
						"app/http/controllers/app/team/monitor-new.test.ts",
						"app/http/controllers/app/team/monitor-run-status.test.ts",
						"app/http/controllers/app/team/monitor-show.test.ts",
						"app/http/controllers/app/team/monitors-import.test.ts",
						"app/http/controllers/app/team/status-page-edit.test.ts",
						"app/http/controllers/app/team/status-page-new.test.ts",
						"app/http/controllers/app/team/status-pages.test.ts",
						"app/http/controllers/app/team/tcp-monitor-card-results.test.ts",
						"app/http/controllers/app/team/tcp-monitor-card-uptime-history.test.ts",
						"app/http/controllers/app/team/tcp-monitor-edit.test.ts",
						"app/http/controllers/app/team/tcp-monitor-new.test.ts",
						"app/http/controllers/app/team/tcp-monitor-show.test.ts",
						"app/http/controllers/app/team/tcp-monitors.test.ts",
						"app/data/monitor.test.ts",
						"app/data/tcp-monitor.test.ts",
						"database/migrations/20260802120000_trial_watch_cap.test.ts",
						"database/migrations/20260811100000_alert_monitor_scope.test.ts",
						"database/migrations/20260811110000_maintenance_monitor_scope.test.ts",
						"app/data/lead.test.ts",
						"app/data/team-digest.test.ts",
						"app/data/trial-conversion.test.ts",
						"app/data/trial-watch.test.ts",
						"app/data/user-preferences.test.ts",
						"app/auth/value-objects/id-token.test.ts",
						"app/auth/services/oauth.test.ts",
						"app/services/docs.test.ts",
						"app/emails/account-deleted.test.tsx",
						"app/emails/alert.test.tsx",
						"app/emails/funnel-report.test.tsx",
						"app/emails/locale.test.ts",
						"app/emails/shared/uptime-bar.test.tsx",
						"app/emails/team-daily-digest.test.tsx",
						"app/emails/team-deleted.test.tsx",
						"app/emails/team-invite.test.tsx",
						"app/emails/team-weekly-digest.test.tsx",
						"app/emails/trial-change.test.tsx",
						"app/emails/trial-confirmation.test.tsx",
						"app/emails/trial-daily-digest.test.tsx",
						"app/emails/trial-repeat-report.test.tsx",
						"app/emails/trial-weekly-digest.test.tsx",
						"app/jobs/check-trial-watches.test.ts",
						"app/jobs/clean.test.ts",
						"app/jobs/enqueue-pending-domains.test.ts",
						"app/jobs/send-funnel-report.test.ts",
						"app/jobs/send-trial-digests.test.ts",
						"app/jobs/verify-domain-ownership.test.ts",
						"app/lib/public-claims.test.ts",
						"app/http/controllers/docs-show.test.ts",
						"app/http/controllers/sitemap.test.ts",
						"app/http/controllers/trust.test.ts",
						"resources/components/range-slider.test.tsx",
						"resources/components/stepper-field.test.tsx",
						"app/http/validators/account.test.ts",
						"app/http/validators/alert.test.ts",
						"app/http/validators/api-key.test.ts",
						"app/http/validators/content-check.test.ts",
						"app/http/validators/cron-job.test.ts",
						"app/http/validators/dns-monitor.test.ts",
						"app/http/validators/invite.test.ts",
						"app/http/validators/language.test.ts",
						"app/http/validators/maintenance-window.test.ts",
						"app/http/validators/monitor-import.test.ts",
						"app/http/validators/monitor.test.ts",
						"app/http/validators/ssl.test.ts",
						"app/http/validators/status-page.test.ts",
						"app/http/validators/tcp-monitor.test.ts",
						"app/http/validators/team-domain.test.ts",
						"app/http/validators/team.test.ts",
						"app/http/cookies.test.ts",
						"app/http/render.test.tsx",
						"app/services/alerts.test.ts",
						"app/lib/trial-report.test.ts",
						"app/services/id-token-verification-key.test.ts",
						"app/services/trial-conversion.test.ts",
						"app/services/zone-file.test.ts",
						"app/http/controllers/auth.test.ts",
						"app/http/controllers/actions/account.test.ts",
						"app/http/controllers/actions/alerts.test.ts",
						"app/http/controllers/actions/monitors.test.ts",
						"app/http/controllers/trial/lead.test.ts",
					],
					pool: "threads",
				},
			},
		],
	},

	fmt: {
		// Vendored third-party content. Oxfmt reformats fenced code inside markdown, which
		// would rewrite 600+ files nobody here authored and make the next vendor sync a
		// conflict; they are read, not maintained.
		ignorePatterns: [".agents/**", "docs/vendor/**"],
		useTabs: true,
		experimentalSortPackageJson: true,
		experimentalSortImports: {
			groups: [
				["value-builtin"],
				["type-external"],
				["value-external"],
				["type-internal"],
				["value-internal"],
				["type-parent"],
				["value-parent"],
				["type-sibling"],
				["value-sibling"],
				["type-index"],
				["value-index"],
				["side_effect"],
			],
		},
	},

	lint: {
		options: {
			typeAware: true,
			typeCheck: true,
			denyWarnings: true,
		},
		plugins: [
			"eslint",
			"import",
			"jsdoc",
			"jsx-a11y",
			"node",
			"oxc",
			"promise",
			"typescript",
			"unicorn",
		],
		categories: {},
		rules: {
			"jsx_a11y/control-has-associated-label": "allow",
			"jsx_a11y/no-noninteractive-element-interactions": "allow",
			"jsx_a11y/prefer-tag-over-role": "allow",
		},
		settings: {
			"jsx-a11y": {
				components: {
					Input: "input",
					Select: "select",
					Button: "button",
				},
			},
		},
		env: { builtin: true },
		globals: {},
		overrides: [
			{
				// These components render an anchor, image or label whose content, `alt` text and
				// associated control are supplied by the caller, so the rules cannot see them
				// here. Ported from the package's own `.oxlintrc.json`, which this replaces.
				files: ["packages/ui/**"],
				rules: {
					"jsx_a11y/anchor-has-content": "allow",
					"jsx_a11y/alt-text": "allow",
					"jsx_a11y/label-has-associated-control": "allow",
				},
			},
		],
	},
});
