/**
 * Custom environment variables that are not auto-generated by wrangler.
 * These are secrets or vars that need to be set in production.
 */
declare namespace Cloudflare {
	interface Env {
		// Secrets (set via wrangler secret)
		RESEND_API_KEY: string;
		POLAR_ACCESS_TOKEN: string;
		POLAR_PRODUCT_ID: string;
		CF_API_TOKEN: string;
		CF_ZONE_ID: string;
		CF_ACCOUNT_ID: string;

		// Vars (set in wrangler.jsonc)
		PLATFORM_DOMAIN: string;
		EMAIL_FROM: string;

		// Analytics Engine
		ANALYTICS: AnalyticsEngineDataset;
	}
}
