/**
 * Regenerates `src/common-passwords.data.ts` from SecLists' NCSC top-100,000 list at a
 * pinned commit, folded the way the check folds a candidate and trimmed to entries a
 * NIST-compliant length floor can reach. Run `bun run update-common-passwords [ref]`, where
 * `ref` is a SecLists commit, branch or tag (default `master`).
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { join } from "node:path";

import type { Result } from "@sdxc/result";

import { failure, isFailure, success } from "@sdxc/result";
import { $ } from "bun";

import { countCodePoints, foldPassword } from "../src/normalize.js";

/** The repository the list and its license are read from. */
const REPOSITORY = "danielmiessler/SecLists";

/** The list inside that repository: the top 100,000 Pwned Passwords the UK NCSC published. */
const LIST_PATH = "Passwords/Common-Credentials/100k-most-used-passwords-NCSC.txt";

/**
 * Shortest entry kept. NIST SP 800-63B never permits a password under 8 characters, so
 * a shorter entry is refused by the length check before the list is ever consulted.
 */
const MIN_ENTRY_LENGTH = 8;

/** The monorepo root, whose `vite.config.ts` the generated module is formatted by. */
const ROOT_DIR = join(import.meta.dir, "..", "..", "..");

/** Where the generated module is written. */
const OUTPUT_PATH = join(import.meta.dir, "..", "src", "common-passwords.data.ts");

/**
 * Fetches a URL's body as text, reporting a non-OK status as a failure so the script
 * never writes a module built from an error page.
 */
async function fetchText(url: string, accept?: string): Promise<Result<string, Error>> {
	let response = await fetch(url, {
		headers: { "User-Agent": "@sdxc/password-policy", ...(accept ? { Accept: accept } : {}) },
	});
	if (!response.ok) return failure(new Error(`${url} answered ${response.status}`));
	return success(await response.text());
}

/**
 * Folds, filters and de-duplicates the raw list, keeping the source's frequency order so
 * the generated module reads most-common first.
 */
function prepareEntries(raw: string): string[] {
	let entries = new Set<string>();

	for (let line of raw.split(/\r?\n/)) {
		let folded = foldPassword(line);
		if (countCodePoints(folded) < MIN_ENTRY_LENGTH) continue;
		entries.add(folded);
	}

	return [...entries];
}

/**
 * Writes a value as a template literal, one line per source line, so a refresh reads as
 * a line-per-entry diff. Escapes are the ones a template literal would otherwise interpret.
 */
function templateLiteral(value: string): string {
	let escaped = value
		.replaceAll("\\", "\\\\")
		.replaceAll("`", "\\`")
		.replaceAll("${", "\\${")
		// oxlint-disable-next-line no-control-regex -- control characters are exactly what this escapes
		.replace(/[\u0000-\u0009\u000B-\u001F\u007F-\u009F]/g, (character) => {
			return `\\u${character.charCodeAt(0).toString(16).padStart(4, "0")}`;
		});

	return `\`${escaped}\``;
}

/** Renders the generated module; the header records provenance and the refresh command. */
function renderModule(input: {
	commit: string;
	date: string;
	entries: string[];
	license: string;
}): string {
	let source = `https://github.com/${REPOSITORY}/blob/${input.commit}/${LIST_PATH}`;

	return [
		"/**",
		` * Generated by scripts/update-common-passwords.ts on ${input.date}. Source: ${source}`,
		` * (SecLists, MIT, Copyright (c) 2018 Daniel Miessler; full notice below). ${input.entries.length} entries,`,
		` * folded with NFKC + lowercase, entries under ${MIN_ENTRY_LENGTH} code points dropped.`,
		" * Refresh: `bun run update-common-passwords [ref]` in packages/password-policy (default ref master).",
		" *",
		" * @author [Sergio Xalambrí](https://sergiodxa.com)",
		" * @copyright Sergio Xalambrí 2026",
		" */",
		"",
		"/** The SecLists license, carried with the list as its MIT terms require. */",
		`export const COMMON_PASSWORDS_NOTICE: string = ${templateLiteral(input.license.trim())};`,
		"",
		"/** Shortest entry the list holds; a shorter candidate is never matched against it. */",
		`export const COMMON_PASSWORDS_MIN_LENGTH = ${MIN_ENTRY_LENGTH};`,
		"",
		"/** Newline-separated folded entries, split into a set only on first lookup. */",
		`export const COMMON_PASSWORDS: string = ${templateLiteral(input.entries.join("\n"))};`,
		"",
	].join("\n");
}

/** Resolves the ref to a commit, downloads the list and license there, and writes the module. */
async function main(): Promise<Result<string, Error>> {
	let ref = process.argv[2] ?? "master";

	let commit = await fetchText(
		`https://api.github.com/repos/${REPOSITORY}/commits/${ref}`,
		"application/vnd.github.sha",
	);
	if (isFailure(commit)) return commit;

	let raw = `https://raw.githubusercontent.com/${REPOSITORY}/${commit.data.trim()}`;
	let list = await fetchText(`${raw}/${LIST_PATH}`);
	if (isFailure(list)) return list;

	let license = await fetchText(`${raw}/LICENSE`);
	if (isFailure(license)) return license;

	let entries = prepareEntries(list.data);
	let date = new Date().toISOString().slice(0, 10);
	let module = renderModule({ commit: commit.data.trim(), date, entries, license: license.data });

	await Bun.write(OUTPUT_PATH, module);
	await $`bunx vp fmt ${OUTPUT_PATH}`.cwd(ROOT_DIR).quiet();
	return success(
		`Wrote ${entries.length} entries (${new TextEncoder().encode(module).byteLength} bytes) at ${commit.data}\n`,
	);
}

const RESULT = await main();

if (isFailure(RESULT)) {
	process.stderr.write(`${RESULT.error.message}\n`);
	process.exitCode = 1;
} else {
	process.stdout.write(RESULT.data);
}
