/**
 * Codegen script that reads Lucide's framework-agnostic icon data from
 * `lucide-static` and emits `src/registry.ts` (one named export per icon's
 * raw node data), `src/icon-names.ts` (the kebab-case name -> registry export
 * name lookup), one `remix/ui` component module per icon under `src/icons/`,
 * and the barrel `src/index.ts` that re-exports all of them.
 * Re-run with `bun run generate` whenever `lucide-static` is upgraded.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import iconNodes from "lucide-static/icon-nodes.json" with { type: "json" };

/** A single Lucide icon's `[tag, attrs]` tuples, as shaped by `lucide-static`'s JSON data. */
type RawIconNode = ReadonlyArray<readonly [string, Record<string, string>]>;

/** Identifiers that are reserved words in JS modules, so can't be used as an `export const` name (e.g. the `"delete"` icon). */
const RESERVED_EXPORT_NAMES = new Set([
	"break",
	"case",
	"catch",
	"class",
	"const",
	"continue",
	"debugger",
	"default",
	"delete",
	"do",
	"else",
	"export",
	"extends",
	"false",
	"finally",
	"for",
	"function",
	"if",
	"import",
	"in",
	"instanceof",
	"new",
	"null",
	"return",
	"super",
	"switch",
	"this",
	"throw",
	"true",
	"try",
	"typeof",
	"var",
	"void",
	"while",
	"with",
	"yield",
	"let",
	"static",
	"enum",
	"await",
	"implements",
	"package",
	"protected",
	"interface",
	"private",
	"public",
]);

const PACKAGE_ROOT = path.resolve(import.meta.dirname, "..");
const ICONS_DIR = path.join(PACKAGE_ROOT, "src", "icons");
const INDEX_FILE = path.join(PACKAGE_ROOT, "src", "index.ts");
const REGISTRY_FILE = path.join(PACKAGE_ROOT, "src", "registry.ts");
const ICON_NAMES_FILE = path.join(PACKAGE_ROOT, "src", "icon-names.ts");
const FILE_HEADER = `/**
 * Generated by \`bun run generate\` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */
`;

/** Converts a kebab-case icon name (e.g. `"circle-alert"`) into PascalCase (e.g. `"CircleAlert"`). */
function toPascalCase(iconName: string) {
	return iconName
		.split("-")
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
}

/** Converts a kebab-case icon name (e.g. `"circle-alert"`) into camelCase (e.g. `"circleAlert"`). */
function toCamelCase(iconName: string) {
	let pascal = toPascalCase(iconName);
	return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * The valid `registry.ts` export name for an icon's camelCase name, renamed
 * with a `Node` suffix when it would otherwise collide with a JS reserved
 * word (e.g. the `"delete"` and `"import"` icons).
 */
function toRegistryExportName(iconName: string) {
	let camel = toCamelCase(iconName);
	return RESERVED_EXPORT_NAMES.has(camel) ? `${camel}Node` : camel;
}

/** Renders an icon's `[tag, attrs]` tuples as a TypeScript array literal. */
function renderIconNode(iconNode: RawIconNode) {
	let entries = iconNode.map(
		([tag, attrs]) => `\t[${JSON.stringify(tag)}, ${JSON.stringify(attrs)}]`,
	);
	return `[\n${entries.join(",\n")},\n]`;
}

/** Removes and recreates the generated `src/icons/` directory. */
async function resetIconsDir() {
	await rm(ICONS_DIR, { recursive: true, force: true });
	await mkdir(ICONS_DIR, { recursive: true });
}

/**
 * Writes `src/registry.ts`: one named export per icon holding its raw node
 * data, so `<Icon />` can look up any icon by its converted name while each
 * `src/icons/<name>.ts` module imports only the one constant it needs for tree-shaking.
 */
async function writeRegistryFile(iconNames: string[]) {
	let entries = iconNames
		.map((iconName) => {
			let node = iconNodes[iconName as keyof typeof iconNodes] as unknown as RawIconNode;
			return `export const ${toRegistryExportName(iconName)} = ${renderIconNode(node)} satisfies IconNode;`;
		})
		.join("\n\n");
	let content = `${FILE_HEADER}
import type { IconNode } from "./create-lucide-icon.js";

${entries}
`;
	await writeFile(REGISTRY_FILE, content);
}

/**
 * Writes `src/icon-names.ts`: a compile-time-checked map from each icon's
 * public kebab-case name to its `registry.ts` export name (identifiers can't
 * contain hyphens), plus the `IconName` union used to typecheck `<Icon name />`.
 */
async function writeIconNamesFile(iconNames: string[]) {
	let entries = iconNames
		.map(
			(iconName) =>
				`\t${JSON.stringify(iconName)}: ${JSON.stringify(toRegistryExportName(iconName))},`,
		)
		.join("\n");
	let content = `${FILE_HEADER}
/** Maps each Lucide icon's public kebab-case name to its export name in \`registry.ts\`. */
export const iconExportNames = {
${entries}
} as const;

/** Every valid \`name\` accepted by \`<Icon />\`, matching Lucide's icon catalog (https://lucide.dev/icons/). */
export type IconName = keyof typeof iconExportNames;
`;
	await writeFile(ICON_NAMES_FILE, content);
}

/** Writes the per-icon module for a single Lucide icon, importing its data from `registry.ts`. */
async function writeIconFile(iconName: string) {
	let exportName = `${toPascalCase(iconName)}Icon`;
	let registryExportName = toRegistryExportName(iconName);
	let content = `${FILE_HEADER}
import { createLucideIcon } from "../create-lucide-icon.js";
import { ${registryExportName} } from "../registry.js";

/** Renders the ${JSON.stringify(iconName)} icon from https://lucide.dev/icons/${iconName}. */
export const ${exportName} = createLucideIcon(${JSON.stringify(iconName)}, ${registryExportName});
`;
	await writeFile(path.join(ICONS_DIR, `${iconName}.ts`), content);
}

/** Writes the barrel file re-exporting the factory, its types, every generated icon, and `<Icon />`. */
async function writeIndexFile(iconNames: string[]) {
	let reExports = iconNames.map((iconName) => `export * from "./icons/${iconName}.js";`).join("\n");
	let content = `/**
 * Public entry point for \`@pkg/icons\` — Lucide icons
 * (https://lucide.dev) as \`remix/ui\` components, one module per icon so
 * bundlers can tree-shake unused ones, matching \`lucide-react\`'s package
 * shape.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

export { createLucideIcon } from "./create-lucide-icon.js";
export type { IconNode, LucideProps } from "./create-lucide-icon.js";

export { Icon } from "./icon.js";
export type { IconProps } from "./icon.js";

export { iconExportNames } from "./icon-names.js";
export type { IconName } from "./icon-names.js";

${reExports}
`;
	await writeFile(INDEX_FILE, content);
}

async function main() {
	await resetIconsDir();

	let iconNames = Object.keys(iconNodes).sort();

	await writeRegistryFile(iconNames);
	await writeIconNamesFile(iconNames);

	for (let iconName of iconNames) {
		await writeIconFile(iconName);
	}

	await writeIndexFile(iconNames);

	let written = await readdir(ICONS_DIR);
	console.log(`Generated ${written.length} icons into ${path.relative(PACKAGE_ROOT, ICONS_DIR)}`);
}

await main();
