/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { aArrowUp } from "../registry.js";

/** Renders the "a-arrow-up" icon from https://lucide.dev/icons/a-arrow-up. */
export const AArrowUpIcon = createLucideIcon("a-arrow-up", aArrowUp);
