/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { activity } from "../registry.js";

/** Renders the "activity" icon from https://lucide.dev/icons/activity. */
export const ActivityIcon = createLucideIcon("activity", activity);
