/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { airVent } from "../registry.js";

/** Renders the "air-vent" icon from https://lucide.dev/icons/air-vent. */
export const AirVentIcon = createLucideIcon("air-vent", airVent);
