/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alarmClockOff } from "../registry.js";

/** Renders the "alarm-clock-off" icon from https://lucide.dev/icons/alarm-clock-off. */
export const AlarmClockOffIcon = createLucideIcon("alarm-clock-off", alarmClockOff);
