/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alarmSmoke } from "../registry.js";

/** Renders the "alarm-smoke" icon from https://lucide.dev/icons/alarm-smoke. */
export const AlarmSmokeIcon = createLucideIcon("alarm-smoke", alarmSmoke);
