/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignStartHorizontal } from "../registry.js";

/** Renders the "align-start-horizontal" icon from https://lucide.dev/icons/align-start-horizontal. */
export const AlignStartHorizontalIcon = createLucideIcon(
	"align-start-horizontal",
	alignStartHorizontal,
);
