/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignHorizontalSpaceBetween } from "../registry.js";

/** Renders the "align-horizontal-space-between" icon from https://lucide.dev/icons/align-horizontal-space-between. */
export const AlignHorizontalSpaceBetweenIcon = createLucideIcon(
	"align-horizontal-space-between",
	alignHorizontalSpaceBetween,
);
