/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignHorizontalDistributeCenter } from "../registry.js";

/** Renders the "align-horizontal-distribute-center" icon from https://lucide.dev/icons/align-horizontal-distribute-center. */
export const AlignHorizontalDistributeCenterIcon = createLucideIcon(
	"align-horizontal-distribute-center",
	alignHorizontalDistributeCenter,
);
