/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignVerticalSpaceAround } from "../registry.js";

/** Renders the "align-vertical-space-around" icon from https://lucide.dev/icons/align-vertical-space-around. */
export const AlignVerticalSpaceAroundIcon = createLucideIcon(
	"align-vertical-space-around",
	alignVerticalSpaceAround,
);
