/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignHorizontalDistributeStart } from "../registry.js";

/** Renders the "align-horizontal-distribute-start" icon from https://lucide.dev/icons/align-horizontal-distribute-start. */
export const AlignHorizontalDistributeStartIcon = createLucideIcon(
	"align-horizontal-distribute-start",
	alignHorizontalDistributeStart,
);
