/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignEndVertical } from "../registry.js";

/** Renders the "align-end-vertical" icon from https://lucide.dev/icons/align-end-vertical. */
export const AlignEndVerticalIcon = createLucideIcon("align-end-vertical", alignEndVertical);
