/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ampersands } from "../registry.js";

/** Renders the "ampersands" icon from https://lucide.dev/icons/ampersands. */
export const AmpersandsIcon = createLucideIcon("ampersands", ampersands);
