/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { anchor } from "../registry.js";

/** Renders the "anchor" icon from https://lucide.dev/icons/anchor. */
export const AnchorIcon = createLucideIcon("anchor", anchor);
