/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { archiveX } from "../registry.js";

/** Renders the "archive-x" icon from https://lucide.dev/icons/archive-x. */
export const ArchiveXIcon = createLucideIcon("archive-x", archiveX);
