/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { archiveRestore } from "../registry.js";

/** Renders the "archive-restore" icon from https://lucide.dev/icons/archive-restore. */
export const ArchiveRestoreIcon = createLucideIcon("archive-restore", archiveRestore);
