/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowDownAZ } from "../registry.js";

/** Renders the "arrow-down-a-z" icon from https://lucide.dev/icons/arrow-down-a-z. */
export const ArrowDownAZIcon = createLucideIcon("arrow-down-a-z", arrowDownAZ);
