/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowDownToDot } from "../registry.js";

/** Renders the "arrow-down-to-dot" icon from https://lucide.dev/icons/arrow-down-to-dot. */
export const ArrowDownToDotIcon = createLucideIcon("arrow-down-to-dot", arrowDownToDot);
