/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowLeftRight } from "../registry.js";

/** Renders the "arrow-left-right" icon from https://lucide.dev/icons/arrow-left-right. */
export const ArrowLeftRightIcon = createLucideIcon("arrow-left-right", arrowLeftRight);
