/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowUpRight } from "../registry.js";

/** Renders the "arrow-up-right" icon from https://lucide.dev/icons/arrow-up-right. */
export const ArrowUpRightIcon = createLucideIcon("arrow-up-right", arrowUpRight);
