/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowBigDown } from "../registry.js";

/** Renders the "arrow-big-down" icon from https://lucide.dev/icons/arrow-big-down. */
export const ArrowBigDownIcon = createLucideIcon("arrow-big-down", arrowBigDown);
