/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowBigRightDash } from "../registry.js";

/** Renders the "arrow-big-right-dash" icon from https://lucide.dev/icons/arrow-big-right-dash. */
export const ArrowBigRightDashIcon = createLucideIcon("arrow-big-right-dash", arrowBigRightDash);
