/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowRightFromLine } from "../registry.js";

/** Renders the "arrow-right-from-line" icon from https://lucide.dev/icons/arrow-right-from-line. */
export const ArrowRightFromLineIcon = createLucideIcon("arrow-right-from-line", arrowRightFromLine);
