/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowDownFromLine } from "../registry.js";

/** Renders the "arrow-down-from-line" icon from https://lucide.dev/icons/arrow-down-from-line. */
export const ArrowDownFromLineIcon = createLucideIcon("arrow-down-from-line", arrowDownFromLine);
