/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowLeftToLine } from "../registry.js";

/** Renders the "arrow-left-to-line" icon from https://lucide.dev/icons/arrow-left-to-line. */
export const ArrowLeftToLineIcon = createLucideIcon("arrow-left-to-line", arrowLeftToLine);
