/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowUpFromDot } from "../registry.js";

/** Renders the "arrow-up-from-dot" icon from https://lucide.dev/icons/arrow-up-from-dot. */
export const ArrowUpFromDotIcon = createLucideIcon("arrow-up-from-dot", arrowUpFromDot);
