/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowBigUpDash } from "../registry.js";

/** Renders the "arrow-big-up-dash" icon from https://lucide.dev/icons/arrow-big-up-dash. */
export const ArrowBigUpDashIcon = createLucideIcon("arrow-big-up-dash", arrowBigUpDash);
