/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowUp10 } from "../registry.js";

/** Renders the "arrow-up-1-0" icon from https://lucide.dev/icons/arrow-up-1-0. */
export const ArrowUp10Icon = createLucideIcon("arrow-up-1-0", arrowUp10);
