/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { axis3d } from "../registry.js";

/** Renders the "axis-3d" icon from https://lucide.dev/icons/axis-3d. */
export const Axis3dIcon = createLucideIcon("axis-3d", axis3d);
