/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { baby } from "../registry.js";

/** Renders the "baby" icon from https://lucide.dev/icons/baby. */
export const BabyIcon = createLucideIcon("baby", baby);
