/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { badgeQuestionMark } from "../registry.js";

/** Renders the "badge-question-mark" icon from https://lucide.dev/icons/badge-question-mark. */
export const BadgeQuestionMarkIcon = createLucideIcon("badge-question-mark", badgeQuestionMark);
