/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { badgeTurkishLira } from "../registry.js";

/** Renders the "badge-turkish-lira" icon from https://lucide.dev/icons/badge-turkish-lira. */
export const BadgeTurkishLiraIcon = createLucideIcon("badge-turkish-lira", badgeTurkishLira);
