/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { badgePoundSterling } from "../registry.js";

/** Renders the "badge-pound-sterling" icon from https://lucide.dev/icons/badge-pound-sterling. */
export const BadgePoundSterlingIcon = createLucideIcon("badge-pound-sterling", badgePoundSterling);
