/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { badgeEuro } from "../registry.js";

/** Renders the "badge-euro" icon from https://lucide.dev/icons/badge-euro. */
export const BadgeEuroIcon = createLucideIcon("badge-euro", badgeEuro);
