/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { badgeInfo } from "../registry.js";

/** Renders the "badge-info" icon from https://lucide.dev/icons/badge-info. */
export const BadgeInfoIcon = createLucideIcon("badge-info", badgeInfo);
