/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { banana } from "../registry.js";

/** Renders the "banana" icon from https://lucide.dev/icons/banana. */
export const BananaIcon = createLucideIcon("banana", banana);
