/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { banknoteArrowUp } from "../registry.js";

/** Renders the "banknote-arrow-up" icon from https://lucide.dev/icons/banknote-arrow-up. */
export const BanknoteArrowUpIcon = createLucideIcon("banknote-arrow-up", banknoteArrowUp);
