/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { banknoteCheck } from "../registry.js";

/** Renders the "banknote-check" icon from https://lucide.dev/icons/banknote-check. */
export const BanknoteCheckIcon = createLucideIcon("banknote-check", banknoteCheck);
