/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { batteryWarning } from "../registry.js";

/** Renders the "battery-warning" icon from https://lucide.dev/icons/battery-warning. */
export const BatteryWarningIcon = createLucideIcon("battery-warning", batteryWarning);
