/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { beaker } from "../registry.js";

/** Renders the "beaker" icon from https://lucide.dev/icons/beaker. */
export const BeakerIcon = createLucideIcon("beaker", beaker);
