/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bedSingle } from "../registry.js";

/** Renders the "bed-single" icon from https://lucide.dev/icons/bed-single. */
export const BedSingleIcon = createLucideIcon("bed-single", bedSingle);
