/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bedDouble } from "../registry.js";

/** Renders the "bed-double" icon from https://lucide.dev/icons/bed-double. */
export const BedDoubleIcon = createLucideIcon("bed-double", bedDouble);
