/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { beefOff } from "../registry.js";

/** Renders the "beef-off" icon from https://lucide.dev/icons/beef-off. */
export const BeefOffIcon = createLucideIcon("beef-off", beefOff);
