/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { beer } from "../registry.js";

/** Renders the "beer" icon from https://lucide.dev/icons/beer. */
export const BeerIcon = createLucideIcon("beer", beer);
