/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bellRing } from "../registry.js";

/** Renders the "bell-ring" icon from https://lucide.dev/icons/bell-ring. */
export const BellRingIcon = createLucideIcon("bell-ring", bellRing);
