/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bellElectric } from "../registry.js";

/** Renders the "bell-electric" icon from https://lucide.dev/icons/bell-electric. */
export const BellElectricIcon = createLucideIcon("bell-electric", bellElectric);
