/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { betweenVerticalEnd } from "../registry.js";

/** Renders the "between-vertical-end" icon from https://lucide.dev/icons/between-vertical-end. */
export const BetweenVerticalEndIcon = createLucideIcon("between-vertical-end", betweenVerticalEnd);
