/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { binary } from "../registry.js";

/** Renders the "binary" icon from https://lucide.dev/icons/binary. */
export const BinaryIcon = createLucideIcon("binary", binary);
