/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { biohazard } from "../registry.js";

/** Renders the "biohazard" icon from https://lucide.dev/icons/biohazard. */
export const BiohazardIcon = createLucideIcon("biohazard", biohazard);
