/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bird } from "../registry.js";

/** Renders the "bird" icon from https://lucide.dev/icons/bird. */
export const BirdIcon = createLucideIcon("bird", bird);
