/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { blender } from "../registry.js";

/** Renders the "blender" icon from https://lucide.dev/icons/blender. */
export const BlenderIcon = createLucideIcon("blender", blender);
