/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bluetoothSearching } from "../registry.js";

/** Renders the "bluetooth-searching" icon from https://lucide.dev/icons/bluetooth-searching. */
export const BluetoothSearchingIcon = createLucideIcon("bluetooth-searching", bluetoothSearching);
