/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bomb } from "../registry.js";

/** Renders the "bomb" icon from https://lucide.dev/icons/bomb. */
export const BombIcon = createLucideIcon("bomb", bomb);
