/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { boneFracture } from "../registry.js";

/** Renders the "bone-fracture" icon from https://lucide.dev/icons/bone-fracture. */
export const BoneFractureIcon = createLucideIcon("bone-fracture", boneFracture);
