/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookOpenText } from "../registry.js";

/** Renders the "book-open-text" icon from https://lucide.dev/icons/book-open-text. */
export const BookOpenTextIcon = createLucideIcon("book-open-text", bookOpenText);
