/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookText } from "../registry.js";

/** Renders the "book-text" icon from https://lucide.dev/icons/book-text. */
export const BookTextIcon = createLucideIcon("book-text", bookText);
