/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookKey } from "../registry.js";

/** Renders the "book-key" icon from https://lucide.dev/icons/book-key. */
export const BookKeyIcon = createLucideIcon("book-key", bookKey);
