/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookUser } from "../registry.js";

/** Renders the "book-user" icon from https://lucide.dev/icons/book-user. */
export const BookUserIcon = createLucideIcon("book-user", bookUser);
