/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookmark } from "../registry.js";

/** Renders the "bookmark" icon from https://lucide.dev/icons/bookmark. */
export const BookmarkIcon = createLucideIcon("bookmark", bookmark);
