/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookSearch } from "../registry.js";

/** Renders the "book-search" icon from https://lucide.dev/icons/book-search. */
export const BookSearchIcon = createLucideIcon("book-search", bookSearch);
