/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookImage } from "../registry.js";

/** Renders the "book-image" icon from https://lucide.dev/icons/book-image. */
export const BookImageIcon = createLucideIcon("book-image", bookImage);
