/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookAlert } from "../registry.js";

/** Renders the "book-alert" icon from https://lucide.dev/icons/book-alert. */
export const BookAlertIcon = createLucideIcon("book-alert", bookAlert);
