/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookMinus } from "../registry.js";

/** Renders the "book-minus" icon from https://lucide.dev/icons/book-minus. */
export const BookMinusIcon = createLucideIcon("book-minus", bookMinus);
