/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookHeadphones } from "../registry.js";

/** Renders the "book-headphones" icon from https://lucide.dev/icons/book-headphones. */
export const BookHeadphonesIcon = createLucideIcon("book-headphones", bookHeadphones);
