/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookUp2 } from "../registry.js";

/** Renders the "book-up-2" icon from https://lucide.dev/icons/book-up-2. */
export const BookUp2Icon = createLucideIcon("book-up-2", bookUp2);
