/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookLock } from "../registry.js";

/** Renders the "book-lock" icon from https://lucide.dev/icons/book-lock. */
export const BookLockIcon = createLucideIcon("book-lock", bookLock);
