/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookmarkCheck } from "../registry.js";

/** Renders the "bookmark-check" icon from https://lucide.dev/icons/bookmark-check. */
export const BookmarkCheckIcon = createLucideIcon("bookmark-check", bookmarkCheck);
