/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookPlus } from "../registry.js";

/** Renders the "book-plus" icon from https://lucide.dev/icons/book-plus. */
export const BookPlusIcon = createLucideIcon("book-plus", bookPlus);
