/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { boomBox } from "../registry.js";

/** Renders the "boom-box" icon from https://lucide.dev/icons/boom-box. */
export const BoomBoxIcon = createLucideIcon("boom-box", boomBox);
