/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { botMessageSquare } from "../registry.js";

/** Renders the "bot-message-square" icon from https://lucide.dev/icons/bot-message-square. */
export const BotMessageSquareIcon = createLucideIcon("bot-message-square", botMessageSquare);
