/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { brainCog } from "../registry.js";

/** Renders the "brain-cog" icon from https://lucide.dev/icons/brain-cog. */
export const BrainCogIcon = createLucideIcon("brain-cog", brainCog);
