/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { brickWall } from "../registry.js";

/** Renders the "brick-wall" icon from https://lucide.dev/icons/brick-wall. */
export const BrickWallIcon = createLucideIcon("brick-wall", brickWall);
