/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { briefcaseConveyorBelt } from "../registry.js";

/** Renders the "briefcase-conveyor-belt" icon from https://lucide.dev/icons/briefcase-conveyor-belt. */
export const BriefcaseConveyorBeltIcon = createLucideIcon(
	"briefcase-conveyor-belt",
	briefcaseConveyorBelt,
);
