/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { brushCleaning } from "../registry.js";

/** Renders the "brush-cleaning" icon from https://lucide.dev/icons/brush-cleaning. */
export const BrushCleaningIcon = createLucideIcon("brush-cleaning", brushCleaning);
