/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bugPlay } from "../registry.js";

/** Renders the "bug-play" icon from https://lucide.dev/icons/bug-play. */
export const BugPlayIcon = createLucideIcon("bug-play", bugPlay);
