/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { busFront } from "../registry.js";

/** Renders the "bus-front" icon from https://lucide.dev/icons/bus-front. */
export const BusFrontIcon = createLucideIcon("bus-front", busFront);
