/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarSearch } from "../registry.js";

/** Renders the "calendar-search" icon from https://lucide.dev/icons/calendar-search. */
export const CalendarSearchIcon = createLucideIcon("calendar-search", calendarSearch);
