/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarArrowUp } from "../registry.js";

/** Renders the "calendar-arrow-up" icon from https://lucide.dev/icons/calendar-arrow-up. */
export const CalendarArrowUpIcon = createLucideIcon("calendar-arrow-up", calendarArrowUp);
