/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarRange } from "../registry.js";

/** Renders the "calendar-range" icon from https://lucide.dev/icons/calendar-range. */
export const CalendarRangeIcon = createLucideIcon("calendar-range", calendarRange);
