/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarCog } from "../registry.js";

/** Renders the "calendar-cog" icon from https://lucide.dev/icons/calendar-cog. */
export const CalendarCogIcon = createLucideIcon("calendar-cog", calendarCog);
