/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { candyOff } from "../registry.js";

/** Renders the "candy-off" icon from https://lucide.dev/icons/candy-off. */
export const CandyOffIcon = createLucideIcon("candy-off", candyOff);
