/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { captionsOff } from "../registry.js";

/** Renders the "captions-off" icon from https://lucide.dev/icons/captions-off. */
export const CaptionsOffIcon = createLucideIcon("captions-off", captionsOff);
