/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { carFront } from "../registry.js";

/** Renders the "car-front" icon from https://lucide.dev/icons/car-front. */
export const CarFrontIcon = createLucideIcon("car-front", carFront);
