/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { carTaxiFront } from "../registry.js";

/** Renders the "car-taxi-front" icon from https://lucide.dev/icons/car-taxi-front. */
export const CarTaxiFrontIcon = createLucideIcon("car-taxi-front", carTaxiFront);
