/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cardSim } from "../registry.js";

/** Renders the "card-sim" icon from https://lucide.dev/icons/card-sim. */
export const CardSimIcon = createLucideIcon("card-sim", cardSim);
