/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { carrot } from "../registry.js";

/** Renders the "carrot" icon from https://lucide.dev/icons/carrot. */
export const CarrotIcon = createLucideIcon("carrot", carrot);
