/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { caseUpper } from "../registry.js";

/** Renders the "case-upper" icon from https://lucide.dev/icons/case-upper. */
export const CaseUpperIcon = createLucideIcon("case-upper", caseUpper);
