/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartColumn } from "../registry.js";

/** Renders the "chart-column" icon from https://lucide.dev/icons/chart-column. */
export const ChartColumnIcon = createLucideIcon("chart-column", chartColumn);
