/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartScatter } from "../registry.js";

/** Renders the "chart-scatter" icon from https://lucide.dev/icons/chart-scatter. */
export const ChartScatterIcon = createLucideIcon("chart-scatter", chartScatter);
