/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartNoAxesColumn } from "../registry.js";

/** Renders the "chart-no-axes-column" icon from https://lucide.dev/icons/chart-no-axes-column. */
export const ChartNoAxesColumnIcon = createLucideIcon("chart-no-axes-column", chartNoAxesColumn);
