/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartColumnIncreasing } from "../registry.js";

/** Renders the "chart-column-increasing" icon from https://lucide.dev/icons/chart-column-increasing. */
export const ChartColumnIncreasingIcon = createLucideIcon(
	"chart-column-increasing",
	chartColumnIncreasing,
);
