/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartPie } from "../registry.js";

/** Renders the "chart-pie" icon from https://lucide.dev/icons/chart-pie. */
export const ChartPieIcon = createLucideIcon("chart-pie", chartPie);
