/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartNoAxesColumnIncreasing } from "../registry.js";

/** Renders the "chart-no-axes-column-increasing" icon from https://lucide.dev/icons/chart-no-axes-column-increasing. */
export const ChartNoAxesColumnIncreasingIcon = createLucideIcon(
	"chart-no-axes-column-increasing",
	chartNoAxesColumnIncreasing,
);
