/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartBarStacked } from "../registry.js";

/** Renders the "chart-bar-stacked" icon from https://lucide.dev/icons/chart-bar-stacked. */
export const ChartBarStackedIcon = createLucideIcon("chart-bar-stacked", chartBarStacked);
