/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chessRook } from "../registry.js";

/** Renders the "chess-rook" icon from https://lucide.dev/icons/chess-rook. */
export const ChessRookIcon = createLucideIcon("chess-rook", chessRook);
