/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chessPawn } from "../registry.js";

/** Renders the "chess-pawn" icon from https://lucide.dev/icons/chess-pawn. */
export const ChessPawnIcon = createLucideIcon("chess-pawn", chessPawn);
