/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chevronsLeftRightEllipsis } from "../registry.js";

/** Renders the "chevrons-left-right-ellipsis" icon from https://lucide.dev/icons/chevrons-left-right-ellipsis. */
export const ChevronsLeftRightEllipsisIcon = createLucideIcon(
	"chevrons-left-right-ellipsis",
	chevronsLeftRightEllipsis,
);
