/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chevronFirst } from "../registry.js";

/** Renders the "chevron-first" icon from https://lucide.dev/icons/chevron-first. */
export const ChevronFirstIcon = createLucideIcon("chevron-first", chevronFirst);
