/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chevronsRight } from "../registry.js";

/** Renders the "chevrons-right" icon from https://lucide.dev/icons/chevrons-right. */
export const ChevronsRightIcon = createLucideIcon("chevrons-right", chevronsRight);
