/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cigaretteOff } from "../registry.js";

/** Renders the "cigarette-off" icon from https://lucide.dev/icons/cigarette-off. */
export const CigaretteOffIcon = createLucideIcon("cigarette-off", cigaretteOff);
