/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circlePause } from "../registry.js";

/** Renders the "circle-pause" icon from https://lucide.dev/icons/circle-pause. */
export const CirclePauseIcon = createLucideIcon("circle-pause", circlePause);
