/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleChevronLeft } from "../registry.js";

/** Renders the "circle-chevron-left" icon from https://lucide.dev/icons/circle-chevron-left. */
export const CircleChevronLeftIcon = createLucideIcon("circle-chevron-left", circleChevronLeft);
