/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleArrowOutUpLeft } from "../registry.js";

/** Renders the "circle-arrow-out-up-left" icon from https://lucide.dev/icons/circle-arrow-out-up-left. */
export const CircleArrowOutUpLeftIcon = createLucideIcon(
	"circle-arrow-out-up-left",
	circleArrowOutUpLeft,
);
