/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleX } from "../registry.js";

/** Renders the "circle-x" icon from https://lucide.dev/icons/circle-x. */
export const CircleXIcon = createLucideIcon("circle-x", circleX);
