/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleStop } from "../registry.js";

/** Renders the "circle-stop" icon from https://lucide.dev/icons/circle-stop. */
export const CircleStopIcon = createLucideIcon("circle-stop", circleStop);
