/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleParkingOff } from "../registry.js";

/** Renders the "circle-parking-off" icon from https://lucide.dev/icons/circle-parking-off. */
export const CircleParkingOffIcon = createLucideIcon("circle-parking-off", circleParkingOff);
