/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleFadingArrowUp } from "../registry.js";

/** Renders the "circle-fading-arrow-up" icon from https://lucide.dev/icons/circle-fading-arrow-up. */
export const CircleFadingArrowUpIcon = createLucideIcon(
	"circle-fading-arrow-up",
	circleFadingArrowUp,
);
