/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleArrowOutDownLeft } from "../registry.js";

/** Renders the "circle-arrow-out-down-left" icon from https://lucide.dev/icons/circle-arrow-out-down-left. */
export const CircleArrowOutDownLeftIcon = createLucideIcon(
	"circle-arrow-out-down-left",
	circleArrowOutDownLeft,
);
