/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circlePower } from "../registry.js";

/** Renders the "circle-power" icon from https://lucide.dev/icons/circle-power. */
export const CirclePowerIcon = createLucideIcon("circle-power", circlePower);
