/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleArrowOutUpRight } from "../registry.js";

/** Renders the "circle-arrow-out-up-right" icon from https://lucide.dev/icons/circle-arrow-out-up-right. */
export const CircleArrowOutUpRightIcon = createLucideIcon(
	"circle-arrow-out-up-right",
	circleArrowOutUpRight,
);
