/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleDivide } from "../registry.js";

/** Renders the "circle-divide" icon from https://lucide.dev/icons/circle-divide. */
export const CircleDivideIcon = createLucideIcon("circle-divide", circleDivide);
