/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleQuestionMark } from "../registry.js";

/** Renders the "circle-question-mark" icon from https://lucide.dev/icons/circle-question-mark. */
export const CircleQuestionMarkIcon = createLucideIcon("circle-question-mark", circleQuestionMark);
