/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleSlash } from "../registry.js";

/** Renders the "circle-slash" icon from https://lucide.dev/icons/circle-slash. */
export const CircleSlashIcon = createLucideIcon("circle-slash", circleSlash);
