/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleArrowLeft } from "../registry.js";

/** Renders the "circle-arrow-left" icon from https://lucide.dev/icons/circle-arrow-left. */
export const CircleArrowLeftIcon = createLucideIcon("circle-arrow-left", circleArrowLeft);
