/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleDollarSign } from "../registry.js";

/** Renders the "circle-dollar-sign" icon from https://lucide.dev/icons/circle-dollar-sign. */
export const CircleDollarSignIcon = createLucideIcon("circle-dollar-sign", circleDollarSign);
