/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleChevronRight } from "../registry.js";

/** Renders the "circle-chevron-right" icon from https://lucide.dev/icons/circle-chevron-right. */
export const CircleChevronRightIcon = createLucideIcon("circle-chevron-right", circleChevronRight);
