/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock6 } from "../registry.js";

/** Renders the "clock-6" icon from https://lucide.dev/icons/clock-6. */
export const Clock6Icon = createLucideIcon("clock-6", clock6);
