/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock11 } from "../registry.js";

/** Renders the "clock-11" icon from https://lucide.dev/icons/clock-11. */
export const Clock11Icon = createLucideIcon("clock-11", clock11);
