/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock2 } from "../registry.js";

/** Renders the "clock-2" icon from https://lucide.dev/icons/clock-2. */
export const Clock2Icon = createLucideIcon("clock-2", clock2);
