/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock1 } from "../registry.js";

/** Renders the "clock-1" icon from https://lucide.dev/icons/clock-1. */
export const Clock1Icon = createLucideIcon("clock-1", clock1);
