/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clockArrowUp } from "../registry.js";

/** Renders the "clock-arrow-up" icon from https://lucide.dev/icons/clock-arrow-up. */
export const ClockArrowUpIcon = createLucideIcon("clock-arrow-up", clockArrowUp);
