/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock10 } from "../registry.js";

/** Renders the "clock-10" icon from https://lucide.dev/icons/clock-10. */
export const Clock10Icon = createLucideIcon("clock-10", clock10);
