/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock9 } from "../registry.js";

/** Renders the "clock-9" icon from https://lucide.dev/icons/clock-9. */
export const Clock9Icon = createLucideIcon("clock-9", clock9);
