/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloudMoon } from "../registry.js";

/** Renders the "cloud-moon" icon from https://lucide.dev/icons/cloud-moon. */
export const CloudMoonIcon = createLucideIcon("cloud-moon", cloudMoon);
