/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloudMoonRain } from "../registry.js";

/** Renders the "cloud-moon-rain" icon from https://lucide.dev/icons/cloud-moon-rain. */
export const CloudMoonRainIcon = createLucideIcon("cloud-moon-rain", cloudMoonRain);
