/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloudSunRain } from "../registry.js";

/** Renders the "cloud-sun-rain" icon from https://lucide.dev/icons/cloud-sun-rain. */
export const CloudSunRainIcon = createLucideIcon("cloud-sun-rain", cloudSunRain);
