/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloudOff } from "../registry.js";

/** Renders the "cloud-off" icon from https://lucide.dev/icons/cloud-off. */
export const CloudOffIcon = createLucideIcon("cloud-off", cloudOff);
