/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloud } from "../registry.js";

/** Renders the "cloud" icon from https://lucide.dev/icons/cloud. */
export const CloudIcon = createLucideIcon("cloud", cloud);
