/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloudRainWind } from "../registry.js";

/** Renders the "cloud-rain-wind" icon from https://lucide.dev/icons/cloud-rain-wind. */
export const CloudRainWindIcon = createLucideIcon("cloud-rain-wind", cloudRainWind);
