/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloudUpload } from "../registry.js";

/** Renders the "cloud-upload" icon from https://lucide.dev/icons/cloud-upload. */
export const CloudUploadIcon = createLucideIcon("cloud-upload", cloudUpload);
