/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { coins } from "../registry.js";

/** Renders the "coins" icon from https://lucide.dev/icons/coins. */
export const CoinsIcon = createLucideIcon("coins", coins);
