/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { columns4 } from "../registry.js";

/** Renders the "columns-4" icon from https://lucide.dev/icons/columns-4. */
export const Columns4Icon = createLucideIcon("columns-4", columns4);
