/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { component } from "../registry.js";

/** Renders the "component" icon from https://lucide.dev/icons/component. */
export const ComponentIcon = createLucideIcon("component", component);
