/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { copyleft } from "../registry.js";

/** Renders the "copyleft" icon from https://lucide.dev/icons/copyleft. */
export const CopyleftIcon = createLucideIcon("copyleft", copyleft);
