/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cornerDownLeft } from "../registry.js";

/** Renders the "corner-down-left" icon from https://lucide.dev/icons/corner-down-left. */
export const CornerDownLeftIcon = createLucideIcon("corner-down-left", cornerDownLeft);
