/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cornerRightDown } from "../registry.js";

/** Renders the "corner-right-down" icon from https://lucide.dev/icons/corner-right-down. */
export const CornerRightDownIcon = createLucideIcon("corner-right-down", cornerRightDown);
