/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { croissant } from "../registry.js";

/** Renders the "croissant" icon from https://lucide.dev/icons/croissant. */
export const CroissantIcon = createLucideIcon("croissant", croissant);
