/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { crop } from "../registry.js";

/** Renders the "crop" icon from https://lucide.dev/icons/crop. */
export const CropIcon = createLucideIcon("crop", crop);
