/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { crosshair } from "../registry.js";

/** Renders the "crosshair" icon from https://lucide.dev/icons/crosshair. */
export const CrosshairIcon = createLucideIcon("crosshair", crosshair);
