/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { decimalsArrowRight } from "../registry.js";

/** Renders the "decimals-arrow-right" icon from https://lucide.dev/icons/decimals-arrow-right. */
export const DecimalsArrowRightIcon = createLucideIcon("decimals-arrow-right", decimalsArrowRight);
