/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { decimalsArrowLeft } from "../registry.js";

/** Renders the "decimals-arrow-left" icon from https://lucide.dev/icons/decimals-arrow-left. */
export const DecimalsArrowLeftIcon = createLucideIcon("decimals-arrow-left", decimalsArrowLeft);
