/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { dice5 } from "../registry.js";

/** Renders the "dice-5" icon from https://lucide.dev/icons/dice-5. */
export const Dice5Icon = createLucideIcon("dice-5", dice5);
