/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { dice3 } from "../registry.js";

/** Renders the "dice-3" icon from https://lucide.dev/icons/dice-3. */
export const Dice3Icon = createLucideIcon("dice-3", dice3);
