/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { dice1 } from "../registry.js";

/** Renders the "dice-1" icon from https://lucide.dev/icons/dice-1. */
export const Dice1Icon = createLucideIcon("dice-1", dice1);
