/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { dice2 } from "../registry.js";

/** Renders the "dice-2" icon from https://lucide.dev/icons/dice-2. */
export const Dice2Icon = createLucideIcon("dice-2", dice2);
