/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { disc3 } from "../registry.js";

/** Renders the "disc-3" icon from https://lucide.dev/icons/disc-3. */
export const Disc3Icon = createLucideIcon("disc-3", disc3);
