/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { doorOpen } from "../registry.js";

/** Renders the "door-open" icon from https://lucide.dev/icons/door-open. */
export const DoorOpenIcon = createLucideIcon("door-open", doorOpen);
