/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { draftingCompass } from "../registry.js";

/** Renders the "drafting-compass" icon from https://lucide.dev/icons/drafting-compass. */
export const DraftingCompassIcon = createLucideIcon("drafting-compass", draftingCompass);
