/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { drum } from "../registry.js";

/** Renders the "drum" icon from https://lucide.dev/icons/drum. */
export const DrumIcon = createLucideIcon("drum", drum);
