/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { dumbbell } from "../registry.js";

/** Renders the "dumbbell" icon from https://lucide.dev/icons/dumbbell. */
export const DumbbellIcon = createLucideIcon("dumbbell", dumbbell);
