/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { earthLock } from "../registry.js";

/** Renders the "earth-lock" icon from https://lucide.dev/icons/earth-lock. */
export const EarthLockIcon = createLucideIcon("earth-lock", earthLock);
