/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ellipsisVertical } from "../registry.js";

/** Renders the "ellipsis-vertical" icon from https://lucide.dev/icons/ellipsis-vertical. */
export const EllipsisVerticalIcon = createLucideIcon("ellipsis-vertical", ellipsisVertical);
