/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { equalApproximately } from "../registry.js";

/** Renders the "equal-approximately" icon from https://lucide.dev/icons/equal-approximately. */
export const EqualApproximatelyIcon = createLucideIcon("equal-approximately", equalApproximately);
