/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { equalNot } from "../registry.js";

/** Renders the "equal-not" icon from https://lucide.dev/icons/equal-not. */
export const EqualNotIcon = createLucideIcon("equal-not", equalNot);
