/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { eraser } from "../registry.js";

/** Renders the "eraser" icon from https://lucide.dev/icons/eraser. */
export const EraserIcon = createLucideIcon("eraser", eraser);
