/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { evCharger } from "../registry.js";

/** Renders the "ev-charger" icon from https://lucide.dev/icons/ev-charger. */
export const EvChargerIcon = createLucideIcon("ev-charger", evCharger);
