/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { eyeClosed } from "../registry.js";

/** Renders the "eye-closed" icon from https://lucide.dev/icons/eye-closed. */
export const EyeClosedIcon = createLucideIcon("eye-closed", eyeClosed);
