/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { eye } from "../registry.js";

/** Renders the "eye" icon from https://lucide.dev/icons/eye. */
export const EyeIcon = createLucideIcon("eye", eye);
