/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fastForward } from "../registry.js";

/** Renders the "fast-forward" icon from https://lucide.dev/icons/fast-forward. */
export const FastForwardIcon = createLucideIcon("fast-forward", fastForward);
