/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { filePlus } from "../registry.js";

/** Renders the "file-plus" icon from https://lucide.dev/icons/file-plus. */
export const FilePlusIcon = createLucideIcon("file-plus", filePlus);
