/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileType } from "../registry.js";

/** Renders the "file-type" icon from https://lucide.dev/icons/file-type. */
export const FileTypeIcon = createLucideIcon("file-type", fileType);
