/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileX } from "../registry.js";

/** Renders the "file-x" icon from https://lucide.dev/icons/file-x. */
export const FileXIcon = createLucideIcon("file-x", fileX);
