/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileOutput } from "../registry.js";

/** Renders the "file-output" icon from https://lucide.dev/icons/file-output. */
export const FileOutputIcon = createLucideIcon("file-output", fileOutput);
