/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileDown } from "../registry.js";

/** Renders the "file-down" icon from https://lucide.dev/icons/file-down. */
export const FileDownIcon = createLucideIcon("file-down", fileDown);
