/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileMinusCorner } from "../registry.js";

/** Renders the "file-minus-corner" icon from https://lucide.dev/icons/file-minus-corner. */
export const FileMinusCornerIcon = createLucideIcon("file-minus-corner", fileMinusCorner);
