/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { filePlusCorner } from "../registry.js";

/** Renders the "file-plus-corner" icon from https://lucide.dev/icons/file-plus-corner. */
export const FilePlusCornerIcon = createLucideIcon("file-plus-corner", filePlusCorner);
