/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileLock } from "../registry.js";

/** Renders the "file-lock" icon from https://lucide.dev/icons/file-lock. */
export const FileLockIcon = createLucideIcon("file-lock", fileLock);
