/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileQuestionMark } from "../registry.js";

/** Renders the "file-question-mark" icon from https://lucide.dev/icons/file-question-mark. */
export const FileQuestionMarkIcon = createLucideIcon("file-question-mark", fileQuestionMark);
