/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileAxis3d } from "../registry.js";

/** Renders the "file-axis-3d" icon from https://lucide.dev/icons/file-axis-3d. */
export const FileAxis3dIcon = createLucideIcon("file-axis-3d", fileAxis3d);
