/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { files } from "../registry.js";

/** Renders the "files" icon from https://lucide.dev/icons/files. */
export const FilesIcon = createLucideIcon("files", files);
