/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileChartLine } from "../registry.js";

/** Renders the "file-chart-line" icon from https://lucide.dev/icons/file-chart-line. */
export const FileChartLineIcon = createLucideIcon("file-chart-line", fileChartLine);
