/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileDigit } from "../registry.js";

/** Renders the "file-digit" icon from https://lucide.dev/icons/file-digit. */
export const FileDigitIcon = createLucideIcon("file-digit", fileDigit);
