/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileCog } from "../registry.js";

/** Renders the "file-cog" icon from https://lucide.dev/icons/file-cog. */
export const FileCogIcon = createLucideIcon("file-cog", fileCog);
