/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileDiff } from "../registry.js";

/** Renders the "file-diff" icon from https://lucide.dev/icons/file-diff. */
export const FileDiffIcon = createLucideIcon("file-diff", fileDiff);
