/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fingerprintPattern } from "../registry.js";

/** Renders the "fingerprint-pattern" icon from https://lucide.dev/icons/fingerprint-pattern. */
export const FingerprintPatternIcon = createLucideIcon("fingerprint-pattern", fingerprintPattern);
