/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fishSymbol } from "../registry.js";

/** Renders the "fish-symbol" icon from https://lucide.dev/icons/fish-symbol. */
export const FishSymbolIcon = createLucideIcon("fish-symbol", fishSymbol);
