/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { flagTriangleRight } from "../registry.js";

/** Renders the "flag-triangle-right" icon from https://lucide.dev/icons/flag-triangle-right. */
export const FlagTriangleRightIcon = createLucideIcon("flag-triangle-right", flagTriangleRight);
