/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { flaskConical } from "../registry.js";

/** Renders the "flask-conical" icon from https://lucide.dev/icons/flask-conical. */
export const FlaskConicalIcon = createLucideIcon("flask-conical", flaskConical);
