/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderGit } from "../registry.js";

/** Renders the "folder-git" icon from https://lucide.dev/icons/folder-git. */
export const FolderGitIcon = createLucideIcon("folder-git", folderGit);
