/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { foldVertical } from "../registry.js";

/** Renders the "fold-vertical" icon from https://lucide.dev/icons/fold-vertical. */
export const FoldVerticalIcon = createLucideIcon("fold-vertical", foldVertical);
