/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderOutput } from "../registry.js";

/** Renders the "folder-output" icon from https://lucide.dev/icons/folder-output. */
export const FolderOutputIcon = createLucideIcon("folder-output", folderOutput);
