/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderPlus } from "../registry.js";

/** Renders the "folder-plus" icon from https://lucide.dev/icons/folder-plus. */
export const FolderPlusIcon = createLucideIcon("folder-plus", folderPlus);
