/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderRoot } from "../registry.js";

/** Renders the "folder-root" icon from https://lucide.dev/icons/folder-root. */
export const FolderRootIcon = createLucideIcon("folder-root", folderRoot);
