/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderX } from "../registry.js";

/** Renders the "folder-x" icon from https://lucide.dev/icons/folder-x. */
export const FolderXIcon = createLucideIcon("folder-x", folderX);
