/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderGit2 } from "../registry.js";

/** Renders the "folder-git-2" icon from https://lucide.dev/icons/folder-git-2. */
export const FolderGit2Icon = createLucideIcon("folder-git-2", folderGit2);
