/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderOpenDot } from "../registry.js";

/** Renders the "folder-open-dot" icon from https://lucide.dev/icons/folder-open-dot. */
export const FolderOpenDotIcon = createLucideIcon("folder-open-dot", folderOpenDot);
