/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderArchive } from "../registry.js";

/** Renders the "folder-archive" icon from https://lucide.dev/icons/folder-archive. */
export const FolderArchiveIcon = createLucideIcon("folder-archive", folderArchive);
