/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderDown } from "../registry.js";

/** Renders the "folder-down" icon from https://lucide.dev/icons/folder-down. */
export const FolderDownIcon = createLucideIcon("folder-down", folderDown);
