/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderSearch2 } from "../registry.js";

/** Renders the "folder-search-2" icon from https://lucide.dev/icons/folder-search-2. */
export const FolderSearch2Icon = createLucideIcon("folder-search-2", folderSearch2);
