/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderLock } from "../registry.js";

/** Renders the "folder-lock" icon from https://lucide.dev/icons/folder-lock. */
export const FolderLockIcon = createLucideIcon("folder-lock", folderLock);
