/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fuel } from "../registry.js";

/** Renders the "fuel" icon from https://lucide.dev/icons/fuel. */
export const FuelIcon = createLucideIcon("fuel", fuel);
