/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { galleryHorizontal } from "../registry.js";

/** Renders the "gallery-horizontal" icon from https://lucide.dev/icons/gallery-horizontal. */
export const GalleryHorizontalIcon = createLucideIcon("gallery-horizontal", galleryHorizontal);
