/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gamepad2 } from "../registry.js";

/** Renders the "gamepad-2" icon from https://lucide.dev/icons/gamepad-2. */
export const Gamepad2Icon = createLucideIcon("gamepad-2", gamepad2);
