/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gavel } from "../registry.js";

/** Renders the "gavel" icon from https://lucide.dev/icons/gavel. */
export const GavelIcon = createLucideIcon("gavel", gavel);
