/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gem } from "../registry.js";

/** Renders the "gem" icon from https://lucide.dev/icons/gem. */
export const GemIcon = createLucideIcon("gem", gem);
