/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gitPullRequestArrow } from "../registry.js";

/** Renders the "git-pull-request-arrow" icon from https://lucide.dev/icons/git-pull-request-arrow. */
export const GitPullRequestArrowIcon = createLucideIcon(
	"git-pull-request-arrow",
	gitPullRequestArrow,
);
