/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gitBranchPlus } from "../registry.js";

/** Renders the "git-branch-plus" icon from https://lucide.dev/icons/git-branch-plus. */
export const GitBranchPlusIcon = createLucideIcon("git-branch-plus", gitBranchPlus);
