/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gitPullRequestDraft } from "../registry.js";

/** Renders the "git-pull-request-draft" icon from https://lucide.dev/icons/git-pull-request-draft. */
export const GitPullRequestDraftIcon = createLucideIcon(
	"git-pull-request-draft",
	gitPullRequestDraft,
);
