/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gitPullRequestClosed } from "../registry.js";

/** Renders the "git-pull-request-closed" icon from https://lucide.dev/icons/git-pull-request-closed. */
export const GitPullRequestClosedIcon = createLucideIcon(
	"git-pull-request-closed",
	gitPullRequestClosed,
);
