/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { globeOff } from "../registry.js";

/** Renders the "globe-off" icon from https://lucide.dev/icons/globe-off. */
export const GlobeOffIcon = createLucideIcon("globe-off", globeOff);
