/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { globeLock } from "../registry.js";

/** Renders the "globe-lock" icon from https://lucide.dev/icons/globe-lock. */
export const GlobeLockIcon = createLucideIcon("globe-lock", globeLock);
