/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { graduationCap } from "../registry.js";

/** Renders the "graduation-cap" icon from https://lucide.dev/icons/graduation-cap. */
export const GraduationCapIcon = createLucideIcon("graduation-cap", graduationCap);
