/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { grid2x2Check } from "../registry.js";

/** Renders the "grid-2x2-check" icon from https://lucide.dev/icons/grid-2x2-check. */
export const Grid2x2CheckIcon = createLucideIcon("grid-2x2-check", grid2x2Check);
