/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { grid3x3 } from "../registry.js";

/** Renders the "grid-3x3" icon from https://lucide.dev/icons/grid-3x3. */
export const Grid3x3Icon = createLucideIcon("grid-3x3", grid3x3);
