/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { grip } from "../registry.js";

/** Renders the "grip" icon from https://lucide.dev/icons/grip. */
export const GripIcon = createLucideIcon("grip", grip);
