/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gripVertical } from "../registry.js";

/** Renders the "grip-vertical" icon from https://lucide.dev/icons/grip-vertical. */
export const GripVerticalIcon = createLucideIcon("grip-vertical", gripVertical);
