/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gripHorizontal } from "../registry.js";

/** Renders the "grip-horizontal" icon from https://lucide.dev/icons/grip-horizontal. */
export const GripHorizontalIcon = createLucideIcon("grip-horizontal", gripHorizontal);
