/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { handCoins } from "../registry.js";

/** Renders the "hand-coins" icon from https://lucide.dev/icons/hand-coins. */
export const HandCoinsIcon = createLucideIcon("hand-coins", handCoins);
