/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { handPlatter } from "../registry.js";

/** Renders the "hand-platter" icon from https://lucide.dev/icons/hand-platter. */
export const HandPlatterIcon = createLucideIcon("hand-platter", handPlatter);
