/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { hand } from "../registry.js";

/** Renders the "hand" icon from https://lucide.dev/icons/hand. */
export const HandIcon = createLucideIcon("hand", hand);
