/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { handMetal } from "../registry.js";

/** Renders the "hand-metal" icon from https://lucide.dev/icons/hand-metal. */
export const HandMetalIcon = createLucideIcon("hand-metal", handMetal);
