/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { hdmiPort } from "../registry.js";

/** Renders the "hdmi-port" icon from https://lucide.dev/icons/hdmi-port. */
export const HdmiPortIcon = createLucideIcon("hdmi-port", hdmiPort);
