/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heading5 } from "../registry.js";

/** Renders the "heading-5" icon from https://lucide.dev/icons/heading-5. */
export const Heading5Icon = createLucideIcon("heading-5", heading5);
