/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heading4 } from "../registry.js";

/** Renders the "heading-4" icon from https://lucide.dev/icons/heading-4. */
export const Heading4Icon = createLucideIcon("heading-4", heading4);
