/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heading3 } from "../registry.js";

/** Renders the "heading-3" icon from https://lucide.dev/icons/heading-3. */
export const Heading3Icon = createLucideIcon("heading-3", heading3);
