/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heartCrack } from "../registry.js";

/** Renders the "heart-crack" icon from https://lucide.dev/icons/heart-crack. */
export const HeartCrackIcon = createLucideIcon("heart-crack", heartCrack);
