/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heart } from "../registry.js";

/** Renders the "heart" icon from https://lucide.dev/icons/heart. */
export const HeartIcon = createLucideIcon("heart", heart);
