/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { hexagon } from "../registry.js";

/** Renders the "hexagon" icon from https://lucide.dev/icons/hexagon. */
export const HexagonIcon = createLucideIcon("hexagon", hexagon);
