/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { hospital } from "../registry.js";

/** Renders the "hospital" icon from https://lucide.dev/icons/hospital. */
export const HospitalIcon = createLucideIcon("hospital", hospital);
