/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { houseWifi } from "../registry.js";

/** Renders the "house-wifi" icon from https://lucide.dev/icons/house-wifi. */
export const HouseWifiIcon = createLucideIcon("house-wifi", houseWifi);
