/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { iceCreamCone } from "../registry.js";

/** Renders the "ice-cream-cone" icon from https://lucide.dev/icons/ice-cream-cone. */
export const IceCreamConeIcon = createLucideIcon("ice-cream-cone", iceCreamCone);
