/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { iceCreamBowl } from "../registry.js";

/** Renders the "ice-cream-bowl" icon from https://lucide.dev/icons/ice-cream-bowl. */
export const IceCreamBowlIcon = createLucideIcon("ice-cream-bowl", iceCreamBowl);
