/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { idCardLanyard } from "../registry.js";

/** Renders the "id-card-lanyard" icon from https://lucide.dev/icons/id-card-lanyard. */
export const IdCardLanyardIcon = createLucideIcon("id-card-lanyard", idCardLanyard);
