/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { idCard } from "../registry.js";

/** Renders the "id-card" icon from https://lucide.dev/icons/id-card. */
export const IdCardIcon = createLucideIcon("id-card", idCard);
