/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { imagePlay } from "../registry.js";

/** Renders the "image-play" icon from https://lucide.dev/icons/image-play. */
export const ImagePlayIcon = createLucideIcon("image-play", imagePlay);
