/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { iterationCcw } from "../registry.js";

/** Renders the "iteration-ccw" icon from https://lucide.dev/icons/iteration-ccw. */
export const IterationCcwIcon = createLucideIcon("iteration-ccw", iterationCcw);
