/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { iterationCw } from "../registry.js";

/** Renders the "iteration-cw" icon from https://lucide.dev/icons/iteration-cw. */
export const IterationCwIcon = createLucideIcon("iteration-cw", iterationCw);
