/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { japaneseYen } from "../registry.js";

/** Renders the "japanese-yen" icon from https://lucide.dev/icons/japanese-yen. */
export const JapaneseYenIcon = createLucideIcon("japanese-yen", japaneseYen);
