/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { joystick } from "../registry.js";

/** Renders the "joystick" icon from https://lucide.dev/icons/joystick. */
export const JoystickIcon = createLucideIcon("joystick", joystick);
