/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { keyRound } from "../registry.js";

/** Renders the "key-round" icon from https://lucide.dev/icons/key-round. */
export const KeyRoundIcon = createLucideIcon("key-round", keyRound);
