/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lampWallUp } from "../registry.js";

/** Renders the "lamp-wall-up" icon from https://lucide.dev/icons/lamp-wall-up. */
export const LampWallUpIcon = createLucideIcon("lamp-wall-up", lampWallUp);
