/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lampWallDown } from "../registry.js";

/** Renders the "lamp-wall-down" icon from https://lucide.dev/icons/lamp-wall-down. */
export const LampWallDownIcon = createLucideIcon("lamp-wall-down", lampWallDown);
