/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lampCeiling } from "../registry.js";

/** Renders the "lamp-ceiling" icon from https://lucide.dev/icons/lamp-ceiling. */
export const LampCeilingIcon = createLucideIcon("lamp-ceiling", lampCeiling);
