/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { landmark } from "../registry.js";

/** Renders the "landmark" icon from https://lucide.dev/icons/landmark. */
export const LandmarkIcon = createLucideIcon("landmark", landmark);
