/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { laptop } from "../registry.js";

/** Renders the "laptop" icon from https://lucide.dev/icons/laptop. */
export const LaptopIcon = createLucideIcon("laptop", laptop);
