/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { layoutPanelLeft } from "../registry.js";

/** Renders the "layout-panel-left" icon from https://lucide.dev/icons/layout-panel-left. */
export const LayoutPanelLeftIcon = createLucideIcon("layout-panel-left", layoutPanelLeft);
