/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { layoutList } from "../registry.js";

/** Renders the "layout-list" icon from https://lucide.dev/icons/layout-list. */
export const LayoutListIcon = createLucideIcon("layout-list", layoutList);
