/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { layoutTemplate } from "../registry.js";

/** Renders the "layout-template" icon from https://lucide.dev/icons/layout-template. */
export const LayoutTemplateIcon = createLucideIcon("layout-template", layoutTemplate);
