/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { layoutGrid } from "../registry.js";

/** Renders the "layout-grid" icon from https://lucide.dev/icons/layout-grid. */
export const LayoutGridIcon = createLucideIcon("layout-grid", layoutGrid);
