/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { leafyGreen } from "../registry.js";

/** Renders the "leafy-green" icon from https://lucide.dev/icons/leafy-green. */
export const LeafyGreenIcon = createLucideIcon("leafy-green", leafyGreen);
