/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lensConcave } from "../registry.js";

/** Renders the "lens-concave" icon from https://lucide.dev/icons/lens-concave. */
export const LensConcaveIcon = createLucideIcon("lens-concave", lensConcave);
