/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { library } from "../registry.js";

/** Renders the "library" icon from https://lucide.dev/icons/library. */
export const LibraryIcon = createLucideIcon("library", library);
