/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lightbulbOff } from "../registry.js";

/** Renders the "lightbulb-off" icon from https://lucide.dev/icons/lightbulb-off. */
export const LightbulbOffIcon = createLucideIcon("lightbulb-off", lightbulbOff);
