/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { link2 } from "../registry.js";

/** Renders the "link-2" icon from https://lucide.dev/icons/link-2. */
export const Link2Icon = createLucideIcon("link-2", link2);
