/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { listSortAscending } from "../registry.js";

/** Renders the "list-sort-ascending" icon from https://lucide.dev/icons/list-sort-ascending. */
export const ListSortAscendingIcon = createLucideIcon("list-sort-ascending", listSortAscending);
