/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { listChevronsDownUp } from "../registry.js";

/** Renders the "list-chevrons-down-up" icon from https://lucide.dev/icons/list-chevrons-down-up. */
export const ListChevronsDownUpIcon = createLucideIcon("list-chevrons-down-up", listChevronsDownUp);
