/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { listPlus } from "../registry.js";

/** Renders the "list-plus" icon from https://lucide.dev/icons/list-plus. */
export const ListPlusIcon = createLucideIcon("list-plus", listPlus);
