/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { listIndentIncrease } from "../registry.js";

/** Renders the "list-indent-increase" icon from https://lucide.dev/icons/list-indent-increase. */
export const ListIndentIncreaseIcon = createLucideIcon("list-indent-increase", listIndentIncrease);
