/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { listMinus } from "../registry.js";

/** Renders the "list-minus" icon from https://lucide.dev/icons/list-minus. */
export const ListMinusIcon = createLucideIcon("list-minus", listMinus);
