/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { listRestart } from "../registry.js";

/** Renders the "list-restart" icon from https://lucide.dev/icons/list-restart. */
export const ListRestartIcon = createLucideIcon("list-restart", listRestart);
