/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mapPinPlusInside } from "../registry.js";

/** Renders the "map-pin-plus-inside" icon from https://lucide.dev/icons/map-pin-plus-inside. */
export const MapPinPlusInsideIcon = createLucideIcon("map-pin-plus-inside", mapPinPlusInside);
