/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mapPinXInside } from "../registry.js";

/** Renders the "map-pin-x-inside" icon from https://lucide.dev/icons/map-pin-x-inside. */
export const MapPinXInsideIcon = createLucideIcon("map-pin-x-inside", mapPinXInside);
