/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mapPinSearch } from "../registry.js";

/** Renders the "map-pin-search" icon from https://lucide.dev/icons/map-pin-search. */
export const MapPinSearchIcon = createLucideIcon("map-pin-search", mapPinSearch);
