/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { megaphone } from "../registry.js";

/** Renders the "megaphone" icon from https://lucide.dev/icons/megaphone. */
export const MegaphoneIcon = createLucideIcon("megaphone", megaphone);
