/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageSquareMore } from "../registry.js";

/** Renders the "message-square-more" icon from https://lucide.dev/icons/message-square-more. */
export const MessageSquareMoreIcon = createLucideIcon("message-square-more", messageSquareMore);
