/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageSquareShare } from "../registry.js";

/** Renders the "message-square-share" icon from https://lucide.dev/icons/message-square-share. */
export const MessageSquareShareIcon = createLucideIcon("message-square-share", messageSquareShare);
