/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageSquareDashed } from "../registry.js";

/** Renders the "message-square-dashed" icon from https://lucide.dev/icons/message-square-dashed. */
export const MessageSquareDashedIcon = createLucideIcon(
	"message-square-dashed",
	messageSquareDashed,
);
