/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageCircleDashed } from "../registry.js";

/** Renders the "message-circle-dashed" icon from https://lucide.dev/icons/message-circle-dashed. */
export const MessageCircleDashedIcon = createLucideIcon(
	"message-circle-dashed",
	messageCircleDashed,
);
