/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messagesSquare } from "../registry.js";

/** Renders the "messages-square" icon from https://lucide.dev/icons/messages-square. */
export const MessagesSquareIcon = createLucideIcon("messages-square", messagesSquare);
