/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageCircleQuestionMark } from "../registry.js";

/** Renders the "message-circle-question-mark" icon from https://lucide.dev/icons/message-circle-question-mark. */
export const MessageCircleQuestionMarkIcon = createLucideIcon(
	"message-circle-question-mark",
	messageCircleQuestionMark,
);
