/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageSquareOff } from "../registry.js";

/** Renders the "message-square-off" icon from https://lucide.dev/icons/message-square-off. */
export const MessageSquareOffIcon = createLucideIcon("message-square-off", messageSquareOff);
