/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageSquareReply } from "../registry.js";

/** Renders the "message-square-reply" icon from https://lucide.dev/icons/message-square-reply. */
export const MessageSquareReplyIcon = createLucideIcon("message-square-reply", messageSquareReply);
