/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageCircleX } from "../registry.js";

/** Renders the "message-circle-x" icon from https://lucide.dev/icons/message-circle-x. */
export const MessageCircleXIcon = createLucideIcon("message-circle-x", messageCircleX);
