/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { milkOff } from "../registry.js";

/** Renders the "milk-off" icon from https://lucide.dev/icons/milk-off. */
export const MilkOffIcon = createLucideIcon("milk-off", milkOff);
