/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { minimize2 } from "../registry.js";

/** Renders the "minimize-2" icon from https://lucide.dev/icons/minimize-2. */
export const Minimize2Icon = createLucideIcon("minimize-2", minimize2);
