/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mirrorRound } from "../registry.js";

/** Renders the "mirror-round" icon from https://lucide.dev/icons/mirror-round. */
export const MirrorRoundIcon = createLucideIcon("mirror-round", mirrorRound);
