/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mirrorRectangular } from "../registry.js";

/** Renders the "mirror-rectangular" icon from https://lucide.dev/icons/mirror-rectangular. */
export const MirrorRectangularIcon = createLucideIcon("mirror-rectangular", mirrorRectangular);
