/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { monitorX } from "../registry.js";

/** Renders the "monitor-x" icon from https://lucide.dev/icons/monitor-x. */
export const MonitorXIcon = createLucideIcon("monitor-x", monitorX);
