/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { monitorSmartphone } from "../registry.js";

/** Renders the "monitor-smartphone" icon from https://lucide.dev/icons/monitor-smartphone. */
export const MonitorSmartphoneIcon = createLucideIcon("monitor-smartphone", monitorSmartphone);
