/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { monitorCheck } from "../registry.js";

/** Renders the "monitor-check" icon from https://lucide.dev/icons/monitor-check. */
export const MonitorCheckIcon = createLucideIcon("monitor-check", monitorCheck);
