/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { monitorOff } from "../registry.js";

/** Renders the "monitor-off" icon from https://lucide.dev/icons/monitor-off. */
export const MonitorOffIcon = createLucideIcon("monitor-off", monitorOff);
