/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { monitorCloud } from "../registry.js";

/** Renders the "monitor-cloud" icon from https://lucide.dev/icons/monitor-cloud. */
export const MonitorCloudIcon = createLucideIcon("monitor-cloud", monitorCloud);
