/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { moonStar } from "../registry.js";

/** Renders the "moon-star" icon from https://lucide.dev/icons/moon-star. */
export const MoonStarIcon = createLucideIcon("moon-star", moonStar);
