/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mousePointer2Off } from "../registry.js";

/** Renders the "mouse-pointer-2-off" icon from https://lucide.dev/icons/mouse-pointer-2-off. */
export const MousePointer2OffIcon = createLucideIcon("mouse-pointer-2-off", mousePointer2Off);
