/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { move } from "../registry.js";

/** Renders the "move" icon from https://lucide.dev/icons/move. */
export const MoveIcon = createLucideIcon("move", move);
