/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { moveUpLeft } from "../registry.js";

/** Renders the "move-up-left" icon from https://lucide.dev/icons/move-up-left. */
export const MoveUpLeftIcon = createLucideIcon("move-up-left", moveUpLeft);
