/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { navigation } from "../registry.js";

/** Renders the "navigation" icon from https://lucide.dev/icons/navigation. */
export const NavigationIcon = createLucideIcon("navigation", navigation);
