/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { nfc } from "../registry.js";

/** Renders the "nfc" icon from https://lucide.dev/icons/nfc. */
export const NfcIcon = createLucideIcon("nfc", nfc);
