/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { octagonMinus } from "../registry.js";

/** Renders the "octagon-minus" icon from https://lucide.dev/icons/octagon-minus. */
export const OctagonMinusIcon = createLucideIcon("octagon-minus", octagonMinus);
