/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { octagonX } from "../registry.js";

/** Renders the "octagon-x" icon from https://lucide.dev/icons/octagon-x. */
export const OctagonXIcon = createLucideIcon("octagon-x", octagonX);
