/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { omega } from "../registry.js";

/** Renders the "omega" icon from https://lucide.dev/icons/omega. */
export const OmegaIcon = createLucideIcon("omega", omega);
