/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { package2 } from "../registry.js";

/** Renders the "package-2" icon from https://lucide.dev/icons/package-2. */
export const Package2Icon = createLucideIcon("package-2", package2);
