/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { packagePlus } from "../registry.js";

/** Renders the "package-plus" icon from https://lucide.dev/icons/package-plus. */
export const PackagePlusIcon = createLucideIcon("package-plus", packagePlus);
