/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { paintBucket } from "../registry.js";

/** Renders the "paint-bucket" icon from https://lucide.dev/icons/paint-bucket. */
export const PaintBucketIcon = createLucideIcon("paint-bucket", paintBucket);
