/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { paintbrushVertical } from "../registry.js";

/** Renders the "paintbrush-vertical" icon from https://lucide.dev/icons/paintbrush-vertical. */
export const PaintbrushVerticalIcon = createLucideIcon("paintbrush-vertical", paintbrushVertical);
