/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { palette } from "../registry.js";

/** Renders the "palette" icon from https://lucide.dev/icons/palette. */
export const PaletteIcon = createLucideIcon("palette", palette);
