/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { panda } from "../registry.js";

/** Renders the "panda" icon from https://lucide.dev/icons/panda. */
export const PandaIcon = createLucideIcon("panda", panda);
