/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { panelBottom } from "../registry.js";

/** Renders the "panel-bottom" icon from https://lucide.dev/icons/panel-bottom. */
export const PanelBottomIcon = createLucideIcon("panel-bottom", panelBottom);
