/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { panelLeftOpen } from "../registry.js";

/** Renders the "panel-left-open" icon from https://lucide.dev/icons/panel-left-open. */
export const PanelLeftOpenIcon = createLucideIcon("panel-left-open", panelLeftOpen);
