/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { panelTop } from "../registry.js";

/** Renders the "panel-top" icon from https://lucide.dev/icons/panel-top. */
export const PanelTopIcon = createLucideIcon("panel-top", panelTop);
