/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { panelsTopLeft } from "../registry.js";

/** Renders the "panels-top-left" icon from https://lucide.dev/icons/panels-top-left. */
export const PanelsTopLeftIcon = createLucideIcon("panels-top-left", panelsTopLeft);
