/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { panelBottomClose } from "../registry.js";

/** Renders the "panel-bottom-close" icon from https://lucide.dev/icons/panel-bottom-close. */
export const PanelBottomCloseIcon = createLucideIcon("panel-bottom-close", panelBottomClose);
