/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { paperBag } from "../registry.js";

/** Renders the "paper-bag" icon from https://lucide.dev/icons/paper-bag. */
export const PaperBagIcon = createLucideIcon("paper-bag", paperBag);
