/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { parkingMeter } from "../registry.js";

/** Renders the "parking-meter" icon from https://lucide.dev/icons/parking-meter. */
export const ParkingMeterIcon = createLucideIcon("parking-meter", parkingMeter);
