/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { pawPrint } from "../registry.js";

/** Renders the "paw-print" icon from https://lucide.dev/icons/paw-print. */
export const PawPrintIcon = createLucideIcon("paw-print", pawPrint);
