/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { pcCase } from "../registry.js";

/** Renders the "pc-case" icon from https://lucide.dev/icons/pc-case. */
export const PcCaseIcon = createLucideIcon("pc-case", pcCase);
