/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { penTool } from "../registry.js";

/** Renders the "pen-tool" icon from https://lucide.dev/icons/pen-tool. */
export const PenToolIcon = createLucideIcon("pen-tool", penTool);
