/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { penOff } from "../registry.js";

/** Renders the "pen-off" icon from https://lucide.dev/icons/pen-off. */
export const PenOffIcon = createLucideIcon("pen-off", penOff);
