/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { pencilOff } from "../registry.js";

/** Renders the "pencil-off" icon from https://lucide.dev/icons/pencil-off. */
export const PencilOffIcon = createLucideIcon("pencil-off", pencilOff);
