/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { philippinePeso } from "../registry.js";

/** Renders the "philippine-peso" icon from https://lucide.dev/icons/philippine-peso. */
export const PhilippinePesoIcon = createLucideIcon("philippine-peso", philippinePeso);
