/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { phoneIncoming } from "../registry.js";

/** Renders the "phone-incoming" icon from https://lucide.dev/icons/phone-incoming. */
export const PhoneIncomingIcon = createLucideIcon("phone-incoming", phoneIncoming);
