/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { phoneForwarded } from "../registry.js";

/** Renders the "phone-forwarded" icon from https://lucide.dev/icons/phone-forwarded. */
export const PhoneForwardedIcon = createLucideIcon("phone-forwarded", phoneForwarded);
