/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { phoneOutgoing } from "../registry.js";

/** Renders the "phone-outgoing" icon from https://lucide.dev/icons/phone-outgoing. */
export const PhoneOutgoingIcon = createLucideIcon("phone-outgoing", phoneOutgoing);
