/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { phoneMissed } from "../registry.js";

/** Renders the "phone-missed" icon from https://lucide.dev/icons/phone-missed. */
export const PhoneMissedIcon = createLucideIcon("phone-missed", phoneMissed);
