/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { pictureInPicture2 } from "../registry.js";

/** Renders the "picture-in-picture-2" icon from https://lucide.dev/icons/picture-in-picture-2. */
export const PictureInPicture2Icon = createLucideIcon("picture-in-picture-2", pictureInPicture2);
