/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { pinOff } from "../registry.js";

/** Renders the "pin-off" icon from https://lucide.dev/icons/pin-off. */
export const PinOffIcon = createLucideIcon("pin-off", pinOff);
