/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { plugZap } from "../registry.js";

/** Renders the "plug-zap" icon from https://lucide.dev/icons/plug-zap. */
export const PlugZapIcon = createLucideIcon("plug-zap", plugZap);
