/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { plus } from "../registry.js";

/** Renders the "plus" icon from https://lucide.dev/icons/plus. */
export const PlusIcon = createLucideIcon("plus", plus);
