/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { podcast } from "../registry.js";

/** Renders the "podcast" icon from https://lucide.dev/icons/podcast. */
export const PodcastIcon = createLucideIcon("podcast", podcast);
