/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { powerOff } from "../registry.js";

/** Renders the "power-off" icon from https://lucide.dev/icons/power-off. */
export const PowerOffIcon = createLucideIcon("power-off", powerOff);
