/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { projector } from "../registry.js";

/** Renders the "projector" icon from https://lucide.dev/icons/projector. */
export const ProjectorIcon = createLucideIcon("projector", projector);
