/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { quote } from "../registry.js";

/** Renders the "quote" icon from https://lucide.dev/icons/quote. */
export const QuoteIcon = createLucideIcon("quote", quote);
