/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { radius } from "../registry.js";

/** Renders the "radius" icon from https://lucide.dev/icons/radius. */
export const RadiusIcon = createLucideIcon("radius", radius);
