/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { radioOff } from "../registry.js";

/** Renders the "radio-off" icon from https://lucide.dev/icons/radio-off. */
export const RadioOffIcon = createLucideIcon("radio-off", radioOff);
