/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ratio } from "../registry.js";

/** Renders the "ratio" icon from https://lucide.dev/icons/ratio. */
export const RatioIcon = createLucideIcon("ratio", ratio);
