/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { receiptText } from "../registry.js";

/** Renders the "receipt-text" icon from https://lucide.dev/icons/receipt-text. */
export const ReceiptTextIcon = createLucideIcon("receipt-text", receiptText);
