/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { receiptJapaneseYen } from "../registry.js";

/** Renders the "receipt-japanese-yen" icon from https://lucide.dev/icons/receipt-japanese-yen. */
export const ReceiptJapaneseYenIcon = createLucideIcon("receipt-japanese-yen", receiptJapaneseYen);
