/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rectangleGoggles } from "../registry.js";

/** Renders the "rectangle-goggles" icon from https://lucide.dev/icons/rectangle-goggles. */
export const RectangleGogglesIcon = createLucideIcon("rectangle-goggles", rectangleGoggles);
