/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { refreshCw } from "../registry.js";

/** Renders the "refresh-cw" icon from https://lucide.dev/icons/refresh-cw. */
export const RefreshCwIcon = createLucideIcon("refresh-cw", refreshCw);
