/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { removeFormatting } from "../registry.js";

/** Renders the "remove-formatting" icon from https://lucide.dev/icons/remove-formatting. */
export const RemoveFormattingIcon = createLucideIcon("remove-formatting", removeFormatting);
