/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { reply } from "../registry.js";

/** Renders the "reply" icon from https://lucide.dev/icons/reply. */
export const ReplyIcon = createLucideIcon("reply", reply);
