/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rewind } from "../registry.js";

/** Renders the "rewind" icon from https://lucide.dev/icons/rewind. */
export const RewindIcon = createLucideIcon("rewind", rewind);
