/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ribbon } from "../registry.js";

/** Renders the "ribbon" icon from https://lucide.dev/icons/ribbon. */
export const RibbonIcon = createLucideIcon("ribbon", ribbon);
