/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { road } from "../registry.js";

/** Renders the "road" icon from https://lucide.dev/icons/road. */
export const RoadIcon = createLucideIcon("road", road);
