/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rocket } from "../registry.js";

/** Renders the "rocket" icon from https://lucide.dev/icons/rocket. */
export const RocketIcon = createLucideIcon("rocket", rocket);
