/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rollerCoaster } from "../registry.js";

/** Renders the "roller-coaster" icon from https://lucide.dev/icons/roller-coaster. */
export const RollerCoasterIcon = createLucideIcon("roller-coaster", rollerCoaster);
