/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rotateCwSquare } from "../registry.js";

/** Renders the "rotate-cw-square" icon from https://lucide.dev/icons/rotate-cw-square. */
export const RotateCwSquareIcon = createLucideIcon("rotate-cw-square", rotateCwSquare);
