/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rotate3d } from "../registry.js";

/** Renders the "rotate-3d" icon from https://lucide.dev/icons/rotate-3d. */
export const Rotate3dIcon = createLucideIcon("rotate-3d", rotate3d);
