/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rotateCcwKey } from "../registry.js";

/** Renders the "rotate-ccw-key" icon from https://lucide.dev/icons/rotate-ccw-key. */
export const RotateCcwKeyIcon = createLucideIcon("rotate-ccw-key", rotateCcwKey);
