/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { router } from "../registry.js";

/** Renders the "router" icon from https://lucide.dev/icons/router. */
export const RouterIcon = createLucideIcon("router", router);
