/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rows3 } from "../registry.js";

/** Renders the "rows-3" icon from https://lucide.dev/icons/rows-3. */
export const Rows3Icon = createLucideIcon("rows-3", rows3);
