/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rows4 } from "../registry.js";

/** Renders the "rows-4" icon from https://lucide.dev/icons/rows-4. */
export const Rows4Icon = createLucideIcon("rows-4", rows4);
