/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ruler } from "../registry.js";

/** Renders the "ruler" icon from https://lucide.dev/icons/ruler. */
export const RulerIcon = createLucideIcon("ruler", ruler);
