/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rulerDimensionLine } from "../registry.js";

/** Renders the "ruler-dimension-line" icon from https://lucide.dev/icons/ruler-dimension-line. */
export const RulerDimensionLineIcon = createLucideIcon("ruler-dimension-line", rulerDimensionLine);
