/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { russianRuble } from "../registry.js";

/** Renders the "russian-ruble" icon from https://lucide.dev/icons/russian-ruble. */
export const RussianRubleIcon = createLucideIcon("russian-ruble", russianRuble);
