/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sandwich } from "../registry.js";

/** Renders the "sandwich" icon from https://lucide.dev/icons/sandwich. */
export const SandwichIcon = createLucideIcon("sandwich", sandwich);
