/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { satelliteDish } from "../registry.js";

/** Renders the "satellite-dish" icon from https://lucide.dev/icons/satellite-dish. */
export const SatelliteDishIcon = createLucideIcon("satellite-dish", satelliteDish);
