/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { saveAll } from "../registry.js";

/** Renders the "save-all" icon from https://lucide.dev/icons/save-all. */
export const SaveAllIcon = createLucideIcon("save-all", saveAll);
