/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { scissors } from "../registry.js";

/** Renders the "scissors" icon from https://lucide.dev/icons/scissors. */
export const ScissorsIcon = createLucideIcon("scissors", scissors);
