/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { screenShareOff } from "../registry.js";

/** Renders the "screen-share-off" icon from https://lucide.dev/icons/screen-share-off. */
export const ScreenShareOffIcon = createLucideIcon("screen-share-off", screenShareOff);
