/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { screenShare } from "../registry.js";

/** Renders the "screen-share" icon from https://lucide.dev/icons/screen-share. */
export const ScreenShareIcon = createLucideIcon("screen-share", screenShare);
