/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { searchX } from "../registry.js";

/** Renders the "search-x" icon from https://lucide.dev/icons/search-x. */
export const SearchXIcon = createLucideIcon("search-x", searchX);
