/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { searchAlert } from "../registry.js";

/** Renders the "search-alert" icon from https://lucide.dev/icons/search-alert. */
export const SearchAlertIcon = createLucideIcon("search-alert", searchAlert);
