/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { serverCog } from "../registry.js";

/** Renders the "server-cog" icon from https://lucide.dev/icons/server-cog. */
export const ServerCogIcon = createLucideIcon("server-cog", serverCog);
