/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { settings2 } from "../registry.js";

/** Renders the "settings-2" icon from https://lucide.dev/icons/settings-2. */
export const Settings2Icon = createLucideIcon("settings-2", settings2);
