/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { share2 } from "../registry.js";

/** Renders the "share-2" icon from https://lucide.dev/icons/share-2. */
export const Share2Icon = createLucideIcon("share-2", share2);
