/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { share } from "../registry.js";

/** Renders the "share" icon from https://lucide.dev/icons/share. */
export const ShareIcon = createLucideIcon("share", share);
