/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sheet } from "../registry.js";

/** Renders the "sheet" icon from https://lucide.dev/icons/sheet. */
export const SheetIcon = createLucideIcon("sheet", sheet);
