/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { shieldCheck } from "../registry.js";

/** Renders the "shield-check" icon from https://lucide.dev/icons/shield-check. */
export const ShieldCheckIcon = createLucideIcon("shield-check", shieldCheck);
