/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { shrimp } from "../registry.js";

/** Renders the "shrimp" icon from https://lucide.dev/icons/shrimp. */
export const ShrimpIcon = createLucideIcon("shrimp", shrimp);
