/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { signpost } from "../registry.js";

/** Renders the "signpost" icon from https://lucide.dev/icons/signpost. */
export const SignpostIcon = createLucideIcon("signpost", signpost);
