/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { signpostBig } from "../registry.js";

/** Renders the "signpost-big" icon from https://lucide.dev/icons/signpost-big. */
export const SignpostBigIcon = createLucideIcon("signpost-big", signpostBig);
