/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { signature } from "../registry.js";

/** Renders the "signature" icon from https://lucide.dev/icons/signature. */
export const SignatureIcon = createLucideIcon("signature", signature);
