/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { skipForward } from "../registry.js";

/** Renders the "skip-forward" icon from https://lucide.dev/icons/skip-forward. */
export const SkipForwardIcon = createLucideIcon("skip-forward", skipForward);
