/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { smile } from "../registry.js";

/** Renders the "smile" icon from https://lucide.dev/icons/smile. */
export const SmileIcon = createLucideIcon("smile", smile);
