/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sofa } from "../registry.js";

/** Renders the "sofa" icon from https://lucide.dev/icons/sofa. */
export const SofaIcon = createLucideIcon("sofa", sofa);
