/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { space } from "../registry.js";

/** Renders the "space" icon from https://lucide.dev/icons/space. */
export const SpaceIcon = createLucideIcon("space", space);
