/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { splinePointer } from "../registry.js";

/** Renders the "spline-pointer" icon from https://lucide.dev/icons/spline-pointer. */
export const SplinePointerIcon = createLucideIcon("spline-pointer", splinePointer);
