/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sportShoe } from "../registry.js";

/** Renders the "sport-shoe" icon from https://lucide.dev/icons/sport-shoe. */
export const SportShoeIcon = createLucideIcon("sport-shoe", sportShoe);
