/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { spotlight } from "../registry.js";

/** Renders the "spotlight" icon from https://lucide.dev/icons/spotlight. */
export const SpotlightIcon = createLucideIcon("spotlight", spotlight);
