/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sprout } from "../registry.js";

/** Renders the "sprout" icon from https://lucide.dev/icons/sprout. */
export const SproutIcon = createLucideIcon("sprout", sprout);
