/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squarePen } from "../registry.js";

/** Renders the "square-pen" icon from https://lucide.dev/icons/square-pen. */
export const SquarePenIcon = createLucideIcon("square-pen", squarePen);
