/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squarePercent } from "../registry.js";

/** Renders the "square-percent" icon from https://lucide.dev/icons/square-percent. */
export const SquarePercentIcon = createLucideIcon("square-percent", squarePercent);
