/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareRoundCorner } from "../registry.js";

/** Renders the "square-round-corner" icon from https://lucide.dev/icons/square-round-corner. */
export const SquareRoundCornerIcon = createLucideIcon("square-round-corner", squareRoundCorner);
