/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squarePause } from "../registry.js";

/** Renders the "square-pause" icon from https://lucide.dev/icons/square-pause. */
export const SquarePauseIcon = createLucideIcon("square-pause", squarePause);
