/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squaresSubtract } from "../registry.js";

/** Renders the "squares-subtract" icon from https://lucide.dev/icons/squares-subtract. */
export const SquaresSubtractIcon = createLucideIcon("squares-subtract", squaresSubtract);
