/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareChevronUp } from "../registry.js";

/** Renders the "square-chevron-up" icon from https://lucide.dev/icons/square-chevron-up. */
export const SquareChevronUpIcon = createLucideIcon("square-chevron-up", squareChevronUp);
