/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareDashedKanban } from "../registry.js";

/** Renders the "square-dashed-kanban" icon from https://lucide.dev/icons/square-dashed-kanban. */
export const SquareDashedKanbanIcon = createLucideIcon("square-dashed-kanban", squareDashedKanban);
