/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareDashedBottom } from "../registry.js";

/** Renders the "square-dashed-bottom" icon from https://lucide.dev/icons/square-dashed-bottom. */
export const SquareDashedBottomIcon = createLucideIcon("square-dashed-bottom", squareDashedBottom);
