/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squaresUnite } from "../registry.js";

/** Renders the "squares-unite" icon from https://lucide.dev/icons/squares-unite. */
export const SquaresUniteIcon = createLucideIcon("squares-unite", squaresUnite);
