/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareSplitHorizontal } from "../registry.js";

/** Renders the "square-split-horizontal" icon from https://lucide.dev/icons/square-split-horizontal. */
export const SquareSplitHorizontalIcon = createLucideIcon(
	"square-split-horizontal",
	squareSplitHorizontal,
);
