/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareArrowRightExit } from "../registry.js";

/** Renders the "square-arrow-right-exit" icon from https://lucide.dev/icons/square-arrow-right-exit. */
export const SquareArrowRightExitIcon = createLucideIcon(
	"square-arrow-right-exit",
	squareArrowRightExit,
);
