/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareParkingOff } from "../registry.js";

/** Renders the "square-parking-off" icon from https://lucide.dev/icons/square-parking-off. */
export const SquareParkingOffIcon = createLucideIcon("square-parking-off", squareParkingOff);
