/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareCenterlineDashedHorizontal } from "../registry.js";

/** Renders the "square-centerline-dashed-horizontal" icon from https://lucide.dev/icons/square-centerline-dashed-horizontal. */
export const SquareCenterlineDashedHorizontalIcon = createLucideIcon(
	"square-centerline-dashed-horizontal",
	squareCenterlineDashedHorizontal,
);
