/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareStop } from "../registry.js";

/** Renders the "square-stop" icon from https://lucide.dev/icons/square-stop. */
export const SquareStopIcon = createLucideIcon("square-stop", squareStop);
