/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareArrowOutDownLeft } from "../registry.js";

/** Renders the "square-arrow-out-down-left" icon from https://lucide.dev/icons/square-arrow-out-down-left. */
export const SquareArrowOutDownLeftIcon = createLucideIcon(
	"square-arrow-out-down-left",
	squareArrowOutDownLeft,
);
