/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareSplitVertical } from "../registry.js";

/** Renders the "square-split-vertical" icon from https://lucide.dev/icons/square-split-vertical. */
export const SquareSplitVerticalIcon = createLucideIcon(
	"square-split-vertical",
	squareSplitVertical,
);
