/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squaresExclude } from "../registry.js";

/** Renders the "squares-exclude" icon from https://lucide.dev/icons/squares-exclude. */
export const SquaresExcludeIcon = createLucideIcon("squares-exclude", squaresExclude);
