/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squarePilcrow } from "../registry.js";

/** Renders the "square-pilcrow" icon from https://lucide.dev/icons/square-pilcrow. */
export const SquarePilcrowIcon = createLucideIcon("square-pilcrow", squarePilcrow);
