/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareDashedText } from "../registry.js";

/** Renders the "square-dashed-text" icon from https://lucide.dev/icons/square-dashed-text. */
export const SquareDashedTextIcon = createLucideIcon("square-dashed-text", squareDashedText);
