/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squarePlus } from "../registry.js";

/** Renders the "square-plus" icon from https://lucide.dev/icons/square-plus. */
export const SquarePlusIcon = createLucideIcon("square-plus", squarePlus);
