/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareCode } from "../registry.js";

/** Renders the "square-code" icon from https://lucide.dev/icons/square-code. */
export const SquareCodeIcon = createLucideIcon("square-code", squareCode);
