/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { stamp } from "../registry.js";

/** Renders the "stamp" icon from https://lucide.dev/icons/stamp. */
export const StampIcon = createLucideIcon("stamp", stamp);
