/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { starOff } from "../registry.js";

/** Renders the "star-off" icon from https://lucide.dev/icons/star-off. */
export const StarOffIcon = createLucideIcon("star-off", starOff);
