/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { starCheck } from "../registry.js";

/** Renders the "star-check" icon from https://lucide.dev/icons/star-check. */
export const StarCheckIcon = createLucideIcon("star-check", starCheck);
