/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { stickyNotes } from "../registry.js";

/** Renders the "sticky-notes" icon from https://lucide.dev/icons/sticky-notes. */
export const StickyNotesIcon = createLucideIcon("sticky-notes", stickyNotes);
