/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { stickyNoteCheck } from "../registry.js";

/** Renders the "sticky-note-check" icon from https://lucide.dev/icons/sticky-note-check. */
export const StickyNoteCheckIcon = createLucideIcon("sticky-note-check", stickyNoteCheck);
