/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { stone } from "../registry.js";

/** Renders the "stone" icon from https://lucide.dev/icons/stone. */
export const StoneIcon = createLucideIcon("stone", stone);
