/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { stretchHorizontal } from "../registry.js";

/** Renders the "stretch-horizontal" icon from https://lucide.dev/icons/stretch-horizontal. */
export const StretchHorizontalIcon = createLucideIcon("stretch-horizontal", stretchHorizontal);
