/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sunset } from "../registry.js";

/** Renders the "sunset" icon from https://lucide.dev/icons/sunset. */
export const SunsetIcon = createLucideIcon("sunset", sunset);
