/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { swissFranc } from "../registry.js";

/** Renders the "swiss-franc" icon from https://lucide.dev/icons/swiss-franc. */
export const SwissFrancIcon = createLucideIcon("swiss-franc", swissFranc);
