/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { switchCamera } from "../registry.js";

/** Renders the "switch-camera" icon from https://lucide.dev/icons/switch-camera. */
export const SwitchCameraIcon = createLucideIcon("switch-camera", switchCamera);
