/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { table2 } from "../registry.js";

/** Renders the "table-2" icon from https://lucide.dev/icons/table-2. */
export const Table2Icon = createLucideIcon("table-2", table2);
