/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tableColumnsSplit } from "../registry.js";

/** Renders the "table-columns-split" icon from https://lucide.dev/icons/table-columns-split. */
export const TableColumnsSplitIcon = createLucideIcon("table-columns-split", tableColumnsSplit);
