/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tagX } from "../registry.js";

/** Renders the "tag-x" icon from https://lucide.dev/icons/tag-x. */
export const TagXIcon = createLucideIcon("tag-x", tagX);
