/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tag } from "../registry.js";

/** Renders the "tag" icon from https://lucide.dev/icons/tag. */
export const TagIcon = createLucideIcon("tag", tag);
