/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tags } from "../registry.js";

/** Renders the "tags" icon from https://lucide.dev/icons/tags. */
export const TagsIcon = createLucideIcon("tags", tags);
