/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { testTubes } from "../registry.js";

/** Renders the "test-tubes" icon from https://lucide.dev/icons/test-tubes. */
export const TestTubesIcon = createLucideIcon("test-tubes", testTubes);
