/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { textCursor } from "../registry.js";

/** Renders the "text-cursor" icon from https://lucide.dev/icons/text-cursor. */
export const TextCursorIcon = createLucideIcon("text-cursor", textCursor);
