/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { textSearch } from "../registry.js";

/** Renders the "text-search" icon from https://lucide.dev/icons/text-search. */
export const TextSearchIcon = createLucideIcon("text-search", textSearch);
