/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { textAlignJustify } from "../registry.js";

/** Renders the "text-align-justify" icon from https://lucide.dev/icons/text-align-justify. */
export const TextAlignJustifyIcon = createLucideIcon("text-align-justify", textAlignJustify);
