/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { textAlignStart } from "../registry.js";

/** Renders the "text-align-start" icon from https://lucide.dev/icons/text-align-start. */
export const TextAlignStartIcon = createLucideIcon("text-align-start", textAlignStart);
