/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { thermometerSun } from "../registry.js";

/** Renders the "thermometer-sun" icon from https://lucide.dev/icons/thermometer-sun. */
export const ThermometerSunIcon = createLucideIcon("thermometer-sun", thermometerSun);
