/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { thermometerSnowflake } from "../registry.js";

/** Renders the "thermometer-snowflake" icon from https://lucide.dev/icons/thermometer-snowflake. */
export const ThermometerSnowflakeIcon = createLucideIcon(
	"thermometer-snowflake",
	thermometerSnowflake,
);
