/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ticketMinus } from "../registry.js";

/** Renders the "ticket-minus" icon from https://lucide.dev/icons/ticket-minus. */
export const TicketMinusIcon = createLucideIcon("ticket-minus", ticketMinus);
