/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ticketPercent } from "../registry.js";

/** Renders the "ticket-percent" icon from https://lucide.dev/icons/ticket-percent. */
export const TicketPercentIcon = createLucideIcon("ticket-percent", ticketPercent);
