/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tickets } from "../registry.js";

/** Renders the "tickets" icon from https://lucide.dev/icons/tickets. */
export const TicketsIcon = createLucideIcon("tickets", tickets);
