/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ticketPlus } from "../registry.js";

/** Renders the "ticket-plus" icon from https://lucide.dev/icons/ticket-plus. */
export const TicketPlusIcon = createLucideIcon("ticket-plus", ticketPlus);
