/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { timerReset } from "../registry.js";

/** Renders the "timer-reset" icon from https://lucide.dev/icons/timer-reset. */
export const TimerResetIcon = createLucideIcon("timer-reset", timerReset);
