/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { timerOff } from "../registry.js";

/** Renders the "timer-off" icon from https://lucide.dev/icons/timer-off. */
export const TimerOffIcon = createLucideIcon("timer-off", timerOff);
