/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { toilet } from "../registry.js";

/** Renders the "toilet" icon from https://lucide.dev/icons/toilet. */
export const ToiletIcon = createLucideIcon("toilet", toilet);
