/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { toolbox } from "../registry.js";

/** Renders the "toolbox" icon from https://lucide.dev/icons/toolbox. */
export const ToolboxIcon = createLucideIcon("toolbox", toolbox);
