/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { towelRack } from "../registry.js";

/** Renders the "towel-rack" icon from https://lucide.dev/icons/towel-rack. */
export const TowelRackIcon = createLucideIcon("towel-rack", towelRack);
