/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tractor } from "../registry.js";

/** Renders the "tractor" icon from https://lucide.dev/icons/tractor. */
export const TractorIcon = createLucideIcon("tractor", tractor);
