/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { trafficCone } from "../registry.js";

/** Renders the "traffic-cone" icon from https://lucide.dev/icons/traffic-cone. */
export const TrafficConeIcon = createLucideIcon("traffic-cone", trafficCone);
