/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { trainFront } from "../registry.js";

/** Renders the "train-front" icon from https://lucide.dev/icons/train-front. */
export const TrainFrontIcon = createLucideIcon("train-front", trainFront);
