/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { treeDeciduous } from "../registry.js";

/** Renders the "tree-deciduous" icon from https://lucide.dev/icons/tree-deciduous. */
export const TreeDeciduousIcon = createLucideIcon("tree-deciduous", treeDeciduous);
