/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { trendingUpDown } from "../registry.js";

/** Renders the "trending-up-down" icon from https://lucide.dev/icons/trending-up-down. */
export const TrendingUpDownIcon = createLucideIcon("trending-up-down", trendingUpDown);
