/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { trendingDown } from "../registry.js";

/** Renders the "trending-down" icon from https://lucide.dev/icons/trending-down. */
export const TrendingDownIcon = createLucideIcon("trending-down", trendingDown);
