/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { triangleRight } from "../registry.js";

/** Renders the "triangle-right" icon from https://lucide.dev/icons/triangle-right. */
export const TriangleRightIcon = createLucideIcon("triangle-right", triangleRight);
