/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { triangleAlert } from "../registry.js";

/** Renders the "triangle-alert" icon from https://lucide.dev/icons/triangle-alert. */
export const TriangleAlertIcon = createLucideIcon("triangle-alert", triangleAlert);
