/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { truckElectric } from "../registry.js";

/** Renders the "truck-electric" icon from https://lucide.dev/icons/truck-electric. */
export const TruckElectricIcon = createLucideIcon("truck-electric", truckElectric);
