/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { turtle } from "../registry.js";

/** Renders the "turtle" icon from https://lucide.dev/icons/turtle. */
export const TurtleIcon = createLucideIcon("turtle", turtle);
