/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tv } from "../registry.js";

/** Renders the "tv" icon from https://lucide.dev/icons/tv. */
export const TvIcon = createLucideIcon("tv", tv);
