/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { undoDot } from "../registry.js";

/** Renders the "undo-dot" icon from https://lucide.dev/icons/undo-dot. */
export const UndoDotIcon = createLucideIcon("undo-dot", undoDot);
