/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { unfoldVertical } from "../registry.js";

/** Renders the "unfold-vertical" icon from https://lucide.dev/icons/unfold-vertical. */
export const UnfoldVerticalIcon = createLucideIcon("unfold-vertical", unfoldVertical);
