/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ungroup } from "../registry.js";

/** Renders the "ungroup" icon from https://lucide.dev/icons/ungroup. */
export const UngroupIcon = createLucideIcon("ungroup", ungroup);
