/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { usersRound } from "../registry.js";

/** Renders the "users-round" icon from https://lucide.dev/icons/users-round. */
export const UsersRoundIcon = createLucideIcon("users-round", usersRound);
