/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userRoundKey } from "../registry.js";

/** Renders the "user-round-key" icon from https://lucide.dev/icons/user-round-key. */
export const UserRoundKeyIcon = createLucideIcon("user-round-key", userRoundKey);
