/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userStar } from "../registry.js";

/** Renders the "user-star" icon from https://lucide.dev/icons/user-star. */
export const UserStarIcon = createLucideIcon("user-star", userStar);
