/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userMinus } from "../registry.js";

/** Renders the "user-minus" icon from https://lucide.dev/icons/user-minus. */
export const UserMinusIcon = createLucideIcon("user-minus", userMinus);
