/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userRoundArrowLeft } from "../registry.js";

/** Renders the "user-round-arrow-left" icon from https://lucide.dev/icons/user-round-arrow-left. */
export const UserRoundArrowLeftIcon = createLucideIcon("user-round-arrow-left", userRoundArrowLeft);
