/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { van } from "../registry.js";

/** Renders the "van" icon from https://lucide.dev/icons/van. */
export const VanIcon = createLucideIcon("van", van);
