/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { venetianMask } from "../registry.js";

/** Renders the "venetian-mask" icon from https://lucide.dev/icons/venetian-mask. */
export const VenetianMaskIcon = createLucideIcon("venetian-mask", venetianMask);
