/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { vibrateOff } from "../registry.js";

/** Renders the "vibrate-off" icon from https://lucide.dev/icons/vibrate-off. */
export const VibrateOffIcon = createLucideIcon("vibrate-off", vibrateOff);
