/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { voicemail } from "../registry.js";

/** Renders the "voicemail" icon from https://lucide.dev/icons/voicemail. */
export const VoicemailIcon = createLucideIcon("voicemail", voicemail);
