/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { volume2 } from "../registry.js";

/** Renders the "volume-2" icon from https://lucide.dev/icons/volume-2. */
export const Volume2Icon = createLucideIcon("volume-2", volume2);
