/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { volume1 } from "../registry.js";

/** Renders the "volume-1" icon from https://lucide.dev/icons/volume-1. */
export const Volume1Icon = createLucideIcon("volume-1", volume1);
