/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wallet } from "../registry.js";

/** Renders the "wallet" icon from https://lucide.dev/icons/wallet. */
export const WalletIcon = createLucideIcon("wallet", wallet);
