/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wandSparkles } from "../registry.js";

/** Renders the "wand-sparkles" icon from https://lucide.dev/icons/wand-sparkles. */
export const WandSparklesIcon = createLucideIcon("wand-sparkles", wandSparkles);
