/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { watch } from "../registry.js";

/** Renders the "watch" icon from https://lucide.dev/icons/watch. */
export const WatchIcon = createLucideIcon("watch", watch);
