/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wavesLadder } from "../registry.js";

/** Renders the "waves-ladder" icon from https://lucide.dev/icons/waves-ladder. */
export const WavesLadderIcon = createLucideIcon("waves-ladder", wavesLadder);
