/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wavesArrowDown } from "../registry.js";

/** Renders the "waves-arrow-down" icon from https://lucide.dev/icons/waves-arrow-down. */
export const WavesArrowDownIcon = createLucideIcon("waves-arrow-down", wavesArrowDown);
