/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wavesArrowUp } from "../registry.js";

/** Renders the "waves-arrow-up" icon from https://lucide.dev/icons/waves-arrow-up. */
export const WavesArrowUpIcon = createLucideIcon("waves-arrow-up", wavesArrowUp);
