/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { webcamOff } from "../registry.js";

/** Renders the "webcam-off" icon from https://lucide.dev/icons/webcam-off. */
export const WebcamOffIcon = createLucideIcon("webcam-off", webcamOff);
