/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { webhook } from "../registry.js";

/** Renders the "webhook" icon from https://lucide.dev/icons/webhook. */
export const WebhookIcon = createLucideIcon("webhook", webhook);
