/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wheatOff } from "../registry.js";

/** Renders the "wheat-off" icon from https://lucide.dev/icons/wheat-off. */
export const WheatOffIcon = createLucideIcon("wheat-off", wheatOff);
