/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wheat } from "../registry.js";

/** Renders the "wheat" icon from https://lucide.dev/icons/wheat. */
export const WheatIcon = createLucideIcon("wheat", wheat);
