/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wifiHigh } from "../registry.js";

/** Renders the "wifi-high" icon from https://lucide.dev/icons/wifi-high. */
export const WifiHighIcon = createLucideIcon("wifi-high", wifiHigh);
