/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wine } from "../registry.js";

/** Renders the "wine" icon from https://lucide.dev/icons/wine. */
export const WineIcon = createLucideIcon("wine", wine);
