/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { worm } from "../registry.js";

/** Renders the "worm" icon from https://lucide.dev/icons/worm. */
export const WormIcon = createLucideIcon("worm", worm);
