/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wrench } from "../registry.js";

/** Renders the "wrench" icon from https://lucide.dev/icons/wrench. */
export const WrenchIcon = createLucideIcon("wrench", wrench);
