/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { xLineTop } from "../registry.js";

/** Renders the "x-line-top" icon from https://lucide.dev/icons/x-line-top. */
export const XLineTopIcon = createLucideIcon("x-line-top", xLineTop);
