/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { zodiacOphiuchus } from "../registry.js";

/** Renders the "zodiac-ophiuchus" icon from https://lucide.dev/icons/zodiac-ophiuchus. */
export const ZodiacOphiuchusIcon = createLucideIcon("zodiac-ophiuchus", zodiacOphiuchus);
