/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { zodiacAries } from "../registry.js";

/** Renders the "zodiac-aries" icon from https://lucide.dev/icons/zodiac-aries. */
export const ZodiacAriesIcon = createLucideIcon("zodiac-aries", zodiacAries);
