/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { zodiacAquarius } from "../registry.js";

/** Renders the "zodiac-aquarius" icon from https://lucide.dev/icons/zodiac-aquarius. */
export const ZodiacAquariusIcon = createLucideIcon("zodiac-aquarius", zodiacAquarius);
