/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { zoomIn } from "../registry.js";

/** Renders the "zoom-in" icon from https://lucide.dev/icons/zoom-in. */
export const ZoomInIcon = createLucideIcon("zoom-in", zoomIn);
