/**
 * Covers the extraction the catalogue documents are generated by: the rule that turns
 * a run of `@example` tags into quick-reference rows, the props and compound parts a
 * component page is built from, and the theme contract's three columns. The catalogue
 * writes its calls and its emitted CSS as consecutive tags, and sixteen utilities
 * break the alternation — so the pairing rule is what keeps those sixteen pages from
 * pairing a call with the next call.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { describe, expect, test } from "vitest";

import {
	collectTheme,
	collectUsage,
	componentName,
	pairExamples,
	readBarrel,
	readComponent,
	readUtility,
} from "~/scripts/catalogue";

/** A module shaped like a utility's, small enough to assert over whole. */
const UTILITY_MODULE = `
/**
 * Applies logical padding using the spacing scale or a raw CSS length.
 *
 * @see [MDN: logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values)
 * @example u.p(4)
 * @example css({ padding: "calc(var(--ui-spacing, 0.25rem) * 4)" })
 */
export function p<Node extends Element = Element>(...values: SpacingValue[]) {
	return utility<Node>(() => resolveBox("padding", values));
}
`;

/** A component module carrying every shape a page reads: a union, props, and a part. */
const COMPONENT_MODULE = `
/**
 * A compact pill communicating a short status. It composes with a text part.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 */

export namespace Badge {
	/** Semantic color role. */
	export type Color = SemanticColor;

	/** Visual weight the badge renders with. */
	export type Variant = "default" | "secondary" | "outline";

	export interface Props extends TagProps<"span"> {
		/** Semantic color role, resolved by {@link Badge.Color}. */
		color?: Color;
		/** Visual weight. */
		variant?: Variant;
	}

	export interface TextProps extends TagProps<"span"> {}
}

/**
 * Renders a single-line pill host.
 *
 * @example
 * <Badge>New</Badge>
 */
export function Badge(handle: Handle<Badge.Props>) {
	return () => <span mix={[bg("brand.solid"), fg("neutral")]} />;
}

/**
 * Renders the badge's label slot.
 */
Badge.Text = function BadgeText(handle: Handle<Badge.TextProps>) {
	return () => <span mix={[fg("brand.emphasis")]} />;
};
`;

/** The shared module a component's `Color` resolves through. */
const SHARED_MODULE = `export type SemanticColor = "brand" | "neutral" | "success" | "warning" | "danger";`;

/** A stylesheet shaped like the ones the packages ship. */
const STYLESHEET = `
:root {
	--ui-brand-bg-solid: var(--ui-color-brand-600);
	--ui-brand-fg-on-solid: white;
	--ui-bg: Canvas;
	--ui-text-sm: 0.875rem;
	--ui-chart-1: var(--ui-color-brand-600);
}

:is(.dark, .dark *) {
	--ui-brand-bg-solid: var(--ui-color-brand-500);
	--ui-bg: color-mix(in oklab, Canvas 92%, CanvasText);
}
`;

describe("pairExamples", () => {
	test("pairs a call with the css it emits", () => {
		expect(pairExamples(["u.p(4)", 'css({ padding: "1rem" })'])).toEqual([
			{ call: "u.p(4)", output: 'css({ padding: "1rem" })' },
		]);
	});

	test("pairs every call in a run of pairs", () => {
		let rows = pairExamples([
			'u.justify("between")',
			'css({ justifyContent: "space-between" })',
			'u.justify("center")',
			'css({ justifyContent: "center" })',
		]);

		expect(rows).toHaveLength(2);
		expect(rows[1]).toEqual({
			call: 'u.justify("center")',
			output: 'css({ justifyContent: "center" })',
		});
	});

	test("pairs a call with a quoted value, which is what a bare-value utility emits", () => {
		expect(pairExamples(['u.var("--sidebar-width")', '"var(--sidebar-width)"'])).toEqual([
			{ call: 'u.var("--sidebar-width")', output: '"var(--sidebar-width)"' },
		]);
	});

	test("leaves a composition utility standing alone, since it emits nothing of its own", () => {
		expect(pairExamples(['u.dark(u.bg("neutral.solid"))', 'u.light(u.bg("neutral.bg"))'])).toEqual([
			{ call: 'u.dark(u.bg("neutral.solid"))', output: null },
			{ call: 'u.light(u.bg("neutral.bg"))', output: null },
		]);
	});

	test("keeps a trailing call unpaired when the run ends on one", () => {
		let rows = pairExamples([
			"u.autofill()",
			'css({ "&:-webkit-autofill": { color: "..." } })',
			'u.autofill("neutral.tint", "neutral")',
		]);

		expect(rows).toHaveLength(2);
		expect(rows[1]?.output).toBeNull();
	});

	test("reads a multi-line output, which is how a keyframed utility writes one", () => {
		let output = 'css({\n  "@keyframes fade-in": { from: { opacity: 0 } },\n})';

		expect(pairExamples(['u.animation("fade-in")', output])).toEqual([
			{ call: 'u.animation("fade-in")', output },
		]);
	});

	test("reports nothing for a utility with no examples", () => {
		expect(pairExamples([])).toEqual([]);
	});
});

describe("readBarrel", () => {
	test("names every value export and the module it comes from", () => {
		let source = [
			'export { absolute } from "./absolute.js";',
			'export type { AnchorSide } from "./anchor.js";',
			'export { anchor, anchorName } from "./anchor.js";',
		].join("\n");

		expect(readBarrel(source, "layout")).toEqual([
			{ name: "absolute", family: "layout", module: "absolute" },
			{ name: "anchor", family: "layout", module: "anchor" },
			{ name: "anchorName", family: "layout", module: "anchor" },
		]);
	});
});

describe("readUtility", () => {
	test("titles a page after the property its first example emits", () => {
		let reference = readUtility(UTILITY_MODULE, { name: "p", family: "size", module: "p" });

		expect(reference?.property).toBe("padding");
		expect(reference?.signature).toBe("u.p(...values: SpacingValue[])");
		expect(reference?.see[0]?.href).toContain("developer.mozilla.org");
		expect(reference?.tokens).toEqual(["--ui-spacing"]);
	});

	test("reports nothing for a name the module does not declare", () => {
		expect(readUtility(UTILITY_MODULE, { name: "m", family: "size", module: "p" })).toBeNull();
	});
});

describe("readComponent", () => {
	test("opens with what the pattern is, which the module's own comment states", () => {
		let reference = readComponent(COMPONENT_MODULE, "badge", [SHARED_MODULE]);

		expect(reference?.name).toBe("Badge");
		expect(reference?.summary).toBe("A compact pill communicating a short status.");
		expect(reference?.description).toBe("Renders a single-line pill host.");
		expect(reference?.examples).toEqual(["<Badge>New</Badge>"]);
	});

	test("lists a prop's allowed values rather than the name of its union", () => {
		let reference = readComponent(COMPONENT_MODULE, "badge", [SHARED_MODULE]);
		let rows = reference?.props.rows ?? [];

		expect(rows.find((row) => row.name === "variant")?.values).toEqual([
			'"default"',
			'"secondary"',
			'"outline"',
		]);
		expect(rows.find((row) => row.name === "color")?.values).toEqual([
			'"brand"',
			'"neutral"',
			'"success"',
			'"warning"',
			'"danger"',
		]);
	});

	test("resolves an inline link to what it names", () => {
		let reference = readComponent(COMPONENT_MODULE, "badge", [SHARED_MODULE]);
		let color = reference?.props.rows.find((row) => row.name === "color");

		expect(color?.description).toBe("Semantic color role, resolved by Badge.Color.");
	});

	test("reads the compound parts and what each interface inherits", () => {
		let reference = readComponent(COMPONENT_MODULE, "badge", [SHARED_MODULE]);

		expect(reference?.parts.map((part) => part.name)).toEqual(["Badge.Text"]);
		expect(reference?.parts[0]?.props.inherits).toEqual(['TagProps<"span">']);
		expect(reference?.props.inherits).toEqual(['TagProps<"span">']);
	});
});

describe("componentName", () => {
	test("reads the exported name rather than spelling the file name back", () => {
		expect(componentName(COMPONENT_MODULE)).toBe("Badge");
		expect(componentName("export const x = 1;")).toBeNull();
	});
});

describe("collectUsage", () => {
	test("finds a component reaching a token through a mixin rather than by name", () => {
		let usage = collectUsage([COMPONENT_MODULE]);

		expect(Array.from(usage.get("--ui-brand-bg-solid") ?? [])).toEqual(["Badge"]);
		expect(Array.from(usage.get("--ui-neutral-fg") ?? [])).toEqual(["Badge"]);
		expect(Array.from(usage.get("--ui-brand-fg-emphasis") ?? [])).toEqual(["Badge"]);
	});
});

describe("collectTheme", () => {
	test("groups the tone variables under the tone that names them", () => {
		let theme = collectTheme([STYLESHEET], collectUsage([COMPONENT_MODULE]));
		let brand = theme.groups.find((group) => group.title === "brand");

		expect(brand?.tokens.map((token) => token.name)).toEqual([
			"--ui-brand-bg-solid",
			"--ui-brand-fg-on-solid",
		]);
		expect(brand?.tokens[0]?.components).toEqual(["Badge"]);
		expect(brand?.tokens[1]?.controls).toBe("Text drawn on the solid fill");
	});

	test("bands the variables that belong to no tone by the scale they name", () => {
		let theme = collectTheme([STYLESHEET], new Map());

		expect(theme.groups.map((group) => group.title)).toEqual([
			"brand",
			"surface",
			"type scale",
			"chart",
		]);
	});

	test("carries both schemes over the same names", () => {
		let theme = collectTheme([STYLESHEET], new Map());
		let names = new Set(theme.light.map((declaration) => declaration.name));

		expect(theme.dark).toHaveLength(2);
		expect(theme.dark.every((declaration) => names.has(declaration.name))).toBe(true);
		expect(theme.dark[0]?.value).toBe("var(--ui-color-brand-500)");
	});
});
