/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { airplay } from "../registry.js";

/** Renders the "airplay" icon from https://lucide.dev/icons/airplay. */
export const AirplayIcon = createLucideIcon("airplay", airplay);
