/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alarmClock } from "../registry.js";

/** Renders the "alarm-clock" icon from https://lucide.dev/icons/alarm-clock. */
export const AlarmClockIcon = createLucideIcon("alarm-clock", alarmClock);
