/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alarmClockPlus } from "../registry.js";

/** Renders the "alarm-clock-plus" icon from https://lucide.dev/icons/alarm-clock-plus. */
export const AlarmClockPlusIcon = createLucideIcon("alarm-clock-plus", alarmClockPlus);
