/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignStartVertical } from "../registry.js";

/** Renders the "align-start-vertical" icon from https://lucide.dev/icons/align-start-vertical. */
export const AlignStartVerticalIcon = createLucideIcon("align-start-vertical", alignStartVertical);
