/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignHorizontalJustifyCenter } from "../registry.js";

/** Renders the "align-horizontal-justify-center" icon from https://lucide.dev/icons/align-horizontal-justify-center. */
export const AlignHorizontalJustifyCenterIcon = createLucideIcon(
	"align-horizontal-justify-center",
	alignHorizontalJustifyCenter,
);
