/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignVerticalSpaceBetween } from "../registry.js";

/** Renders the "align-vertical-space-between" icon from https://lucide.dev/icons/align-vertical-space-between. */
export const AlignVerticalSpaceBetweenIcon = createLucideIcon(
	"align-vertical-space-between",
	alignVerticalSpaceBetween,
);
