/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignCenterHorizontal } from "../registry.js";

/** Renders the "align-center-horizontal" icon from https://lucide.dev/icons/align-center-horizontal. */
export const AlignCenterHorizontalIcon = createLucideIcon(
	"align-center-horizontal",
	alignCenterHorizontal,
);
