/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { alignVerticalDistributeEnd } from "../registry.js";

/** Renders the "align-vertical-distribute-end" icon from https://lucide.dev/icons/align-vertical-distribute-end. */
export const AlignVerticalDistributeEndIcon = createLucideIcon(
	"align-vertical-distribute-end",
	alignVerticalDistributeEnd,
);
