/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ambulance } from "../registry.js";

/** Renders the "ambulance" icon from https://lucide.dev/icons/ambulance. */
export const AmbulanceIcon = createLucideIcon("ambulance", ambulance);
