/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ampersand } from "../registry.js";

/** Renders the "ampersand" icon from https://lucide.dev/icons/ampersand. */
export const AmpersandIcon = createLucideIcon("ampersand", ampersand);
