/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { annoyed } from "../registry.js";

/** Renders the "annoyed" icon from https://lucide.dev/icons/annoyed. */
export const AnnoyedIcon = createLucideIcon("annoyed", annoyed);
