/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { appWindowMac } from "../registry.js";

/** Renders the "app-window-mac" icon from https://lucide.dev/icons/app-window-mac. */
export const AppWindowMacIcon = createLucideIcon("app-window-mac", appWindowMac);
