/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowDown01 } from "../registry.js";

/** Renders the "arrow-down-0-1" icon from https://lucide.dev/icons/arrow-down-0-1. */
export const ArrowDown01Icon = createLucideIcon("arrow-down-0-1", arrowDown01);
