/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowUpWideNarrow } from "../registry.js";

/** Renders the "arrow-up-wide-narrow" icon from https://lucide.dev/icons/arrow-up-wide-narrow. */
export const ArrowUpWideNarrowIcon = createLucideIcon("arrow-up-wide-narrow", arrowUpWideNarrow);
