/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowDownUp } from "../registry.js";

/** Renders the "arrow-down-up" icon from https://lucide.dev/icons/arrow-down-up. */
export const ArrowDownUpIcon = createLucideIcon("arrow-down-up", arrowDownUp);
