/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowBigRight } from "../registry.js";

/** Renders the "arrow-big-right" icon from https://lucide.dev/icons/arrow-big-right. */
export const ArrowBigRightIcon = createLucideIcon("arrow-big-right", arrowBigRight);
