/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowBigLeft } from "../registry.js";

/** Renders the "arrow-big-left" icon from https://lucide.dev/icons/arrow-big-left. */
export const ArrowBigLeftIcon = createLucideIcon("arrow-big-left", arrowBigLeft);
