/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowUpNarrowWide } from "../registry.js";

/** Renders the "arrow-up-narrow-wide" icon from https://lucide.dev/icons/arrow-up-narrow-wide. */
export const ArrowUpNarrowWideIcon = createLucideIcon("arrow-up-narrow-wide", arrowUpNarrowWide);
