/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowUpFromLine } from "../registry.js";

/** Renders the "arrow-up-from-line" icon from https://lucide.dev/icons/arrow-up-from-line. */
export const ArrowUpFromLineIcon = createLucideIcon("arrow-up-from-line", arrowUpFromLine);
