/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { arrowRightLeft } from "../registry.js";

/** Renders the "arrow-right-left" icon from https://lucide.dev/icons/arrow-right-left. */
export const ArrowRightLeftIcon = createLucideIcon("arrow-right-left", arrowRightLeft);
