/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { atSign } from "../registry.js";

/** Renders the "at-sign" icon from https://lucide.dev/icons/at-sign. */
export const AtSignIcon = createLucideIcon("at-sign", atSign);
