/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { badgeIndianRupee } from "../registry.js";

/** Renders the "badge-indian-rupee" icon from https://lucide.dev/icons/badge-indian-rupee. */
export const BadgeIndianRupeeIcon = createLucideIcon("badge-indian-rupee", badgeIndianRupee);
