/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { badgeAlert } from "../registry.js";

/** Renders the "badge-alert" icon from https://lucide.dev/icons/badge-alert. */
export const BadgeAlertIcon = createLucideIcon("badge-alert", badgeAlert);
