/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { badgeMinus } from "../registry.js";

/** Renders the "badge-minus" icon from https://lucide.dev/icons/badge-minus. */
export const BadgeMinusIcon = createLucideIcon("badge-minus", badgeMinus);
