/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { balloon } from "../registry.js";

/** Renders the "balloon" icon from https://lucide.dev/icons/balloon. */
export const BalloonIcon = createLucideIcon("balloon", balloon);
