/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ban } from "../registry.js";

/** Renders the "ban" icon from https://lucide.dev/icons/ban. */
export const BanIcon = createLucideIcon("ban", ban);
