/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { banknoteX } from "../registry.js";

/** Renders the "banknote-x" icon from https://lucide.dev/icons/banknote-x. */
export const BanknoteXIcon = createLucideIcon("banknote-x", banknoteX);
