/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { barcode } from "../registry.js";

/** Renders the "barcode" icon from https://lucide.dev/icons/barcode. */
export const BarcodeIcon = createLucideIcon("barcode", barcode);
