/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { beanOff } from "../registry.js";

/** Renders the "bean-off" icon from https://lucide.dev/icons/bean-off. */
export const BeanOffIcon = createLucideIcon("bean-off", beanOff);
