/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bellOff } from "../registry.js";

/** Renders the "bell-off" icon from https://lucide.dev/icons/bell-off. */
export const BellOffIcon = createLucideIcon("bell-off", bellOff);
