/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bellPlus } from "../registry.js";

/** Renders the "bell-plus" icon from https://lucide.dev/icons/bell-plus. */
export const BellPlusIcon = createLucideIcon("bell-plus", bellPlus);
