/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { betweenVerticalStart } from "../registry.js";

/** Renders the "between-vertical-start" icon from https://lucide.dev/icons/between-vertical-start. */
export const BetweenVerticalStartIcon = createLucideIcon(
	"between-vertical-start",
	betweenVerticalStart,
);
