/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { betweenHorizontalEnd } from "../registry.js";

/** Renders the "between-horizontal-end" icon from https://lucide.dev/icons/between-horizontal-end. */
export const BetweenHorizontalEndIcon = createLucideIcon(
	"between-horizontal-end",
	betweenHorizontalEnd,
);
