/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bicepsFlexed } from "../registry.js";

/** Renders the "biceps-flexed" icon from https://lucide.dev/icons/biceps-flexed. */
export const BicepsFlexedIcon = createLucideIcon("biceps-flexed", bicepsFlexed);
