/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { blend } from "../registry.js";

/** Renders the "blend" icon from https://lucide.dev/icons/blend. */
export const BlendIcon = createLucideIcon("blend", blend);
