/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { blinds } from "../registry.js";

/** Renders the "blinds" icon from https://lucide.dev/icons/blinds. */
export const BlindsIcon = createLucideIcon("blinds", blinds);
