/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookA } from "../registry.js";

/** Renders the "book-a" icon from https://lucide.dev/icons/book-a. */
export const BookAIcon = createLucideIcon("book-a", bookA);
