/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookMarked } from "../registry.js";

/** Renders the "book-marked" icon from https://lucide.dev/icons/book-marked. */
export const BookMarkedIcon = createLucideIcon("book-marked", bookMarked);
