/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookHeart } from "../registry.js";

/** Renders the "book-heart" icon from https://lucide.dev/icons/book-heart. */
export const BookHeartIcon = createLucideIcon("book-heart", bookHeart);
