/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { book } from "../registry.js";

/** Renders the "book" icon from https://lucide.dev/icons/book. */
export const BookIcon = createLucideIcon("book", book);
