/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bookDown } from "../registry.js";

/** Renders the "book-down" icon from https://lucide.dev/icons/book-down. */
export const BookDownIcon = createLucideIcon("book-down", bookDown);
