/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { bowArrow } from "../registry.js";

/** Renders the "bow-arrow" icon from https://lucide.dev/icons/bow-arrow. */
export const BowArrowIcon = createLucideIcon("bow-arrow", bowArrow);
