/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { brainCircuit } from "../registry.js";

/** Renders the "brain-circuit" icon from https://lucide.dev/icons/brain-circuit. */
export const BrainCircuitIcon = createLucideIcon("brain-circuit", brainCircuit);
