/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { brickWallShield } from "../registry.js";

/** Renders the "brick-wall-shield" icon from https://lucide.dev/icons/brick-wall-shield. */
export const BrickWallShieldIcon = createLucideIcon("brick-wall-shield", brickWallShield);
