/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { brush } from "../registry.js";

/** Renders the "brush" icon from https://lucide.dev/icons/brush. */
export const BrushIcon = createLucideIcon("brush", brush);
