/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { building2 } from "../registry.js";

/** Renders the "building-2" icon from https://lucide.dev/icons/building-2. */
export const Building2Icon = createLucideIcon("building-2", building2);
