/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarX } from "../registry.js";

/** Renders the "calendar-x" icon from https://lucide.dev/icons/calendar-x. */
export const CalendarXIcon = createLucideIcon("calendar-x", calendarX);
