/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarCheck2 } from "../registry.js";

/** Renders the "calendar-check-2" icon from https://lucide.dev/icons/calendar-check-2. */
export const CalendarCheck2Icon = createLucideIcon("calendar-check-2", calendarCheck2);
