/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarX2 } from "../registry.js";

/** Renders the "calendar-x-2" icon from https://lucide.dev/icons/calendar-x-2. */
export const CalendarX2Icon = createLucideIcon("calendar-x-2", calendarX2);
