/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarMinus2 } from "../registry.js";

/** Renders the "calendar-minus-2" icon from https://lucide.dev/icons/calendar-minus-2. */
export const CalendarMinus2Icon = createLucideIcon("calendar-minus-2", calendarMinus2);
