/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarPlus } from "../registry.js";

/** Renders the "calendar-plus" icon from https://lucide.dev/icons/calendar-plus. */
export const CalendarPlusIcon = createLucideIcon("calendar-plus", calendarPlus);
