/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { calendarFold } from "../registry.js";

/** Renders the "calendar-fold" icon from https://lucide.dev/icons/calendar-fold. */
export const CalendarFoldIcon = createLucideIcon("calendar-fold", calendarFold);
