/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { candyCane } from "../registry.js";

/** Renders the "candy-cane" icon from https://lucide.dev/icons/candy-cane. */
export const CandyCaneIcon = createLucideIcon("candy-cane", candyCane);
