/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartNoAxesColumnDecreasing } from "../registry.js";

/** Renders the "chart-no-axes-column-decreasing" icon from https://lucide.dev/icons/chart-no-axes-column-decreasing. */
export const ChartNoAxesColumnDecreasingIcon = createLucideIcon(
	"chart-no-axes-column-decreasing",
	chartNoAxesColumnDecreasing,
);
