/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartBarBig } from "../registry.js";

/** Renders the "chart-bar-big" icon from https://lucide.dev/icons/chart-bar-big. */
export const ChartBarBigIcon = createLucideIcon("chart-bar-big", chartBarBig);
