/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartNetwork } from "../registry.js";

/** Renders the "chart-network" icon from https://lucide.dev/icons/chart-network. */
export const ChartNetworkIcon = createLucideIcon("chart-network", chartNetwork);
