/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartArea } from "../registry.js";

/** Renders the "chart-area" icon from https://lucide.dev/icons/chart-area. */
export const ChartAreaIcon = createLucideIcon("chart-area", chartArea);
