/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartNoAxesGantt } from "../registry.js";

/** Renders the "chart-no-axes-gantt" icon from https://lucide.dev/icons/chart-no-axes-gantt. */
export const ChartNoAxesGanttIcon = createLucideIcon("chart-no-axes-gantt", chartNoAxesGantt);
