/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartColumnStacked } from "../registry.js";

/** Renders the "chart-column-stacked" icon from https://lucide.dev/icons/chart-column-stacked. */
export const ChartColumnStackedIcon = createLucideIcon("chart-column-stacked", chartColumnStacked);
