/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chartColumnDecreasing } from "../registry.js";

/** Renders the "chart-column-decreasing" icon from https://lucide.dev/icons/chart-column-decreasing. */
export const ChartColumnDecreasingIcon = createLucideIcon(
	"chart-column-decreasing",
	chartColumnDecreasing,
);
