/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { check } from "../registry.js";

/** Renders the "check" icon from https://lucide.dev/icons/check. */
export const CheckIcon = createLucideIcon("check", check);
