/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chessQueen } from "../registry.js";

/** Renders the "chess-queen" icon from https://lucide.dev/icons/chess-queen. */
export const ChessQueenIcon = createLucideIcon("chess-queen", chessQueen);
