/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chessKnight } from "../registry.js";

/** Renders the "chess-knight" icon from https://lucide.dev/icons/chess-knight. */
export const ChessKnightIcon = createLucideIcon("chess-knight", chessKnight);
