/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chevronsDown } from "../registry.js";

/** Renders the "chevrons-down" icon from https://lucide.dev/icons/chevrons-down. */
export const ChevronsDownIcon = createLucideIcon("chevrons-down", chevronsDown);
