/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { chevronRight } from "../registry.js";

/** Renders the "chevron-right" icon from https://lucide.dev/icons/chevron-right. */
export const ChevronRightIcon = createLucideIcon("chevron-right", chevronRight);
