/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circlePlay } from "../registry.js";

/** Renders the "circle-play" icon from https://lucide.dev/icons/circle-play. */
export const CirclePlayIcon = createLucideIcon("circle-play", circlePlay);
