/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circlePoundSterling } from "../registry.js";

/** Renders the "circle-pound-sterling" icon from https://lucide.dev/icons/circle-pound-sterling. */
export const CirclePoundSterlingIcon = createLucideIcon(
	"circle-pound-sterling",
	circlePoundSterling,
);
