/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circlePile } from "../registry.js";

/** Renders the "circle-pile" icon from https://lucide.dev/icons/circle-pile. */
export const CirclePileIcon = createLucideIcon("circle-pile", circlePile);
