/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleArrowRight } from "../registry.js";

/** Renders the "circle-arrow-right" icon from https://lucide.dev/icons/circle-arrow-right. */
export const CircleArrowRightIcon = createLucideIcon("circle-arrow-right", circleArrowRight);
