/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleSmall } from "../registry.js";

/** Renders the "circle-small" icon from https://lucide.dev/icons/circle-small. */
export const CircleSmallIcon = createLucideIcon("circle-small", circleSmall);
