/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleCheck } from "../registry.js";

/** Renders the "circle-check" icon from https://lucide.dev/icons/circle-check. */
export const CircleCheckIcon = createLucideIcon("circle-check", circleCheck);
