/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { circleStar } from "../registry.js";

/** Renders the "circle-star" icon from https://lucide.dev/icons/circle-star. */
export const CircleStarIcon = createLucideIcon("circle-star", circleStar);
