/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clipboardClock } from "../registry.js";

/** Renders the "clipboard-clock" icon from https://lucide.dev/icons/clipboard-clock. */
export const ClipboardClockIcon = createLucideIcon("clipboard-clock", clipboardClock);
