/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clipboardPen } from "../registry.js";

/** Renders the "clipboard-pen" icon from https://lucide.dev/icons/clipboard-pen. */
export const ClipboardPenIcon = createLucideIcon("clipboard-pen", clipboardPen);
