/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clipboardPlus } from "../registry.js";

/** Renders the "clipboard-plus" icon from https://lucide.dev/icons/clipboard-plus. */
export const ClipboardPlusIcon = createLucideIcon("clipboard-plus", clipboardPlus);
