/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clipboardX } from "../registry.js";

/** Renders the "clipboard-x" icon from https://lucide.dev/icons/clipboard-x. */
export const ClipboardXIcon = createLucideIcon("clipboard-x", clipboardX);
