/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clockArrowDown } from "../registry.js";

/** Renders the "clock-arrow-down" icon from https://lucide.dev/icons/clock-arrow-down. */
export const ClockArrowDownIcon = createLucideIcon("clock-arrow-down", clockArrowDown);
