/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clockFading } from "../registry.js";

/** Renders the "clock-fading" icon from https://lucide.dev/icons/clock-fading. */
export const ClockFadingIcon = createLucideIcon("clock-fading", clockFading);
