/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clockArrowRight } from "../registry.js";

/** Renders the "clock-arrow-right" icon from https://lucide.dev/icons/clock-arrow-right. */
export const ClockArrowRightIcon = createLucideIcon("clock-arrow-right", clockArrowRight);
