/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock12 } from "../registry.js";

/** Renders the "clock-12" icon from https://lucide.dev/icons/clock-12. */
export const Clock12Icon = createLucideIcon("clock-12", clock12);
