/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clockPlus } from "../registry.js";

/** Renders the "clock-plus" icon from https://lucide.dev/icons/clock-plus. */
export const ClockPlusIcon = createLucideIcon("clock-plus", clockPlus);
