/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock8 } from "../registry.js";

/** Renders the "clock-8" icon from https://lucide.dev/icons/clock-8. */
export const Clock8Icon = createLucideIcon("clock-8", clock8);
