/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock4 } from "../registry.js";

/** Renders the "clock-4" icon from https://lucide.dev/icons/clock-4. */
export const Clock4Icon = createLucideIcon("clock-4", clock4);
