/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { clock3 } from "../registry.js";

/** Renders the "clock-3" icon from https://lucide.dev/icons/clock-3. */
export const Clock3Icon = createLucideIcon("clock-3", clock3);
