/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { closedCaption } from "../registry.js";

/** Renders the "closed-caption" icon from https://lucide.dev/icons/closed-caption. */
export const ClosedCaptionIcon = createLucideIcon("closed-caption", closedCaption);
