/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloudLightning } from "../registry.js";

/** Renders the "cloud-lightning" icon from https://lucide.dev/icons/cloud-lightning. */
export const CloudLightningIcon = createLucideIcon("cloud-lightning", cloudLightning);
