/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cloudSync } from "../registry.js";

/** Renders the "cloud-sync" icon from https://lucide.dev/icons/cloud-sync. */
export const CloudSyncIcon = createLucideIcon("cloud-sync", cloudSync);
