/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cog } from "../registry.js";

/** Renders the "cog" icon from https://lucide.dev/icons/cog. */
export const CogIcon = createLucideIcon("cog", cog);
