/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { columns3Cog } from "../registry.js";

/** Renders the "columns-3-cog" icon from https://lucide.dev/icons/columns-3-cog. */
export const Columns3CogIcon = createLucideIcon("columns-3-cog", columns3Cog);
