/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { combine } from "../registry.js";

/** Renders the "combine" icon from https://lucide.dev/icons/combine. */
export const CombineIcon = createLucideIcon("combine", combine);
