/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { conciergeBell } from "../registry.js";

/** Renders the "concierge-bell" icon from https://lucide.dev/icons/concierge-bell. */
export const ConciergeBellIcon = createLucideIcon("concierge-bell", conciergeBell);
