/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cookingPot } from "../registry.js";

/** Renders the "cooking-pot" icon from https://lucide.dev/icons/cooking-pot. */
export const CookingPotIcon = createLucideIcon("cooking-pot", cookingPot);
