/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { copyX } from "../registry.js";

/** Renders the "copy-x" icon from https://lucide.dev/icons/copy-x. */
export const CopyXIcon = createLucideIcon("copy-x", copyX);
