/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { cupSoda } from "../registry.js";

/** Renders the "cup-soda" icon from https://lucide.dev/icons/cup-soda. */
export const CupSodaIcon = createLucideIcon("cup-soda", cupSoda);
