/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { databaseSearch } from "../registry.js";

/** Renders the "database-search" icon from https://lucide.dev/icons/database-search. */
export const DatabaseSearchIcon = createLucideIcon("database-search", databaseSearch);
