/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { dessert } from "../registry.js";

/** Renders the "dessert" icon from https://lucide.dev/icons/dessert. */
export const DessertIcon = createLucideIcon("dessert", dessert);
