/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { diamondPercent } from "../registry.js";

/** Renders the "diamond-percent" icon from https://lucide.dev/icons/diamond-percent. */
export const DiamondPercentIcon = createLucideIcon("diamond-percent", diamondPercent);
