/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { dice6 } from "../registry.js";

/** Renders the "dice-6" icon from https://lucide.dev/icons/dice-6. */
export const Dice6Icon = createLucideIcon("dice-6", dice6);
