/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { disc2 } from "../registry.js";

/** Renders the "disc-2" icon from https://lucide.dev/icons/disc-2. */
export const Disc2Icon = createLucideIcon("disc-2", disc2);
