/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { discAlbum } from "../registry.js";

/** Renders the "disc-album" icon from https://lucide.dev/icons/disc-album. */
export const DiscAlbumIcon = createLucideIcon("disc-album", discAlbum);
