/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { dollarSign } from "../registry.js";

/** Renders the "dollar-sign" icon from https://lucide.dev/icons/dollar-sign. */
export const DollarSignIcon = createLucideIcon("dollar-sign", dollarSign);
