/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { doorClosed } from "../registry.js";

/** Renders the "door-closed" icon from https://lucide.dev/icons/door-closed. */
export const DoorClosedIcon = createLucideIcon("door-closed", doorClosed);
