/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { droplets } from "../registry.js";

/** Renders the "droplets" icon from https://lucide.dev/icons/droplets. */
export const DropletsIcon = createLucideIcon("droplets", droplets);
