/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { earOff } from "../registry.js";

/** Renders the "ear-off" icon from https://lucide.dev/icons/ear-off. */
export const EarOffIcon = createLucideIcon("ear-off", earOff);
