/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { eggFried } from "../registry.js";

/** Renders the "egg-fried" icon from https://lucide.dev/icons/egg-fried. */
export const EggFriedIcon = createLucideIcon("egg-fried", eggFried);
