/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { eggOff } from "../registry.js";

/** Renders the "egg-off" icon from https://lucide.dev/icons/egg-off. */
export const EggOffIcon = createLucideIcon("egg-off", eggOff);
