/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { ethernetPort } from "../registry.js";

/** Renders the "ethernet-port" icon from https://lucide.dev/icons/ethernet-port. */
export const EthernetPortIcon = createLucideIcon("ethernet-port", ethernetPort);
