/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { eyeOff } from "../registry.js";

/** Renders the "eye-off" icon from https://lucide.dev/icons/eye-off. */
export const EyeOffIcon = createLucideIcon("eye-off", eyeOff);
