/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fan } from "../registry.js";

/** Renders the "fan" icon from https://lucide.dev/icons/fan. */
export const FanIcon = createLucideIcon("fan", fan);
