/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileCodeCorner } from "../registry.js";

/** Renders the "file-code-corner" icon from https://lucide.dev/icons/file-code-corner. */
export const FileCodeCornerIcon = createLucideIcon("file-code-corner", fileCodeCorner);
