/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileScan } from "../registry.js";

/** Renders the "file-scan" icon from https://lucide.dev/icons/file-scan. */
export const FileScanIcon = createLucideIcon("file-scan", fileScan);
