/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileChartColumn } from "../registry.js";

/** Renders the "file-chart-column" icon from https://lucide.dev/icons/file-chart-column. */
export const FileChartColumnIcon = createLucideIcon("file-chart-column", fileChartColumn);
