/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileCheckCorner } from "../registry.js";

/** Renders the "file-check-corner" icon from https://lucide.dev/icons/file-check-corner. */
export const FileCheckCornerIcon = createLucideIcon("file-check-corner", fileCheckCorner);
