/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { file } from "../registry.js";

/** Renders the "file" icon from https://lucide.dev/icons/file. */
export const FileIcon = createLucideIcon("file", file);
