/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileImage } from "../registry.js";

/** Renders the "file-image" icon from https://lucide.dev/icons/file-image. */
export const FileImageIcon = createLucideIcon("file-image", fileImage);
