/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileCode } from "../registry.js";

/** Renders the "file-code" icon from https://lucide.dev/icons/file-code. */
export const FileCodeIcon = createLucideIcon("file-code", fileCode);
