/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fileHeadphone } from "../registry.js";

/** Renders the "file-headphone" icon from https://lucide.dev/icons/file-headphone. */
export const FileHeadphoneIcon = createLucideIcon("file-headphone", fileHeadphone);
