/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { fireExtinguisher } from "../registry.js";

/** Renders the "fire-extinguisher" icon from https://lucide.dev/icons/fire-extinguisher. */
export const FireExtinguisherIcon = createLucideIcon("fire-extinguisher", fireExtinguisher);
