/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { flashlight } from "../registry.js";

/** Renders the "flashlight" icon from https://lucide.dev/icons/flashlight. */
export const FlashlightIcon = createLucideIcon("flashlight", flashlight);
