/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { flipHorizontal2 } from "../registry.js";

/** Renders the "flip-horizontal-2" icon from https://lucide.dev/icons/flip-horizontal-2. */
export const FlipHorizontal2Icon = createLucideIcon("flip-horizontal-2", flipHorizontal2);
