/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { flower2 } from "../registry.js";

/** Renders the "flower-2" icon from https://lucide.dev/icons/flower-2. */
export const Flower2Icon = createLucideIcon("flower-2", flower2);
