/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderSymlink } from "../registry.js";

/** Renders the "folder-symlink" icon from https://lucide.dev/icons/folder-symlink. */
export const FolderSymlinkIcon = createLucideIcon("folder-symlink", folderSymlink);
