/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folders } from "../registry.js";

/** Renders the "folders" icon from https://lucide.dev/icons/folders. */
export const FoldersIcon = createLucideIcon("folders", folders);
