/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderTree } from "../registry.js";

/** Renders the "folder-tree" icon from https://lucide.dev/icons/folder-tree. */
export const FolderTreeIcon = createLucideIcon("folder-tree", folderTree);
