/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderPen } from "../registry.js";

/** Renders the "folder-pen" icon from https://lucide.dev/icons/folder-pen. */
export const FolderPenIcon = createLucideIcon("folder-pen", folderPen);
