/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderSync } from "../registry.js";

/** Renders the "folder-sync" icon from https://lucide.dev/icons/folder-sync. */
export const FolderSyncIcon = createLucideIcon("folder-sync", folderSync);
