/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderOpen } from "../registry.js";

/** Renders the "folder-open" icon from https://lucide.dev/icons/folder-open. */
export const FolderOpenIcon = createLucideIcon("folder-open", folderOpen);
