/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderMinus } from "../registry.js";

/** Renders the "folder-minus" icon from https://lucide.dev/icons/folder-minus. */
export const FolderMinusIcon = createLucideIcon("folder-minus", folderMinus);
