/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderBookmark } from "../registry.js";

/** Renders the "folder-bookmark" icon from https://lucide.dev/icons/folder-bookmark. */
export const FolderBookmarkIcon = createLucideIcon("folder-bookmark", folderBookmark);
