/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { foldHorizontal } from "../registry.js";

/** Renders the "fold-horizontal" icon from https://lucide.dev/icons/fold-horizontal. */
export const FoldHorizontalIcon = createLucideIcon("fold-horizontal", foldHorizontal);
