/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderCheck } from "../registry.js";

/** Renders the "folder-check" icon from https://lucide.dev/icons/folder-check. */
export const FolderCheckIcon = createLucideIcon("folder-check", folderCheck);
