/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderKey } from "../registry.js";

/** Renders the "folder-key" icon from https://lucide.dev/icons/folder-key. */
export const FolderKeyIcon = createLucideIcon("folder-key", folderKey);
