/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { folderSearch } from "../registry.js";

/** Renders the "folder-search" icon from https://lucide.dev/icons/folder-search. */
export const FolderSearchIcon = createLucideIcon("folder-search", folderSearch);
