/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { galleryVertical } from "../registry.js";

/** Renders the "gallery-vertical" icon from https://lucide.dev/icons/gallery-vertical. */
export const GalleryVerticalIcon = createLucideIcon("gallery-vertical", galleryVertical);
