/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gauge } from "../registry.js";

/** Renders the "gauge" icon from https://lucide.dev/icons/gauge. */
export const GaugeIcon = createLucideIcon("gauge", gauge);
