/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gitCommitHorizontal } from "../registry.js";

/** Renders the "git-commit-horizontal" icon from https://lucide.dev/icons/git-commit-horizontal. */
export const GitCommitHorizontalIcon = createLucideIcon(
	"git-commit-horizontal",
	gitCommitHorizontal,
);
