/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gitGraph } from "../registry.js";

/** Renders the "git-graph" icon from https://lucide.dev/icons/git-graph. */
export const GitGraphIcon = createLucideIcon("git-graph", gitGraph);
