/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { gitBranchMinus } from "../registry.js";

/** Renders the "git-branch-minus" icon from https://lucide.dev/icons/git-branch-minus. */
export const GitBranchMinusIcon = createLucideIcon("git-branch-minus", gitBranchMinus);
