/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { globeCheck } from "../registry.js";

/** Renders the "globe-check" icon from https://lucide.dev/icons/globe-check. */
export const GlobeCheckIcon = createLucideIcon("globe-check", globeCheck);
