/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { grid2x2X } from "../registry.js";

/** Renders the "grid-2x2-x" icon from https://lucide.dev/icons/grid-2x2-x. */
export const Grid2x2XIcon = createLucideIcon("grid-2x2-x", grid2x2X);
