/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { grid2x2Plus } from "../registry.js";

/** Renders the "grid-2x2-plus" icon from https://lucide.dev/icons/grid-2x2-plus. */
export const Grid2x2PlusIcon = createLucideIcon("grid-2x2-plus", grid2x2Plus);
