/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { grid3x2 } from "../registry.js";

/** Renders the "grid-3x2" icon from https://lucide.dev/icons/grid-3x2. */
export const Grid3x2Icon = createLucideIcon("grid-3x2", grid3x2);
