/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { hardDriveDownload } from "../registry.js";

/** Renders the "hard-drive-download" icon from https://lucide.dev/icons/hard-drive-download. */
export const HardDriveDownloadIcon = createLucideIcon("hard-drive-download", hardDriveDownload);
