/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { hardHat } from "../registry.js";

/** Renders the "hard-hat" icon from https://lucide.dev/icons/hard-hat. */
export const HardHatIcon = createLucideIcon("hard-hat", hardHat);
