/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heading1 } from "../registry.js";

/** Renders the "heading-1" icon from https://lucide.dev/icons/heading-1. */
export const Heading1Icon = createLucideIcon("heading-1", heading1);
