/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heading2 } from "../registry.js";

/** Renders the "heading-2" icon from https://lucide.dev/icons/heading-2. */
export const Heading2Icon = createLucideIcon("heading-2", heading2);
