/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heartHandshake } from "../registry.js";

/** Renders the "heart-handshake" icon from https://lucide.dev/icons/heart-handshake. */
export const HeartHandshakeIcon = createLucideIcon("heart-handshake", heartHandshake);
