/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heartPulse } from "../registry.js";

/** Renders the "heart-pulse" icon from https://lucide.dev/icons/heart-pulse. */
export const HeartPulseIcon = createLucideIcon("heart-pulse", heartPulse);
