/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heartPlus } from "../registry.js";

/** Renders the "heart-plus" icon from https://lucide.dev/icons/heart-plus. */
export const HeartPlusIcon = createLucideIcon("heart-plus", heartPlus);
