/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { heater } from "../registry.js";

/** Renders the "heater" icon from https://lucide.dev/icons/heater. */
export const HeaterIcon = createLucideIcon("heater", heater);
