/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { highlighter } from "../registry.js";

/** Renders the "highlighter" icon from https://lucide.dev/icons/highlighter. */
export const HighlighterIcon = createLucideIcon("highlighter", highlighter);
