/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { hotel } from "../registry.js";

/** Renders the "hotel" icon from https://lucide.dev/icons/hotel. */
export const HotelIcon = createLucideIcon("hotel", hotel);
