/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { houseHeart } from "../registry.js";

/** Renders the "house-heart" icon from https://lucide.dev/icons/house-heart. */
export const HouseHeartIcon = createLucideIcon("house-heart", houseHeart);
