/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { imageUpscale } from "../registry.js";

/** Renders the "image-upscale" icon from https://lucide.dev/icons/image-upscale. */
export const ImageUpscaleIcon = createLucideIcon("image-upscale", imageUpscale);
