/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { imageMinus } from "../registry.js";

/** Renders the "image-minus" icon from https://lucide.dev/icons/image-minus. */
export const ImageMinusIcon = createLucideIcon("image-minus", imageMinus);
