/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { images } from "../registry.js";

/** Renders the "images" icon from https://lucide.dev/icons/images. */
export const ImagesIcon = createLucideIcon("images", images);
