/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { keyboardMusic } from "../registry.js";

/** Renders the "keyboard-music" icon from https://lucide.dev/icons/keyboard-music. */
export const KeyboardMusicIcon = createLucideIcon("keyboard-music", keyboardMusic);
