/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { laptopMinimal } from "../registry.js";

/** Renders the "laptop-minimal" icon from https://lucide.dev/icons/laptop-minimal. */
export const LaptopMinimalIcon = createLucideIcon("laptop-minimal", laptopMinimal);
