/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lassoSelect } from "../registry.js";

/** Renders the "lasso-select" icon from https://lucide.dev/icons/lasso-select. */
export const LassoSelectIcon = createLucideIcon("lasso-select", lassoSelect);
