/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lasso } from "../registry.js";

/** Renders the "lasso" icon from https://lucide.dev/icons/lasso. */
export const LassoIcon = createLucideIcon("lasso", lasso);
