/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { layersPlus } from "../registry.js";

/** Renders the "layers-plus" icon from https://lucide.dev/icons/layers-plus. */
export const LayersPlusIcon = createLucideIcon("layers-plus", layersPlus);
