/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { layoutPanelTop } from "../registry.js";

/** Renders the "layout-panel-top" icon from https://lucide.dev/icons/layout-panel-top. */
export const LayoutPanelTopIcon = createLucideIcon("layout-panel-top", layoutPanelTop);
