/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lensConvex } from "../registry.js";

/** Renders the "lens-convex" icon from https://lucide.dev/icons/lens-convex. */
export const LensConvexIcon = createLucideIcon("lens-convex", lensConvex);
