/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lineDotRightHorizontal } from "../registry.js";

/** Renders the "line-dot-right-horizontal" icon from https://lucide.dev/icons/line-dot-right-horizontal. */
export const LineDotRightHorizontalIcon = createLucideIcon(
	"line-dot-right-horizontal",
	lineDotRightHorizontal,
);
