/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { listTree } from "../registry.js";

/** Renders the "list-tree" icon from https://lucide.dev/icons/list-tree. */
export const ListTreeIcon = createLucideIcon("list-tree", listTree);
