/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { listVideo } from "../registry.js";

/** Renders the "list-video" icon from https://lucide.dev/icons/list-video. */
export const ListVideoIcon = createLucideIcon("list-video", listVideo);
