/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { locateFixed } from "../registry.js";

/** Renders the "locate-fixed" icon from https://lucide.dev/icons/locate-fixed. */
export const LocateFixedIcon = createLucideIcon("locate-fixed", locateFixed);
