/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lockKeyhole } from "../registry.js";

/** Renders the "lock-keyhole" icon from https://lucide.dev/icons/lock-keyhole. */
export const LockKeyholeIcon = createLucideIcon("lock-keyhole", lockKeyhole);
