/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { lockKeyholeOpen } from "../registry.js";

/** Renders the "lock-keyhole-open" icon from https://lucide.dev/icons/lock-keyhole-open. */
export const LockKeyholeOpenIcon = createLucideIcon("lock-keyhole-open", lockKeyholeOpen);
