/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mailPlus } from "../registry.js";

/** Renders the "mail-plus" icon from https://lucide.dev/icons/mail-plus. */
export const MailPlusIcon = createLucideIcon("mail-plus", mailPlus);
