/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mailCheck } from "../registry.js";

/** Renders the "mail-check" icon from https://lucide.dev/icons/mail-check. */
export const MailCheckIcon = createLucideIcon("mail-check", mailCheck);
