/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mailWarning } from "../registry.js";

/** Renders the "mail-warning" icon from https://lucide.dev/icons/mail-warning. */
export const MailWarningIcon = createLucideIcon("mail-warning", mailWarning);
