/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mailQuestionMark } from "../registry.js";

/** Renders the "mail-question-mark" icon from https://lucide.dev/icons/mail-question-mark. */
export const MailQuestionMarkIcon = createLucideIcon("mail-question-mark", mailQuestionMark);
