/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mapPinCheck } from "../registry.js";

/** Renders the "map-pin-check" icon from https://lucide.dev/icons/map-pin-check. */
export const MapPinCheckIcon = createLucideIcon("map-pin-check", mapPinCheck);
