/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mapPinHouse } from "../registry.js";

/** Renders the "map-pin-house" icon from https://lucide.dev/icons/map-pin-house. */
export const MapPinHouseIcon = createLucideIcon("map-pin-house", mapPinHouse);
