/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mapPlus } from "../registry.js";

/** Renders the "map-plus" icon from https://lucide.dev/icons/map-plus. */
export const MapPlusIcon = createLucideIcon("map-plus", mapPlus);
