/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mapPinOff } from "../registry.js";

/** Renders the "map-pin-off" icon from https://lucide.dev/icons/map-pin-off. */
export const MapPinOffIcon = createLucideIcon("map-pin-off", mapPinOff);
