/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { maximize2 } from "../registry.js";

/** Renders the "maximize-2" icon from https://lucide.dev/icons/maximize-2. */
export const Maximize2Icon = createLucideIcon("maximize-2", maximize2);
