/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { megaphoneOff } from "../registry.js";

/** Renders the "megaphone-off" icon from https://lucide.dev/icons/megaphone-off. */
export const MegaphoneOffIcon = createLucideIcon("megaphone-off", megaphoneOff);
