/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageCircleWarning } from "../registry.js";

/** Renders the "message-circle-warning" icon from https://lucide.dev/icons/message-circle-warning. */
export const MessageCircleWarningIcon = createLucideIcon(
	"message-circle-warning",
	messageCircleWarning,
);
