/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageCircleMore } from "../registry.js";

/** Renders the "message-circle-more" icon from https://lucide.dev/icons/message-circle-more. */
export const MessageCircleMoreIcon = createLucideIcon("message-circle-more", messageCircleMore);
