/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { messageSquareWarning } from "../registry.js";

/** Renders the "message-square-warning" icon from https://lucide.dev/icons/message-square-warning. */
export const MessageSquareWarningIcon = createLucideIcon(
	"message-square-warning",
	messageSquareWarning,
);
