/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { microscope } from "../registry.js";

/** Renders the "microscope" icon from https://lucide.dev/icons/microscope. */
export const MicroscopeIcon = createLucideIcon("microscope", microscope);
