/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { monitorPlay } from "../registry.js";

/** Renders the "monitor-play" icon from https://lucide.dev/icons/monitor-play. */
export const MonitorPlayIcon = createLucideIcon("monitor-play", monitorPlay);
