/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { monitorSpeaker } from "../registry.js";

/** Renders the "monitor-speaker" icon from https://lucide.dev/icons/monitor-speaker. */
export const MonitorSpeakerIcon = createLucideIcon("monitor-speaker", monitorSpeaker);
