/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mountainSnow } from "../registry.js";

/** Renders the "mountain-snow" icon from https://lucide.dev/icons/mountain-snow. */
export const MountainSnowIcon = createLucideIcon("mountain-snow", mountainSnow);
