/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { mouseOff } from "../registry.js";

/** Renders the "mouse-off" icon from https://lucide.dev/icons/mouse-off. */
export const MouseOffIcon = createLucideIcon("mouse-off", mouseOff);
