/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { moveDownLeft } from "../registry.js";

/** Renders the "move-down-left" icon from https://lucide.dev/icons/move-down-left. */
export const MoveDownLeftIcon = createLucideIcon("move-down-left", moveDownLeft);
