/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { moveRight } from "../registry.js";

/** Renders the "move-right" icon from https://lucide.dev/icons/move-right. */
export const MoveRightIcon = createLucideIcon("move-right", moveRight);
