/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { move3d } from "../registry.js";

/** Renders the "move-3d" icon from https://lucide.dev/icons/move-3d. */
export const Move3dIcon = createLucideIcon("move-3d", move3d);
