/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { music2 } from "../registry.js";

/** Renders the "music-2" icon from https://lucide.dev/icons/music-2. */
export const Music2Icon = createLucideIcon("music-2", music2);
