/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { music3 } from "../registry.js";

/** Renders the "music-3" icon from https://lucide.dev/icons/music-3. */
export const Music3Icon = createLucideIcon("music-3", music3);
