/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { music } from "../registry.js";

/** Renders the "music" icon from https://lucide.dev/icons/music. */
export const MusicIcon = createLucideIcon("music", music);
