/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { navigationOff } from "../registry.js";

/** Renders the "navigation-off" icon from https://lucide.dev/icons/navigation-off. */
export const NavigationOffIcon = createLucideIcon("navigation-off", navigationOff);
