/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { navigation2 } from "../registry.js";

/** Renders the "navigation-2" icon from https://lucide.dev/icons/navigation-2. */
export const Navigation2Icon = createLucideIcon("navigation-2", navigation2);
