/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { nut } from "../registry.js";

/** Renders the "nut" icon from https://lucide.dev/icons/nut. */
export const NutIcon = createLucideIcon("nut", nut);
