/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { packageSearch } from "../registry.js";

/** Renders the "package-search" icon from https://lucide.dev/icons/package-search. */
export const PackageSearchIcon = createLucideIcon("package-search", packageSearch);
