/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { packageOpen } from "../registry.js";

/** Renders the "package-open" icon from https://lucide.dev/icons/package-open. */
export const PackageOpenIcon = createLucideIcon("package-open", packageOpen);
