/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { panelRightDashed } from "../registry.js";

/** Renders the "panel-right-dashed" icon from https://lucide.dev/icons/panel-right-dashed. */
export const PanelRightDashedIcon = createLucideIcon("panel-right-dashed", panelRightDashed);
