/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { personStanding } from "../registry.js";

/** Renders the "person-standing" icon from https://lucide.dev/icons/person-standing. */
export const PersonStandingIcon = createLucideIcon("person-standing", personStanding);
