/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { phone } from "../registry.js";

/** Renders the "phone" icon from https://lucide.dev/icons/phone. */
export const PhoneIcon = createLucideIcon("phone", phone);
