/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { piggyBank } from "../registry.js";

/** Renders the "piggy-bank" icon from https://lucide.dev/icons/piggy-bank. */
export const PiggyBankIcon = createLucideIcon("piggy-bank", piggyBank);
