/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { pilcrow } from "../registry.js";

/** Renders the "pilcrow" icon from https://lucide.dev/icons/pilcrow. */
export const PilcrowIcon = createLucideIcon("pilcrow", pilcrow);
