/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { plug2 } from "../registry.js";

/** Renders the "plug-2" icon from https://lucide.dev/icons/plug-2. */
export const Plug2Icon = createLucideIcon("plug-2", plug2);
