/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { printerCheck } from "../registry.js";

/** Renders the "printer-check" icon from https://lucide.dev/icons/printer-check. */
export const PrinterCheckIcon = createLucideIcon("printer-check", printerCheck);
