/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { pyramid } from "../registry.js";

/** Renders the "pyramid" icon from https://lucide.dev/icons/pyramid. */
export const PyramidIcon = createLucideIcon("pyramid", pyramid);
