/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rabbit } from "../registry.js";

/** Renders the "rabbit" icon from https://lucide.dev/icons/rabbit. */
export const RabbitIcon = createLucideIcon("rabbit", rabbit);
