/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { radioTower } from "../registry.js";

/** Renders the "radio-tower" icon from https://lucide.dev/icons/radio-tower. */
export const RadioTowerIcon = createLucideIcon("radio-tower", radioTower);
