/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { receiptTurkishLira } from "../registry.js";

/** Renders the "receipt-turkish-lira" icon from https://lucide.dev/icons/receipt-turkish-lira. */
export const ReceiptTurkishLiraIcon = createLucideIcon("receipt-turkish-lira", receiptTurkishLira);
