/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { receiptCent } from "../registry.js";

/** Renders the "receipt-cent" icon from https://lucide.dev/icons/receipt-cent. */
export const ReceiptCentIcon = createLucideIcon("receipt-cent", receiptCent);
