/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { receiptRussianRuble } from "../registry.js";

/** Renders the "receipt-russian-ruble" icon from https://lucide.dev/icons/receipt-russian-ruble. */
export const ReceiptRussianRubleIcon = createLucideIcon(
	"receipt-russian-ruble",
	receiptRussianRuble,
);
