/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { receiptSwissFranc } from "../registry.js";

/** Renders the "receipt-swiss-franc" icon from https://lucide.dev/icons/receipt-swiss-franc. */
export const ReceiptSwissFrancIcon = createLucideIcon("receipt-swiss-franc", receiptSwissFranc);
