/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { receiptPoundSterling } from "../registry.js";

/** Renders the "receipt-pound-sterling" icon from https://lucide.dev/icons/receipt-pound-sterling. */
export const ReceiptPoundSterlingIcon = createLucideIcon(
	"receipt-pound-sterling",
	receiptPoundSterling,
);
