/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rectangleVertical } from "../registry.js";

/** Renders the "rectangle-vertical" icon from https://lucide.dev/icons/rectangle-vertical. */
export const RectangleVerticalIcon = createLucideIcon("rectangle-vertical", rectangleVertical);
