/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { recycle } from "../registry.js";

/** Renders the "recycle" icon from https://lucide.dev/icons/recycle. */
export const RecycleIcon = createLucideIcon("recycle", recycle);
