/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { redo2 } from "../registry.js";

/** Renders the "redo-2" icon from https://lucide.dev/icons/redo-2. */
export const Redo2Icon = createLucideIcon("redo-2", redo2);
