/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { redoDot } from "../registry.js";

/** Renders the "redo-dot" icon from https://lucide.dev/icons/redo-dot. */
export const RedoDotIcon = createLucideIcon("redo-dot", redoDot);
