/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { repeat1 } from "../registry.js";

/** Renders the "repeat-1" icon from https://lucide.dev/icons/repeat-1. */
export const Repeat1Icon = createLucideIcon("repeat-1", repeat1);
