/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { repeat2 } from "../registry.js";

/** Renders the "repeat-2" icon from https://lucide.dev/icons/repeat-2. */
export const Repeat2Icon = createLucideIcon("repeat-2", repeat2);
