/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rockingChair } from "../registry.js";

/** Renders the "rocking-chair" icon from https://lucide.dev/icons/rocking-chair. */
export const RockingChairIcon = createLucideIcon("rocking-chair", rockingChair);
