/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rotateCcwSquare } from "../registry.js";

/** Renders the "rotate-ccw-square" icon from https://lucide.dev/icons/rotate-ccw-square. */
export const RotateCcwSquareIcon = createLucideIcon("rotate-ccw-square", rotateCcwSquare);
