/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { rows2 } from "../registry.js";

/** Renders the "rows-2" icon from https://lucide.dev/icons/rows-2. */
export const Rows2Icon = createLucideIcon("rows-2", rows2);
