/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { savePen } from "../registry.js";

/** Renders the "save-pen" icon from https://lucide.dev/icons/save-pen. */
export const SavePenIcon = createLucideIcon("save-pen", savePen);
