/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { scale3d } from "../registry.js";

/** Renders the "scale-3d" icon from https://lucide.dev/icons/scale-3d. */
export const Scale3dIcon = createLucideIcon("scale-3d", scale3d);
