/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { scanHeart } from "../registry.js";

/** Renders the "scan-heart" icon from https://lucide.dev/icons/scan-heart. */
export const ScanHeartIcon = createLucideIcon("scan-heart", scanHeart);
