/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { scanEye } from "../registry.js";

/** Renders the "scan-eye" icon from https://lucide.dev/icons/scan-eye. */
export const ScanEyeIcon = createLucideIcon("scan-eye", scanEye);
