/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { scanFace } from "../registry.js";

/** Renders the "scan-face" icon from https://lucide.dev/icons/scan-face. */
export const ScanFaceIcon = createLucideIcon("scan-face", scanFace);
