/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { school } from "../registry.js";

/** Renders the "school" icon from https://lucide.dev/icons/school. */
export const SchoolIcon = createLucideIcon("school", school);
