/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { scissorsLineDashed } from "../registry.js";

/** Renders the "scissors-line-dashed" icon from https://lucide.dev/icons/scissors-line-dashed. */
export const ScissorsLineDashedIcon = createLucideIcon("scissors-line-dashed", scissorsLineDashed);
