/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { scooter } from "../registry.js";

/** Renders the "scooter" icon from https://lucide.dev/icons/scooter. */
export const ScooterIcon = createLucideIcon("scooter", scooter);
