/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { scrollText } from "../registry.js";

/** Renders the "scroll-text" icon from https://lucide.dev/icons/scroll-text. */
export const ScrollTextIcon = createLucideIcon("scroll-text", scrollText);
