/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { searchCode } from "../registry.js";

/** Renders the "search-code" icon from https://lucide.dev/icons/search-code. */
export const SearchCodeIcon = createLucideIcon("search-code", searchCode);
