/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { searchSlash } from "../registry.js";

/** Renders the "search-slash" icon from https://lucide.dev/icons/search-slash. */
export const SearchSlashIcon = createLucideIcon("search-slash", searchSlash);
