/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sendToBack } from "../registry.js";

/** Renders the "send-to-back" icon from https://lucide.dev/icons/send-to-back. */
export const SendToBackIcon = createLucideIcon("send-to-back", sendToBack);
