/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { separatorVertical } from "../registry.js";

/** Renders the "separator-vertical" icon from https://lucide.dev/icons/separator-vertical. */
export const SeparatorVerticalIcon = createLucideIcon("separator-vertical", separatorVertical);
