/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { separatorHorizontal } from "../registry.js";

/** Renders the "separator-horizontal" icon from https://lucide.dev/icons/separator-horizontal. */
export const SeparatorHorizontalIcon = createLucideIcon(
	"separator-horizontal",
	separatorHorizontal,
);
