/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { serverCrash } from "../registry.js";

/** Renders the "server-crash" icon from https://lucide.dev/icons/server-crash. */
export const ServerCrashIcon = createLucideIcon("server-crash", serverCrash);
