/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { server } from "../registry.js";

/** Renders the "server" icon from https://lucide.dev/icons/server. */
export const ServerIcon = createLucideIcon("server", server);
