/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { shieldBan } from "../registry.js";

/** Renders the "shield-ban" icon from https://lucide.dev/icons/shield-ban. */
export const ShieldBanIcon = createLucideIcon("shield-ban", shieldBan);
