/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { shieldCogCorner } from "../registry.js";

/** Renders the "shield-cog-corner" icon from https://lucide.dev/icons/shield-cog-corner. */
export const ShieldCogCornerIcon = createLucideIcon("shield-cog-corner", shieldCogCorner);
