/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { shieldX } from "../registry.js";

/** Renders the "shield-x" icon from https://lucide.dev/icons/shield-x. */
export const ShieldXIcon = createLucideIcon("shield-x", shieldX);
