/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { shieldPlus } from "../registry.js";

/** Renders the "shield-plus" icon from https://lucide.dev/icons/shield-plus. */
export const ShieldPlusIcon = createLucideIcon("shield-plus", shieldPlus);
