/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { shoppingBag } from "../registry.js";

/** Renders the "shopping-bag" icon from https://lucide.dev/icons/shopping-bag. */
export const ShoppingBagIcon = createLucideIcon("shopping-bag", shoppingBag);
