/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { signal } from "../registry.js";

/** Renders the "signal" icon from https://lucide.dev/icons/signal. */
export const SignalIcon = createLucideIcon("signal", signal);
