/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { signalMedium } from "../registry.js";

/** Renders the "signal-medium" icon from https://lucide.dev/icons/signal-medium. */
export const SignalMediumIcon = createLucideIcon("signal-medium", signalMedium);
