/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { slidersHorizontal } from "../registry.js";

/** Renders the "sliders-horizontal" icon from https://lucide.dev/icons/sliders-horizontal. */
export const SlidersHorizontalIcon = createLucideIcon("sliders-horizontal", slidersHorizontal);
