/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { smartphoneCharging } from "../registry.js";

/** Renders the "smartphone-charging" icon from https://lucide.dev/icons/smartphone-charging. */
export const SmartphoneChargingIcon = createLucideIcon("smartphone-charging", smartphoneCharging);
