/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { smilePlus } from "../registry.js";

/** Renders the "smile-plus" icon from https://lucide.dev/icons/smile-plus. */
export const SmilePlusIcon = createLucideIcon("smile-plus", smilePlus);
