/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { snail } from "../registry.js";

/** Renders the "snail" icon from https://lucide.dev/icons/snail. */
export const SnailIcon = createLucideIcon("snail", snail);
