/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { spellCheck } from "../registry.js";

/** Renders the "spell-check" icon from https://lucide.dev/icons/spell-check. */
export const SpellCheckIcon = createLucideIcon("spell-check", spellCheck);
