/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { spline } from "../registry.js";

/** Renders the "spline" icon from https://lucide.dev/icons/spline. */
export const SplineIcon = createLucideIcon("spline", spline);
