/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareMousePointer } from "../registry.js";

/** Renders the "square-mouse-pointer" icon from https://lucide.dev/icons/square-mouse-pointer. */
export const SquareMousePointerIcon = createLucideIcon("square-mouse-pointer", squareMousePointer);
