/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareCheckBig } from "../registry.js";

/** Renders the "square-check-big" icon from https://lucide.dev/icons/square-check-big. */
export const SquareCheckBigIcon = createLucideIcon("square-check-big", squareCheckBig);
