/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareChevronLeft } from "../registry.js";

/** Renders the "square-chevron-left" icon from https://lucide.dev/icons/square-chevron-left. */
export const SquareChevronLeftIcon = createLucideIcon("square-chevron-left", squareChevronLeft);
