/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareAsterisk } from "../registry.js";

/** Renders the "square-asterisk" icon from https://lucide.dev/icons/square-asterisk. */
export const SquareAsteriskIcon = createLucideIcon("square-asterisk", squareAsterisk);
