/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareParking } from "../registry.js";

/** Renders the "square-parking" icon from https://lucide.dev/icons/square-parking. */
export const SquareParkingIcon = createLucideIcon("square-parking", squareParking);
