/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareArrowUpRight } from "../registry.js";

/** Renders the "square-arrow-up-right" icon from https://lucide.dev/icons/square-arrow-up-right. */
export const SquareArrowUpRightIcon = createLucideIcon("square-arrow-up-right", squareArrowUpRight);
