/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareUserRound } from "../registry.js";

/** Renders the "square-user-round" icon from https://lucide.dev/icons/square-user-round. */
export const SquareUserRoundIcon = createLucideIcon("square-user-round", squareUserRound);
