/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareChevronDown } from "../registry.js";

/** Renders the "square-chevron-down" icon from https://lucide.dev/icons/square-chevron-down. */
export const SquareChevronDownIcon = createLucideIcon("square-chevron-down", squareChevronDown);
