/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareArrowUpLeft } from "../registry.js";

/** Renders the "square-arrow-up-left" icon from https://lucide.dev/icons/square-arrow-up-left. */
export const SquareArrowUpLeftIcon = createLucideIcon("square-arrow-up-left", squareArrowUpLeft);
