/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareArrowOutDownRight } from "../registry.js";

/** Renders the "square-arrow-out-down-right" icon from https://lucide.dev/icons/square-arrow-out-down-right. */
export const SquareArrowOutDownRightIcon = createLucideIcon(
	"square-arrow-out-down-right",
	squareArrowOutDownRight,
);
