/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareFunction } from "../registry.js";

/** Renders the "square-function" icon from https://lucide.dev/icons/square-function. */
export const SquareFunctionIcon = createLucideIcon("square-function", squareFunction);
