/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { squareDashedTopSolid } from "../registry.js";

/** Renders the "square-dashed-top-solid" icon from https://lucide.dev/icons/square-dashed-top-solid. */
export const SquareDashedTopSolidIcon = createLucideIcon(
	"square-dashed-top-solid",
	squareDashedTopSolid,
);
