/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { stickyNoteX } from "../registry.js";

/** Renders the "sticky-note-x" icon from https://lucide.dev/icons/sticky-note-x. */
export const StickyNoteXIcon = createLucideIcon("sticky-note-x", stickyNoteX);
