/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { stickyNote } from "../registry.js";

/** Renders the "sticky-note" icon from https://lucide.dev/icons/sticky-note. */
export const StickyNoteIcon = createLucideIcon("sticky-note", stickyNote);
