/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sunSnow } from "../registry.js";

/** Renders the "sun-snow" icon from https://lucide.dev/icons/sun-snow. */
export const SunSnowIcon = createLucideIcon("sun-snow", sunSnow);
