/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sunMedium } from "../registry.js";

/** Renders the "sun-medium" icon from https://lucide.dev/icons/sun-medium. */
export const SunMediumIcon = createLucideIcon("sun-medium", sunMedium);
