/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { sunrise } from "../registry.js";

/** Renders the "sunrise" icon from https://lucide.dev/icons/sunrise. */
export const SunriseIcon = createLucideIcon("sunrise", sunrise);
