/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tableCellsMerge } from "../registry.js";

/** Renders the "table-cells-merge" icon from https://lucide.dev/icons/table-cells-merge. */
export const TableCellsMergeIcon = createLucideIcon("table-cells-merge", tableCellsMerge);
