/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tabletSmartphone } from "../registry.js";

/** Renders the "tablet-smartphone" icon from https://lucide.dev/icons/tablet-smartphone. */
export const TabletSmartphoneIcon = createLucideIcon("tablet-smartphone", tabletSmartphone);
