/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tableRowsSplit } from "../registry.js";

/** Renders the "table-rows-split" icon from https://lucide.dev/icons/table-rows-split. */
export const TableRowsSplitIcon = createLucideIcon("table-rows-split", tableRowsSplit);
