/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tally2 } from "../registry.js";

/** Renders the "tally-2" icon from https://lucide.dev/icons/tally-2. */
export const Tally2Icon = createLucideIcon("tally-2", tally2);
