/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tally4 } from "../registry.js";

/** Renders the "tally-4" icon from https://lucide.dev/icons/tally-4. */
export const Tally4Icon = createLucideIcon("tally-4", tally4);
