/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { telescope } from "../registry.js";

/** Renders the "telescope" icon from https://lucide.dev/icons/telescope. */
export const TelescopeIcon = createLucideIcon("telescope", telescope);
