/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { testTube } from "../registry.js";

/** Renders the "test-tube" icon from https://lucide.dev/icons/test-tube. */
export const TestTubeIcon = createLucideIcon("test-tube", testTube);
