/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { textAlignEnd } from "../registry.js";

/** Renders the "text-align-end" icon from https://lucide.dev/icons/text-align-end. */
export const TextAlignEndIcon = createLucideIcon("text-align-end", textAlignEnd);
