/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { textCursorInput } from "../registry.js";

/** Renders the "text-cursor-input" icon from https://lucide.dev/icons/text-cursor-input. */
export const TextCursorInputIcon = createLucideIcon("text-cursor-input", textCursorInput);
