/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { toggleRight } from "../registry.js";

/** Renders the "toggle-right" icon from https://lucide.dev/icons/toggle-right. */
export const ToggleRightIcon = createLucideIcon("toggle-right", toggleRight);
