/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { trainFrontTunnel } from "../registry.js";

/** Renders the "train-front-tunnel" icon from https://lucide.dev/icons/train-front-tunnel. */
export const TrainFrontTunnelIcon = createLucideIcon("train-front-tunnel", trainFrontTunnel);
