/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { treePalm } from "../registry.js";

/** Renders the "tree-palm" icon from https://lucide.dev/icons/tree-palm. */
export const TreePalmIcon = createLucideIcon("tree-palm", treePalm);
