/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { trendingUp } from "../registry.js";

/** Renders the "trending-up" icon from https://lucide.dev/icons/trending-up. */
export const TrendingUpIcon = createLucideIcon("trending-up", trendingUp);
