/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { tvMinimal } from "../registry.js";

/** Renders the "tv-minimal" icon from https://lucide.dev/icons/tv-minimal. */
export const TvMinimalIcon = createLucideIcon("tv-minimal", tvMinimal);
