/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { umbrellaOff } from "../registry.js";

/** Renders the "umbrella-off" icon from https://lucide.dev/icons/umbrella-off. */
export const UmbrellaOffIcon = createLucideIcon("umbrella-off", umbrellaOff);
