/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { undo2 } from "../registry.js";

/** Renders the "undo-2" icon from https://lucide.dev/icons/undo-2. */
export const Undo2Icon = createLucideIcon("undo-2", undo2);
