/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { unfoldHorizontal } from "../registry.js";

/** Renders the "unfold-horizontal" icon from https://lucide.dev/icons/unfold-horizontal. */
export const UnfoldHorizontalIcon = createLucideIcon("unfold-horizontal", unfoldHorizontal);
