/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { university } from "../registry.js";

/** Renders the "university" icon from https://lucide.dev/icons/university. */
export const UniversityIcon = createLucideIcon("university", university);
