/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userSearch } from "../registry.js";

/** Renders the "user-search" icon from https://lucide.dev/icons/user-search. */
export const UserSearchIcon = createLucideIcon("user-search", userSearch);
