/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userRoundPlus } from "../registry.js";

/** Renders the "user-round-plus" icon from https://lucide.dev/icons/user-round-plus. */
export const UserRoundPlusIcon = createLucideIcon("user-round-plus", userRoundPlus);
