/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userX } from "../registry.js";

/** Renders the "user-x" icon from https://lucide.dev/icons/user-x. */
export const UserXIcon = createLucideIcon("user-x", userX);
