/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userCheck } from "../registry.js";

/** Renders the "user-check" icon from https://lucide.dev/icons/user-check. */
export const UserCheckIcon = createLucideIcon("user-check", userCheck);
