/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { userLock } from "../registry.js";

/** Renders the "user-lock" icon from https://lucide.dev/icons/user-lock. */
export const UserLockIcon = createLucideIcon("user-lock", userLock);
