/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { videotape } from "../registry.js";

/** Renders the "videotape" icon from https://lucide.dev/icons/videotape. */
export const VideotapeIcon = createLucideIcon("videotape", videotape);
