/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { vote } from "../registry.js";

/** Renders the "vote" icon from https://lucide.dev/icons/vote. */
export const VoteIcon = createLucideIcon("vote", vote);
