/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { walletMinimal } from "../registry.js";

/** Renders the "wallet-minimal" icon from https://lucide.dev/icons/wallet-minimal. */
export const WalletMinimalIcon = createLucideIcon("wallet-minimal", walletMinimal);
