/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { washingMachine } from "../registry.js";

/** Renders the "washing-machine" icon from https://lucide.dev/icons/washing-machine. */
export const WashingMachineIcon = createLucideIcon("washing-machine", washingMachine);
