/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wavesVertical } from "../registry.js";

/** Renders the "waves-vertical" icon from https://lucide.dev/icons/waves-vertical. */
export const WavesVerticalIcon = createLucideIcon("waves-vertical", wavesVertical);
