/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { webhookOff } from "../registry.js";

/** Renders the "webhook-off" icon from https://lucide.dev/icons/webhook-off. */
export const WebhookOffIcon = createLucideIcon("webhook-off", webhookOff);
