/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { weightTilde } from "../registry.js";

/** Renders the "weight-tilde" icon from https://lucide.dev/icons/weight-tilde. */
export const WeightTildeIcon = createLucideIcon("weight-tilde", weightTilde);
