/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wholeWord } from "../registry.js";

/** Renders the "whole-word" icon from https://lucide.dev/icons/whole-word. */
export const WholeWordIcon = createLucideIcon("whole-word", wholeWord);
