/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wifiLow } from "../registry.js";

/** Renders the "wifi-low" icon from https://lucide.dev/icons/wifi-low. */
export const WifiLowIcon = createLucideIcon("wifi-low", wifiLow);
