/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wifiCog } from "../registry.js";

/** Renders the "wifi-cog" icon from https://lucide.dev/icons/wifi-cog. */
export const WifiCogIcon = createLucideIcon("wifi-cog", wifiCog);
