/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { wifiZero } from "../registry.js";

/** Renders the "wifi-zero" icon from https://lucide.dev/icons/wifi-zero. */
export const WifiZeroIcon = createLucideIcon("wifi-zero", wifiZero);
