/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { zodiacCapricorn } from "../registry.js";

/** Renders the "zodiac-capricorn" icon from https://lucide.dev/icons/zodiac-capricorn. */
export const ZodiacCapricornIcon = createLucideIcon("zodiac-capricorn", zodiacCapricorn);
