/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { zodiacTaurus } from "../registry.js";

/** Renders the "zodiac-taurus" icon from https://lucide.dev/icons/zodiac-taurus. */
export const ZodiacTaurusIcon = createLucideIcon("zodiac-taurus", zodiacTaurus);
