/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { zodiacGemini } from "../registry.js";

/** Renders the "zodiac-gemini" icon from https://lucide.dev/icons/zodiac-gemini. */
export const ZodiacGeminiIcon = createLucideIcon("zodiac-gemini", zodiacGemini);
