/**
 * Generated by `bun run generate` from Lucide's icon data. Do not edit by hand.
 *
 * @author [Sergio Xalambrí](https://sergiodxa.com)
 * @copyright Sergio Xalambrí 2026
 */

import { createLucideIcon } from "../create-lucide-icon.js";
import { zodiacLibra } from "../registry.js";

/** Renders the "zodiac-libra" icon from https://lucide.dev/icons/zodiac-libra. */
export const ZodiacLibraIcon = createLucideIcon("zodiac-libra", zodiacLibra);
